### ISSUE TITLE
Latest Version does not appear to be documented on github

### ISSUE THREAD

**Issue by philrasch** [vgough/encfs#100]
I just built a new version of encfs by downloading the source as a  zip file from the github repo. Everything works fine, but in checking to make sure I was using the new build, I entered "encfs --version" and it returns "encfs version 1.9..0". I cannot find any mention of a tag, or release on github or in the changelog with this number, which appear to end at 1.8.1. It makes me a bit nervous to be using a version beyond the documentation.

Among other things, I am wondering whether there are any "gotchas" that might cause me problems in mixing this new version of encfs on one machine with older versions on another machine.

Thanks for any advice you might have.

**Comment by vgough** [comment]
github HEAD contains code which has not yet been released.  I should really change the version to something like "1.9.0-beta", or "1.8.99" until a real 1.9 is released.

There shouldn't be any showstoppers on HEAD, so you should be safe.  I wouldn't say the same for other branches, in particular the dev branch.  But what you have is really 1.8 + some patches, not 1.9 (which doesn't exist yet).
