### ISSUE TITLE
encfsctl showcruft shows ~/.encfs6.xml

### ISSUE THREAD

**Issue by andrewferrier** [vgough/encfs#101]
If I use `encfsctl showcruft` on an (unmounted) encfs-encrypted directory (which otherwise works fine):

```
encfsctl showcruft ~/Dropbox/.encfs-crypted
EncFS Password:
In directory /:
/Users/myusername/Dropbox/.encfs-crypted//.encfs6.xml
Found 1 invalid file.
```

As you can see, it identifies `.encfs6.xml` as cruft. But surely this is the very opposite? This file is essential to encfs' working. Granted, it technically isn't an encrypted file for the filesystem, but it would seem logical to exclude it from showcruft, since it will always be present.

I am using encfs 1.8.1 on OS X 10.10.4. I also see the same problem with encfs 1.7.4 on Ubuntu 14.04.2.

**Comment by antofthy** [comment]
Whether .encfs6.xml is cruft or not, is debatable!
Technically it is part of the 'normal' usage of encfs, and so should be ignored as being cruft.

However I don't store .encfs6.xml in the file system, and don't recommend storing it with the data.  Instead I store it separately in a key storage system I use.   While in only contains 'public' parts of the encryption. That does not mean you should make it 'public'.  Why give a cracker information for free!

Actually I lie... I do store a .encfs6.xml in some encfs file systems.  A fake one with a fake password that decrypts fake data :-)   Actually I even create file systems that look like EncFS encrypted file systems, but actually aren't.  That is encrypted data with filenames that look like EncFS but isn't.  You can also 'interleave' two or more EncFS file systems on the one data storage system.  It is doubtful you will get a filename clash.
