### ISSUE TITLE
small last block insecure

### ISSUE THREAD

**Issue by haffs** [vgough/encfs#103]
If the size of the last block doesn't exceed the block size of the
cipher used, this last block is vulnerable against key reuse attack
and bit flipping attack, at least when standard configuration is used.
The attacker needs to see two snapshots of the last block, who are
equal in length, and can get the XOR of the plaintexts. (For a last
block with a single byte the vulnerability was noticed back in 2010:
http://archives.neohapsis.com/archives/fulldisclosure/2010-08/0316.html)

Let c1 and c2 be the two snapshots of the last block:

c1: XOR(S(F(XOR(S(p1),E1))),E2)
c2: XOR(S(F(XOR(S(p2),E1))),E2)

Because of

P: XOR(XOR(A,K),XOR(B,K)) = XOR(A,B)

we get from the XOR of the two ciphertexts

1: XOR(XOR(S(F(XOR(S(p1),E1))),E2),XOR(S(F(XOR(S(p2),E1))),E2))		[XOR(c1,c2)]

the XOR of the plaintexts:

2: XOR(S(F(XOR(S(p1),E1))),S(F(XOR(S(p2),E1))))		[P,1]
3: XOR(F(XOR(S(p1),E1)),F(XOR(S(p2),E1)))		[unshuffle]
4: XOR(XOR(S(p1),E1),XOR(S(p2),E1))		[flip]
5: XOR(S(p1),S(p2))		[P,4]
6: XOR(p1,p2)		[unshuffle]

I know the plan is to remove stream encryption of the last file block.
Until then standard configuration in version 1.x probably shouldn't be
offered as before.

**Comment by rfjakob** [comment]
Thanks for hte detailed analysis. This issue is already tracked here: https://github.com/vgough/encfs/issues/9
