### ISSUE TITLE
Build issues with automake build infrastructure

### ISSUE THREAD

**Issue by prashantpandey** [vgough/encfs#104]
Hi,
I have been developing on top of EncFS. I started working from this commit "08e918f8ff13335435ae2469dca49de4d8924f3a" which has automake/autoconf build infrastructure.
It used to build fine, but suddenly I am getting a weird issue during configure:

./configure: line 18903: AX_CXX_COMPILE_STDCXX_11: command not found
./configure: line 18905: syntax error near unexpected token `fuse.h,'
./configure: line 18905: `AX_EXT_HAVE_HEADER(fuse.h, /usr/include/fuse /usr/local/include/fuse \'

I have all the latest tools installed. automake version is 1.14 and autocong version is 2.69.

**Comment by prashantpandey** [comment]
I got rid of the "AX_CXX_COMPILE_STDCXX_11" issue by installing the macro explicitly in the "/usr/share/aclocal".
But the other two issues, basically the syntax error still persists. Any help is greatly appreciated..

**Comment by vgough** [comment]
If syncing and using cmake is not an option, then you are now the proud owner of an automake system.  

I would try removing any generated automake files and regenerate them using your version of the automake toolchain.

**Comment by prashantpandey** [comment]
Hey I got hold of the issue. Its basically was occurring because a macro was missing. I don't know if it was the issue with underlying tool chain or during the "autoreconf". I basically downloaded the "ax_ext_have_header.m4" copied it in the "~/encfs/m4" folder and it worked.
