### ISSUE TITLE
Encrypt/Decrypt paths or filenames

### ISSUE THREAD

**Issue by Rudde** [vgough/encfs#111]
Hello!

I have EncFS on a Read Only cloud filesystem and I need to use a different tool to administrate the files out over reading them. So I am wondering if there is any way of finding the "encrypted" path of my files from the decrypted name? 

Example:

Decrypted path:

~/decrypted/directory/file.ext

and this is all the information I have I would like to know if there is a way to find the encrypted path (with the proper passphrase of course) 

~/encrypted/jkndjkhsnkldhs/bkjdbjkdbhdvsbuio

**Comment by RogerThiede** [comment]
See latest of [encfsctl.pod](https://github.com/vgough/encfs/blob/master/encfs/encfsctl.pod)

encfsctl encode [--extpass=prog] rootdir [plaintext name ...]
* encode
Allows you to specify a filename on the command line, and displays its encoded version. This is useful if e.g. you are taking a backup of an encrypted directory and would like to exclude some files.

**Comment by Rudde** [comment]
Thanks RogerThiede, did not find that, but I found it in the manual but it was certainly there when I knew what to look for.
