### ISSUE TITLE
All users can access mounted volumes in Windows

### ISSUE THREAD

**Issue by kmray** [vgough/encfs#114]
If a volume is mounted in Windows by one user and a 2nd user logs in, the 2nd user will be able to access the mounted volume. I have tried mounting as both local and network drive and the 2nd user was able to access the unencrypted files. The default should be that mounted volumes are only accessible by the user who mounted them but an option to mount for all users may be useful.

**Comment by rfjakob** [comment]
Wow, you run encfs on windows? How?

**Comment by kmray** [comment]
Sorry, submitted to wrong project. This was meant for EncFSMP

**Comment by rfjakob** [comment]
Oh, nice, I wasn't aware of encfsmp.

But I'm afraid that I can not help with that.

Just reading the faq at http://encfsmp.sourceforge.net/faq.html I noticed
that having "very limited access control" is mentioned as a known
limitation.
