### ISSUE TITLE
Decrypted folder is empty

### ISSUE THREAD

**Issue by tsjfd** [vgough/encfs#115]
I have found a one year backup on my remote machine which I have tried to mount. The encrypted encfs folder has a size of ~10 GB and I know the password. The problem is that after encfs ~/.remote-backup/ ~/backup -vf the backup folder is empty. I am pretty sure that I have never manipulate .encfs6.xml or any other file in ~/.remote-backup/.

**Comment by rfjakob** [comment]
What is the output from encfs?

**Comment by vgough** [comment]
Closing for lack of information.
