### ISSUE TITLE
OS El Capitan

### ISSUE THREAD

**Issue by axet** [vgough/encfs#116]
Unable to delete files on encrypted folder using Finger. Works well with rm -rf.

The operation can’t be completed because one or more required items can’t be found.
(Error code -43)

**Comment by vgough** [comment]
Which version of OSXFuse do you have installed?

**Comment by axet** [comment]
encfs @1.8.1  macports

**Comment by vgough** [comment]
Macports appears to use OSXFuse 2.8.0.  I suspect that you need to upgrade OSXFuse to the latest version (2.8.1 as of this writing).  The 2.8.1 release fixes a delete issue on OS X 10.11, which sounds like what you're reporting. 

    Improved compatibility with Finder on OS X 10.11. Starting with OS X 10.11 
    DesktopServicesHelper, which is running as root, calls stat(2) on behalf of Finder
    when trying to delete a directory. Blocking this request would result in Finder 
    aborting the delete process.

**Comment by cometta** [comment]
i upgraded oxxfuse to 2.8.1, but still unable to delete the file from the mounted drive. Any workaround?

**Comment by W4RH4WK** [comment]
Similar issue here, while using `2.8.2`.

**Comment by axet** [comment]
Reboot your machine. Works for me with 2.8.2

**Comment by W4RH4WK** [comment]
Sorry for the slow answer, rebooting seemed to solve my problem. Thanks!
