### ISSUE TITLE
EncFS over SMB: Operation not supported

### ISSUE THREAD

**Issue by fnkr** [vgough/encfs#119]
I can't get EncFS working together with an SMB mount. I was able to create a new EncFS volume, mount it but when I copy a file into it I get the error "Operation not supported" and I have a new empty(!) file in the EncFS directory ("rootDir").

```
$ ls -al
total 2
drwx------. 1 fnkr fnkr    0 14. Okt 07:53 .
drwx------. 1 fnkr fnkr    0 14. Okt 07:10 ..
-rwx------. 1 fnkr fnkr 1092 14. Okt 07:11 .encfs6.xml
-rwx------. 1 fnkr fnkr    0 14. Okt 07:37 Oo45QTrhdAwxhVS80eq,WnzP
```

```
encfs -f "/run/user/1000/gvfs/smb-share:server=nas,share=data,user=data/data" "$HOME/encfs-mount"
```

Log: https://gist.github.com/fnkr/c613b577d1c65bf7ecf8

**Comment by rfjakob** [comment]
I can reproduce this. This seems to be a limitation of gvfs, it returns "Operation not supported" when EncFS tries to open the file in read/write mode. However, I think this `/run/user/1000/gvfs` thing is more meant as a convenience than a serious filesystem.

The "serious filesystem" smb mount is `mount -t cifs`. Please mount the smb share like this:

    sudo mount -t cifs -o user=data,password=data //nas/data /mnt/nas-data

EncFS works fine on top of cifs.

**Comment by Aikhjarto** [comment]
@fnkr Which OS on the client, which version of the SMB-protocol (not version of the samba package) and which kernel versions do you use. There are known bugs for e.g. openSUSE clients with kernel less than 4.2 that cannot write properly on a SMB-Server using SMB Protocol 2 or higher. Furthermore  gvfs-mount does IMHO only support protocol 1. Maybe do some write test on the mounted samba filesystems without encfs to ensure your samba setup does work.

**Comment by rfjakob** [comment]
gvfs-smb does not allow opening an file in read/write mode, I tried it out
by opening a file on gvfs-smb in a hex editor. It errors out with
"operation not supported".

**Comment by fnkr** [comment]
Ok, gvfs is probably the problem. I'm not that satisfied with cifs as solution because it requires root privileges and I would like to stay in userspace while doing usal work (like editing word documents or  mounting my EncFS container), but it's not an EncFS-bug/problem so I will try cifs this evening and close this issue if it works.

**Comment by rfjakob** [comment]
True, that complicates things a bit. However, if you can add an entry to `/etc/fstab` with the `user` option, you can mount and unmount it without requiring sudo.

**Comment by Aikhjarto** [comment]
When root privileges of mount.cifs are a problem, you can also mount as user using pam_mount to automount a samba-share when the users logs in.

**Comment by fnkr** [comment]
@rfjakob I tired it now and it worked, thanks for helping!
