### ISSUE TITLE
Question about Filesystem Block Size

### ISSUE THREAD

**Issue by fnkr** [vgough/encfs#120]
If my EncFS container does not contain files with less than 100 KB of size, and I allways want to read the entire file (or at least more than 100 KB at a time), would it, theoretically, improve the performance if I increase the filesystem block size to 100 KB?

**Comment by RogerThiede** [comment]
*Not a full answer:*

Is there any processing or parallelism that can be performed on less than 100KB of data even though the final intent would be to read all 100KB?  While Filesystem Block Size refers to the size of a block of stored data, *for a majority of filesystems* doesn't it also imply the amount of data to read and block until completed?

**Comment by fnkr** [comment]
@RogerThiede Additionally, I noticed that EncFS does not support more then 4096 B as filesystem block size anyway (maybe because of what you said?), so I'm closing this issue.

**Comment by rfjakob** [comment]
I would not expect a performance benefit from choosing a bigger block size.
