### ISSUE TITLE
Not able to run TorBrowser Bundle from encfs mounted drive on Windows

### ISSUE THREAD

**Issue by clustor** [vgough/encfs#123]
I installed Tor Browser Bundle from https://www.torproject.org/download/download-easy.html.en to an encfw mounted volume. 

When a run the exe I get the following error.

"The procedure entry point EVP_aes_128_ctr could not be located in the dynamic link library LIBEAY32.dll"

This seems like some type of conflict with the encryption library as there is no error if Tor Browser is installed to C:\ drive.

**Comment by rfjakob** [comment]
I am sorry but we don't have expertise with running encfs on windows. You are probable using EncFSMP, maybe you can file a ticket there? http://encfsmp.sourceforge.net/
