### ISSUE TITLE
memory use issue

### ISSUE THREAD

**Issue by elmarr** [vgough/encfs#124]
Linux Mint Cinnamon: whenever I open encrypted folders, the reported memory use by cinnamon increases. It grows from around 135MB to 2.2GB. Not only does the memory use increase, but the system slows down.
When I untick the folder in encfs, the memory is not released.
I need to shut down and reboot.

**Comment by rfjakob** [comment]
This kinda sounds like a bug in Cinnamon. I don't think this can be fixed from encfs.

**Comment by vgough** [comment]
This sounds a lot like Linux using the memory for caching purposes.  I'd check the output of the "free" command before and after, to see if the memory is really in use.
