### ISSUE TITLE
wine apps dont work with encfs

### ISSUE THREAD

**Issue by jsalatiel** [vgough/encfs#126]
Apparently wine apps are not able to work when the home is encrypted using encfs.
I tried wine / crossover / teamviewer, none of them work correctly on my encrypted home.
Windows applications installed by wine or crossover wont start, teamviewer wont start ...
Is there any workaround ?

Version 6 configuration; created by EncFS 1.7.4 (revision 20100713)
Filesystem cipher: "ssl/aes", version 3:0:0 (using 3:0:2)
Filename encoding: "nameio/stream", version 2:1:0 (using 2:1:2)
Key Size: 256 bits
Using PBKDF2, with 267800 iterations
Salt Size: 160 bits
Block Size: 1024 bytes
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File holes passed through to ciphertext.

**Comment by rfjakob** [comment]
What error messages do you get when you start teamviewer from a terminal?

**Comment by jsalatiel** [comment]
Init...
Checking setup...
ln: failed to create symbolic link ‘/home/myself/.config/teamviewer10/dosdevices/z:’: No such file or directory
err:process:init_windows_dirs directory L"C:\\windows" could not be created, error 2
err:process:init_windows_dirs directory L"C:\\windows\\system32" could not be created, error 3
err:process:init_windows_dirs directory L"C:\\windows" could not be created, error 2
err:process:init_windows_dirs directory L"C:\\windows\\system32" could not be created, error 3
err:wineboot:main Cannot set the dir to L"C:\\windows" (2)
err:process:init_windows_dirs directory L"C:\\windows" could not be created, error 2
err:process:init_windows_dirs directory L"C:\\windows\\system32" could not be created, error 3
err:process:init_windows_dirs directory L"C:\\windows" could not be created, error 2
err:process:init_windows_dirs directory L"C:\\windows\\system32" could not be created, error 3
err:setupapi:SetupDefaultQueueCallbackW copy error 2 L"\\\\?\\unix\\opt\\teamviewer\\tv_bin\\wine\\share\\wine\\l_intl.nls" -> L"C:\\windows\\system32\\l_intl.nls"
err:setupapi:SetupDefaultQueueCallbackW copy error 3 L"\\\\?\\unix\\opt\\teamviewer\\tv_bin\\wine\\share\\wine\\l_intl.nls" -> L"C:\\windows\\system32\\l_intl.nls"
err:setupapi:create_dest_file failed to create L"C:\\windows\\rundll.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\twain.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\twain_32.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\winhelp.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\winhlp32.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\command\\start.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system\\ddeml.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system\\mmsystem.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\ddhelp.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\dosx.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\dsound.vxd" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\winhlp32.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\explorer.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\hh.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\notepad.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\regedit.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\explorer.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\iexplore.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\notepad.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\winetest.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\drivers\\mountmgr.sys" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\aspnet_regiis.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\ngen.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\fusion.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\regsvcs.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\regasm.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\servicemodelreg.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\presentationfontcache.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\msxml.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\msxml2.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\msxml3.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\msxml4.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\msxml6.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\shdocvw.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\gecko\\plugin\\npmshtml.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\wbem\\mofcomp.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\wbem\\wbemprox.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\wbem\\wmic.exe" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\wbem\\wmiutils.dll" (error=3)
err:shell:SHGetFolderPathAndSubDirW Failed to create directory L"C:\\Program Files".
fixme:setupapi:get_csidl_dir CSIDL 26 not found
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\unknown\\Internet Explorer\\iexplore.exe" (error=3)
err:shell:SHGetFolderPathAndSubDirW Failed to create directory L"C:\\Program Files\\Common Files".
fixme:setupapi:get_csidl_dir CSIDL 2b not found
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\unknown\\System\\OLE DB\\oledb32.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\unknown\\System\\OLE DB\\msdaps.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\rsaenh.dll" (error=3)
err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\rsabase.dll" (error=3)
err:shell:SHGetFolderPathAndSubDirW Failed to create directory L"C:\\users\\myself\\My Documents".
err:shell:SHGetFolderPathAndSubDirW Failed to create directory L"C:\\users\\myself\\Start Menu\\Programs".
err:ole:CoGetClassObject class {4315d437-5b8c-11d0-bd3b-00a0c911ce86} not registered
err:ole:CoGetClassObject class {4315d437-5b8c-11d0-bd3b-00a0c911ce86} not registered
err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x3
wine: configuration in '/home/myself/.config/teamviewer10' has been updated.
regedit: File not found "/opt/teamviewer/tv_bin/script/fontsmooth_rgb.reg" (2)


if i create a directory outside the encfs , and symlink ~/.config/teamviewer10 to it , teamviewer starts just fine. The same applies to the .wine directory and .cxoffice directory.

**Comment by fulldecent** [comment]
@jsalatiel Could you please confirm there is no error when using another, trivial Fuse filesystem, for example ROFS.

**Comment by jsalatiel** [comment]
ROFS wont work because it is a readonly filesystem.
Could you lead me to another trivial fuse fs ?

**Comment by fulldecent** [comment]
Here is the trivial file system:

https://github.com/jrk/passfs

**Comment by jsalatiel** [comment]
Ok, tried with passfs and it works just fine.

**Comment by fulldecent** [comment]
Awesome, thank you for testing, this is helpful

**Comment by jsalatiel** [comment]
sorry to bother, but any news on this ?

**Comment by benrubson** [comment]
@jsalatiel, do you still encounter this issue with EncFS master branch ?
The first error of your log is a symlink error, some symlink bugs have been corrected recently.
Thx 👍

**Comment by jsalatiel** [comment]
Hi @benrubson , i have stopped using encfs because of this problem. Now i am using gocryptfs.

**Comment by benrubson** [comment]
Would have been interested if you could have tested EncFS master branch (giving us `encfs -v` and teamviewer logs) :)
Anyway, thank you for your feedback 👍

**Comment by samrocketman** [comment]
If anybody could try running a simple Windows app in an EncFS filesystem (master branch EncFS) to confirm this is still an issue that would be great.

For example, [`EKeyfinder_v0.1beta7_win32.zip` (hyper link)](https://github.com/samrocketman/ekeyfinder/releases) contains a simple Windows program which can be used as a test to run in WINE on EncFS.  I've used it in WINE successfully without EncFS so it's a decent litmus test I think.

**Comment by benrubson** [comment]
It works, just tested with full .wine directory in EncFS (master branch) in paranoia mode, under Debian 9.

![wine](https://user-images.githubusercontent.com/6764151/29748451-827bbe26-8b17-11e7-9620-44d314839c35.png)

**Comment by samrocketman** [comment]
Ok seems the issue is resolved.  Thanks for reporting back.
