### ISSUE TITLE
Input/output error filesystem corruption and recovering

### ISSUE THREAD

**Issue by Sylvain303** [vgough/encfs#129]
Hi,

I'm using an encfs over a cloud stored repository, mainly for testing. The data stored in the encrypted folders are mainly, if not only, txt content and folder tree. Precisely it's a Zim wiki notebook file structure. 

I faced a read error on a file. Some file, not all, from the mounted encfs, are giving empty content and a read error. After reading some links on the Net I finally found the --forcedecode parameter in #94. Which worked! The text file is partially corrupted but usable.

My question are:

1. How do I identify corrupted files in the tree? 

I tried encfsctl showcruft but it found cloud remote collisions file also stored in the crypted tree. And if I did it correctly, it didn't found the corrupted file I was working on.

I did:

~~~
cd crypt/
encfsctl encode . clear/path/to/some.txt
~~~

got some crypted_filename

~~~
encfsctl cat . crypted_filename
~~~

result:

~~~
07:53:38 (MACFileIO.cpp:217) MAC comparison failure in block 0
terminate called after throwing an instance of 'rlog::Error'
  what():  Assert failure at MACFileIO.cpp:222 -- MAC comparison failure, refusing to read
Aborted (core dumped)
~~~

So I'm not sure it's the way of identify a single file. I did not manage to show a single file that way.

2. Is there a doc about managing and may be recovering some corrupted file anywhere?
3. If not, what is the commands needed to find and show a single file content?

Version:

~~~
Version 6 configuration; created by EncFS 1.7.4 (revision 20100713)
Filesystem cipher: "ssl/aes", version 3:0:0 (using 3:0:2)
Filename encoding: "nameio/block", version 3:0:0 (using 3:0:1)
Key Size: 256 bits
Using PBKDF2, with 186572 iterations
Salt Size: 160 bits
Block Size: 1024 bytes, including 8 byte MAC header
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File data IV is chained to filename IV.
File holes passed through to ciphertext.
~~~

I suspect the corruption come from disk error or something related to system error during write on the single file.

Regards,
Sylvain.

**Comment by rfjakob** [comment]
For question (1): You have to read every file and see if they return IO errors.
So on the mounted encfs,

    find . -type f -exec cat {} \; > /dev/null

This will return no output but errors.

**Comment by Sylvain303** [comment]
OK thanks in deed it works. This Zim's notebook has a .git folder, to skip it the find command becomes:

~~~
cd decrypted_mount
find . -path ./path/to/folder/.git -prune -o -type f -exec head -c 32 {} \; > /dev/null
~~~

Which is really faster.
In both case, only one filename is giving an error. Which seems reasonable because I worked only on the corrupted one.

To be continued.

**Comment by rfjakob** [comment]
I guess this is solved. Closing the ticket.
