### ISSUE TITLE
Major problem with Encfs no longer working: Symbol not found

### ISSUE THREAD

**Issue by b-u-g-s** [vgough/encfs#132]
Hi,

I shutdown my laptop last night and rebooted this morning, now encfs fails to start with the following error:
dyld: Symbol not found: __ZN5boost7archive17xml_iarchive_implINS0_12xml_iarchiveEE13load_overrideERNS0_15class_name_typeEi
  Referenced from: /usr/local/Cellar/encfs/1.8.1/lib/libencfs.6.dylib
  Expected in: /usr/local/lib/libboost_serialization-mt.dylib
 in /usr/local/Cellar/encfs/1.8.1/lib/libencfs.6.dylib

I am running El Capitan, fully updated, I have done a brew update and upgrade.

Could it be that there has been a recent MAC OS X update that affected encfs? and that by rebooting my laptop got applied?

When upgrading brew I noticed the following text:
Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

Not sure if encfs could be affected by that.

Any help is much appreciated!
Bugs.

**Comment by akpw** [comment]
Given you have already done your brew update + upgrade, simply reinstalling encfs should fix it:
 $ brew uninstall encfs
 $ brew install encfs

or:
 $ brew reinstall encfs

**Comment by b-u-g-s** [comment]
Thanks! it worked!
Any idea what was wrong and why it needed to be recompiled/reinstalled?

B.

**Comment by vgough** [comment]
The missing symbol was a Boost library.  One way that could happen is if boost was upgraded without rebuilding any programs using it (such as encfs).
