### ISSUE TITLE
Decrypted folder is empty, .encfs6.xml was changed

### ISSUE THREAD

**Issue by bitwombat** [vgough/encfs#133]
Long time happy encfs user.  

Today, something weird happened - an attempt to mount the fs resulted in an empty decrypted folder:

    encfs /data/info.encfs /info

No error message.  Luckily, I had a backup .encfs6.xml.  Copying that over, remounting, and everything works.

I've used encfs for years.  Nothing like this has happened before.

The two are very different.  They are attached, with keys and salt removed.  Both had changed (don't know if that's normal).  You can see the keysize and blocksize changed.  Is that normal, or a known bug?

This is on Ubuntu 14.04 LTS, which is using 1.7.4.  I know that's ancient but I'm wondering if this is a known bug, indicative of a hardware failure, or something I did.

[encfs_files.zip](https://github.com/vgough/encfs/files/71379/encfs_files.zip)

**Comment by rfjakob** [comment]
No there are no known bugs related to the handling of `.encfs6.xml`. The only time that file is changed is when changing the password. Did this happen immediately after chaning the password?

**Comment by bitwombat** [comment]
No, I've never changed the password.
6 months later, it hasn't recurred, so call it an alpha particle maybe :)

**Comment by rsommer** [comment]
Even if this is close - i'm getting the exact same behaviour, the encfs6.xml file keeps changing on two different servers and i have no clue whats going on.
