### ISSUE TITLE
Build broken on cent7

### ISSUE THREAD

**Issue by carsonfenimore** [vgough/encfs#134]
When I try to compile on cent7 I see the following:

[ 43%] In file included from /usr/include/rlog/rlog.h:206:0,
                 from /home/carson/encryptedbackup/encfs-master/encfs/encfs.h:25,
                 from /home/carson/encryptedbackup/encfs-master/encfs/FSConfig.h:26,
                 from /home/carson/encryptedbackup/encfs-master/encfs/BlockFileIO.h:26,
                 from /home/carson/encryptedbackup/encfs-master/encfs/BlockFileIO.cpp:21:
/home/carson/encryptedbackup/encfs-master/encfs/BlockFileIO.cpp: In member function ‘void BlockFileIO::padFile(off_t, off_t, bool)’:
/home/carson/encryptedbackup/encfs-master/encfs/BlockFileIO.cpp:318:32: error: expected ‘)’ before ‘PRIi64’
       rDebug("padding block %" PRIi64, oldLastBlock);

I found the following fixes the build:

--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -20,7 +20,7 @@ if (${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} GREATER 3.0)
 else ()
   if (CMAKE_COMPILER_IS_GNUCXX)
     message ("Assuming that GNU CXX uses -std=c++11 flag for C++11 compatibility.")
-    list(APPEND CMAKE_CXX_FLAGS "-std=c++11")
+    list(APPEND CMAKE_CXX_FLAGS "-std=c++11 -D __STDC_FORMAT_MACROS")
   else()
     message ("No CMAKE C++11 check. If the build breaks, you're on your own.")
   endif()

**Comment by rmorin** [comment]
this is also necessary on cent6

**Comment by vgough** [comment]
Thanks for the report.  The need for printf macros should be gone now on master, as it no longer uses printf style logging functions.
