### ISSUE TITLE
cross-compiling possible for ARM?

### ISSUE THREAD

**Issue by cr8r** [vgough/encfs#137]
Short version:

Is it possible to cross compile encfs for ARM target on an X86 build system?

Long version:

Been working on cross compiling encfs 1.7.4 for the QNAP NAS using QNAP's ARM toolchain. Build system is Lubuntu x86 and target is ARM Marvell. So far I have built libiconv,  rlog,  boost, and fuse. However when running configure for encfs, I get this message:
...
checking fuse.h usability... yes
checking fuse.h presence... yes
checking for fuse.h... yes
checking for fuse_new in -lfuse_ino64... no
checking for fuse_new in -lfuse... yes
checking For supported FUSE API version... configure: error: in `/opt/cross-project/arm/marvell/build/encfs-1.7.4':
configure: error: cannot run test program while cross compiling
See `config.log' for more details

Config.log shows the same information:

configure:17665: checking For supported FUSE API version
configure:17668: error: in `/opt/cross-project/arm/marvell/build/encfs-1.7.4':
configure:17670: error: cannot run test program while cross compiling
See `config.log' for more details

Is there a way around this check, or will encfs have to be compiled on an ARM build system?

Thanks for any suggestions!

**Comment by cr8r** [comment]
Bump :)

**Comment by rfjakob** [comment]
Hi! You are building a very old version of encfs. The build system was
changed to cmake in the meantime, so any errors you are getting are
probably no longer relevant for encfs master. You will get others, though ;)

Please try building the latest master.
