### ISSUE TITLE
Concurrent mounts safe?

### ISSUE THREAD

**Issue by EulersSerum** [vgough/encfs#138]
Is it possible/safe to mount an encfs folder stored on a server concurrently by multiple clients on different computers?

**Comment by fulldecent** [comment]
Yes. There is no additional synchronization required for encfs to operate properly.

That is assuming that without encfs you are still able to open the files on multiple clients.

**Comment by vgough** [comment]
Note that there is caching of open files (particularly the last block of an open file, to speed appends).  Otherwise I believe that it should work as well as sharing the folder without encfs.
