### ISSUE TITLE
Files wrongly considered “not found” in encfs volume on MacOS

### ISSUE THREAD

**Issue by programmdesign** [vgough/encfs#145]
Note: Previously posted on [AskDifferent](http://apple.stackexchange.com/questions/228024/files-wrongly-considered-not-found-in-encfs-volume). So far, without response.

I'm using encfs 1.8.1 (installed via homebrew) on OSX 10.11.2 and Fuse 2.8.3. IIRC after upgrading to OS X I have the issue that I can open certain files that are in the folder that I mounted with encfs.
## The problem
- Finder shows me a file without file type (Note the "--" where you'd usually find the file type)

[![](http://i.stack.imgur.com/lZsfI.png)](http://i.stack.imgur.com/lZsfI.png)
- If I try to open the file, I get a message saying: '“file.txt” can’t be found.'
- The same happens, if i go to the terminal an run ...
  
  ```
  open file.txt
  ```
- However, I can open the file and see its content in the terminal if I run ...
  
  ```
  vi file.txt
  ```
- Also, if I make a copy of the file in the same folder or if I copy it to a folder outside of encfs, I can open it both in Finder and in via the open command in the terminal.
## Steps I've taken to fix it:
1. Removed com.apple.quarantine attribute -- still couldn't open the file
   
   ```
   xattr -r -d com.apple.quarantine /path/to/my/encfs/folder
   ```
2. Compared extra attributes of the copy and the original file -- they were identical
   
   ```
   xattr -l file.txt
   com.apple.FinderInfo:
   00000000  57 58 42 4E 4D 53 57 44 00 00 00 00 00 00 00 00  |WXBNMSWD........|
   00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
   00000020
   com.dropbox.attributes:
   00000000  78 9C AB 56 4A 29 CA 2F 48 CA AF 88 4F CB CC 49  |x..VJ)./H...O..I|
   00000010  CD 4C 89 CF C9 4F 4E CC 51 B2 52 A8 56 CA 4D 4C  |.L...ON.Q.R.V.ML|
   00000020  CE C8 CC 03 89 25 96 94 14 81 85 52 12 4B 12 81  |.....%.....R.K..|
   00000030  0C A5 6C 67 F7 4C AF F0 E2 CC C4 52 F3 50 43 5F  |..lg.L.....R.PC_|
   00000040  FD 30 8B 14 F7 20 A7 74 5B 5B A5 DA DA 5A 00 C4  |.0... .t[[...Z..|
   00000050  D4 1C 29                                         |..)|
   00000053
   xattr -l copy.txt
   com.apple.FinderInfo:
   00000000  57 58 42 4E 4D 53 57 44 00 00 00 00 00 00 00 00  |WXBNMSWD........|
   00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
   00000020
   com.dropbox.attributes:
   00000000  78 9C AB 56 4A 29 CA 2F 48 CA AF 88 4F CB CC 49  |x..VJ)./H...O..I|
   00000010  CD 4C 89 CF C9 4F 4E CC 51 B2 52 A8 56 CA 4D 4C  |.L...ON.Q.R.V.ML|
   00000020  CE C8 CC 03 89 25 96 94 14 81 85 52 12 4B 12 81  |.....%.....R.K..|
   00000030  0C A5 6C 67 F7 4C AF F0 E2 CC C4 52 F3 50 43 5F  |..lg.L.....R.PC_|
   00000040  FD 30 8B 14 F7 20 A7 74 5B 5B A5 DA DA 5A 00 C4  |.0... .t[[...Z..|
   00000050  D4 1C 29                                         |..)|
   00000053
   ```
3. Compared and aligned access rights attributes of the copy and the original file -- still couldn't open the file
4. Removed extra attributes -- still couldn't open the file
   
   ```
    xattr -r -d com.dropbox.attributes /path/to/my/encfs/folder/file.txt
    xattr -r -d com.apple.FinderInfo /path/to/my/encfs/folder/file.txt
   ```

Does anyone have an idea, how to fix this? Thanks!

**Comment by pasnox** [comment]
Same here, lots of can't read / write files using EncFS on OSX.
That's a bit annoying because I do build my C++ projects in the EncFS partition and that make my builds failing randomly.
The EncFS partition is mounted as a local disk (I do want to see real files / folders permissions).
Installed osxfuse and encfs from brew on el Capitan.

**Comment by pasnox** [comment]
Looks like all those errors vanished while upgrading osxfuse to latest beta (3.2.x)

**Comment by jetwhiz** [comment]
@pasnox Could you test out this patch to see if it fixes your problems? 

https://github.com/jetwhiz/encfs4win/commit/50abe2fc7d12117d5077102deea1f18ce6583857

I think using base32 for case-insensitive systems is the intended implementation, instead of using base64.  They might have gotten mixed up when that feature was added.

**Comment by pasnox** [comment]
You mean the actual partition will no longer working ?
That would a bit annoying for me - i have many gigas of data to move on external disk etc, will consume lots of time :/

**Comment by jetwhiz** [comment]
Did you choose "Block" or "Block32" encoding when you set up your encrypted partition?

**Comment by pasnox** [comment]
I did use default parameters - only set the password.

**Comment by jetwhiz** [comment]
I think that explains the issues that you're seeing.  For case-insensitive systems (like Windows and Mac), you should use the Block32 filename encoding setting.  The current implementation is mislabeled, saying that Block32 is for case-*sensitive* systems.

**Comment by pasnox** [comment]
Hm, would that mean i need to extract all my data, and reimport them all after having deleted / recreated the encfs ?

**Comment by jetwhiz** [comment]
Unfortunately the only thing I can think of is moving all of your data over to an encfs filesystem with Block32 filename encoding set.  

The only alternative would be to make a tool that will rename all of the files in your encrypted folder to convert them from base64 to base32, and then update your config to use block32.  

Unless someone else can weigh in on some other options?  @vgough

**Comment by pasnox** [comment]
Hm... ok, I will think / test that!
thanks,

**Comment by sir-brickalot** [comment]
I have similar problems. Some files/folder are readable, others are not. Workaround: rsyncing them to a new folder resolves the problem.
Is there a tool to see which files are affected?
Does this affect interoperability with Win/Linux?

**Comment by jetwhiz** [comment]
@sir-brickalot - This will not affect interoperability between Windows and Linux.  Linux can work with both Block (base64) and Block32 (base32) filename encoding, while Windows/Mac can only effectively use Block32 (base32) filename encoding.

**Comment by vgough** [comment]
@jetwhiz  the "case sensitive" / "case insensitive" fix was purely a documentation issue within encfs.  The PR you pushed to encfs master fixed the text and made the naming consistent, but the behavior was correct:  https://github.com/vgough/encfs/commit/aa08c382d9c27fb00c23ab88a3b54f3c3e89f791

**Comment by jetwhiz** [comment]
@vgough  I think the problem these users are experiencing is because they either used the defaults (which was always base64 before), or the setup prompt told them to use base64 for case-insensitive systems (Win/Mac).  The only solution I can think of is for them is to create a new encfs container using Block32, and copy all of their files over to the new container.  You know much more about the system than I do, though -- do you know of a less-intensive option for them (maybe a way to rename all of the files to use Block32)?  

I realize that base64 encoding is more space-efficient than base32, but is there a reason encfs should still use base64 at all?  Maybe only provide base64 if the user explicitly opts-in to use it (and have base32 always be the default)?  I believe the issue we're going to see is that users might create a filesystem on Linux (using base64), and someday they (or someone else) might want to access it on a Win/Mac system (which will give them the problems we're seeing here).

**Comment by rfjakob** [comment]
The downside of base32 is that it limits the maximum filename length even more:
* base64: max 176 characters
* base32: max 144 characters

**Comment by vgough** [comment]
@jetwhiz  Parts of this puzzle don't fit with it being an encoding problem (for instance, the files can be opened in some programs but not others, and the files aren't missing, just wrongly typed).  It does sound like it could be an extended attribute issue.  I'd started working on a fix for that in #107 , but I'm not sure there's a way to incorporate that in a backward-compatible way.

**Comment by benrubson** [comment]
@programmdesign does EncFS master branch (or at least version 1.9.1) corrects your issue ?
Thank you 👍

**Comment by benrubson** [comment]
You may also consider this :
[Mac OS iconv setting](https://github.com/vgough/encfs/issues/316#issuecomment-304636726).

**Comment by benrubson** [comment]
To reporters having the issue, does last version of EncFS (or master branch) corrects your issue ? (some OS X fixes were made)

You may also consider this :
[Mac OS iconv setting](https://github.com/vgough/encfs/issues/316#issuecomment-304636726).

Please test both and report !

Thx 👍
