### ISSUE TITLE
Can't test within sandbox

### ISSUE THREAD

**Issue by ilovezfs** [vgough/encfs#151]
encfs doesn't require root to run but its behaviors prevent a sandboxed test for Homebrew:
```
==> Sandbox log
Mar 31 23:44:27 sandboxd[128]: com.apple.WebKit(4238) deny mach-lookup com.apple.dock.fullscreen
Mar 31 23:44:39 sandboxd[128]: com.apple.WebKit(4238) deny mach-lookup com.apple.dock.fullscreen
Mar 31 23:44:39 sandboxd[128]: encfs(50569) deny forbidden-exec-sugid
```
Any chance we could get an option added that would allow a sandboxed test?

The current test that fails when run within the sandbox does the following:
```
    if Pathname.new("/Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs").exist?
      (testpath/"print-password").write("#!/bin/sh\necho password")
      chmod 0755, testpath/"print-password"
      system "yes | #{bin}/encfs --standard --extpass=#{testpath}/print-password #{testpath}/a #{testpath}/b"
      system "umount", testpath/"b"
    end
```

**Comment by vgough** [comment]
@ilovezfs encfs doesn't have any special permissions (and no suid or sugid executable), so I suspect that this is a FUSE issue.  The FUSE mount helper load_osxfusefs is suid, so if you can't run FUSE programs in the sandbox then the current integration tests won't work.  You can run `checkops`, which runs some basic unit tests.

**Comment by ilovezfs** [comment]
@vgough Thank you for following up. Ah, OK. So testing anything FUSE related in the sandbox is probably going to be a problem. Thanks for the hint about checkops.
