### ISSUE TITLE
Filesystems created with `-S` can never be mounted again

### ISSUE THREAD

**Issue by kizzx2** [vgough/encfs#155]
```
$ encfs --version
encfs version 1.8.1

OS X El Capitan 10.11.4 Beta (15E39d)

$ brew info encfs
homebrew/fuse/encfs: stable 1.8.1, HEAD
```

Here is a small test script that demonstrates the issue:

```
#!/bin/sh -x

PASSWORD="password"

rm -rf test1
rm -rf test2

mkdir test1
mkdir test2

echo -n $PASSWORD | encfs -S $PWD/test1 $PWD/test2 -- -ovolname=test3
touch test2/xxx
sleep 5

umount test2

echo -n $PASSWORD | encfs -S $PWD/test1 $PWD/test2 -- -ovolname=test3
touch test2/xxx
sleep 5

umount test2
```

The above filesystem `test2` can never be mounted back, as it was created using the command `encfs -S`.

The above script works if I change the first `encfs` line to 

`echo -n $PASSWORD | encfs --standard -S $PWD/test1 $PWD/test2 -- -ovolname=test3`

The `.encfs6.xml` file generated using both approaches seem to be the same.

**Question 2**: I actually have another filesystem created using `encfs -S` and have put data into it. Is it possible to recover that data?

**Comment by rfjakob** [comment]
I cannot reproduce this, I get
```
Zero length password not allowed
Segmentation fault (core dumped)
```
and no file system is created. Can you copy-paste the whole output?

**Comment by kizzx2** [comment]
@rfjakob 

Ah, so I think the problem is that the prompt to create the new volume consumed the stdin. This is the output I got:

```
$ sh test-foo.sh
Creating new encrypted volume.
Please choose from one of the following options:
 enter "x" for expert configuration mode,
 enter "p" for pre-configured paranoia mode,
 anything else, or an empty line will select standard mode.
?>
Standard configuration selected.

Configuration finished.  The filesystem to be created has
the following properties:
Filesystem cipher: "ssl/aes", version 3:0:2
Filename encoding: "nameio/block", version 4:0:2
Key Size: 192 bits
Block Size: 1024 bytes
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File holes passed through to ciphertext.

Now you will need to enter a password for your filesystem.
You will need to remember this password, as there is absolutely
no recovery mechanism.  However, the password can be changed
later using encfsctl.

Error decoding volume key, password incorrect
umount: test2: not currently mounted
```

What's your `encfs` version?

**Comment by rfjakob** [comment]
I compiled 1.8.1 to match what you used.

Did your password contain newlines? Otherwise the actually used password is
probably empty, maybe you can mount the filesystem that way.

**Comment by kizzx2** [comment]
OK, found something weird.

Running the above script with `sh test-foo.sh` got my original input, but when I ran it with `bash test-foo.sh` I got the Segmentation fault...

Just reporting. Trying to figure out what that means.

**Comment by kizzx2** [comment]
If you are using `bash` or `dash`, you can try this script instead:

```
#!/bin/bash

PASSWORD="-n password"

rm -rf test1
rm -rf test2

mkdir test1
mkdir test2

echo "$PASSWORD" | encfs -S $PWD/test1 $PWD/test2 -- -ovolname=test3
touch test2/xxx
sleep 1

umount test2

echo "$PASSWORD" | encfs -S $PWD/test1 $PWD/test2 -- -ovolname=test3
touch test2/xxx
sleep 1

umount test2
```

**Comment by vgough** [comment]
Like @rfjakob  said, your echo was probably eaten by prompts before the password prompt if you didn't specify --standard.  If you are creating a new filesystem, there are prompts before the password prompt.  The man page recommends creating the filesystem normally and only using -S when mounting an existing filesystem, but I believe that --standard should work too when creating a filesystem.

**Comment by kizzx2** [comment]
@vgough 

Yes, the man page recommends that. Just a suggestion, if creating new filesystem with `-S` leads to such "unexpected" behaviors, how about the idea of it just erroring out instead?

On a separate note, any idea what the _actual_ password would have been in the above case? I've got a filesystem created in the above manner just wondering if it's possible to recover the data.

**Comment by rfjakob** [comment]
Probably "n password", because the first prompt consumed the "-"?

I don't know if we should error out here, scripts may actually want to
create a filesystem that way.

**Comment by rfjakob** [comment]
Btw @vgough , what do you think about releasing v1.9? Homebrew is stuck on
the old build system because the cmake stuff is not tagged yet.

**Comment by kizzx2** [comment]
@rfjakob FYI. Just tried `n password` ` password` ... up to empty string still no luck :cry: So it's quite unlikely that some scripts may actually want to create a filesystem that way given it's pretty unpredictable what the actual password may turn out to be

**Comment by vgough** [comment]
Using scripted input is a valid use case, but the onus is on the person automating this to ensure they are scripting it correctly.  

The easiest way to check your case is to add a line to print the password out in EncFSConfig::getUserKey and then run your creation script again to see what was used.  Based on the bash script you gave, I suspect the password is "rd".

**Comment by kizzx2** [comment]
@vgough Thanks very much for the pointer. Printing out the password at `EncFSConfig::getUserKey` solved it.

**Comment by openhoat** [comment]
I had the same problem, and found a way to deal with :
It seems that when using --extpass instead of -S it works
Example :
$ mkdir ~/encrypted ~/decrypted
$ echo "" | encfs --extpass='echo password' ~/encrypted ~/decrypted
# echo pipe trick is used to select standard configuration, the password is given with extpass
$ mount
$ echo "bar" > decrypted/foo.txt
$ fusermount -u ~/decrypted
# now let's mount again
$ encfs --extpass='echo password' ~/encrypted ~/decrypted
# no more configuration to choose so pipe is removed => no more error
$ mount
$ cat decrypted/foo.txt 
bar
# done!

my2cents
