### ISSUE TITLE
Data loss on OSX + OpenZFS

### ISSUE THREAD

**Issue by sir-brickalot** [vgough/encfs#157]
I was live at the scene when EncFS destroyed a bunch of files and I accidentally logged it.

Setup:
Hackintosh OSX 10.11.3
Drive: HDD > HFS+ journaled (encrypted) > OpenZFS 1.4.5 > FUSE for OSX 3.2.0 > EncFS 1.8.1_2 installed via brew.
Container: not sure about the settings. Is there a way to show properties of an encfs container?

There were problems with accessing files before so I was watching my encfs mount with `encfs -v -f` and because I was missing a file I checked against a backup and found that the file was present in unencrypted backup; even in another encrypted backup the file was still there.
I did a rsync dry-run on the whole mounted encfs volume and a bunch of files seem to be missing (not necessarily all of them because it was an old backup and I moved files around...
While dry-running there was a glitch and I saw files and folder vanishing in an open finder. I remounted the encfs volume and the files/folders were still gone.

Scary.

Tell me what else to provide for debugging.
[encfs-lostfiles1.log.zip](https://github.com/vgough/encfs/files/224413/encfs-lostfiles1.log.zip)

**Comment by vgough** [comment]
I don't see anything suspicious in the logs, and the behavior you describe has historically been tracked back to FUSE problems (particularly on OSX, where FUSE isn't as robust as on Linux).  I suspect that FUSE and OpenZFS may not be playing well together.  You might try using a simple loopback FUSE filesystem on top of OpenZFS to see if you get the same behavior (eg https://github.com/osxfuse/filesystems/blob/master/filesystems-c/loopback/loopback.c).

**Comment by vgough** [comment]
Closing for lack of information.
