### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by rdiez** [vgough/encfs#168]
Is there a mailing list for this project? I tried to send an e-mail to the encfs mailing list in sourceforge.net but it is still "waiting moderator approval".

If there is no mailing list, it would be nice to add to the readme file or documentation a note about it, in order to prevent other people from wasting time searching for one.

**Comment by rfjakob** [comment]
@vgough do you want to add me as a moderator so there is two people looking at the subscription requests?

**Comment by benrubson** [comment]
Let's close this for the moment, I made some documentation with #406.
