### ISSUE TITLE
Very bad performance copying to USB flash (over exFAT-fuse)

### ISSUE THREAD

**Issue by viric** [vgough/encfs#169]
I'm writing to a USB2 flash with encfs 1.8.1 in x86_64 GNU/Linux, and I notice this huge performance difference. I use bs=128K because it is what GNU "cp" uses:

```
#1. To the flash without encfs
$ dd if=/dev/zero of=prova bs=128K count=1024
134217728 bytes (134 MB, 128 MiB) copied, 0,286115 s, 469 MB/s

#2. Now to the encfs (default settings)
$ dd if=/dev/zero of=enc/prova bs=128K count=1024
134217728 bytes (134 MB, 128 MiB) copied, 51,4455 s, 2,6 MB/s

#3. Now I run the previous command again (the 128MB are preallocated)
$ dd if=/dev/zero of=enc/prova bs=128K count=1024
134217728 bytes (134 MB, 128 MiB) copied, 5,27361 s, 25,5 MB/s
```

So, it seems that copying to encfs disables some important caching.

And moreover, writing to new file has a big performance penalty. If I look at "iostat 2" numbers at this case (2.6MB/s writing), I see something like this:

```
Device:            tps    MB_read/s    MB_wrtn/s    MB_read    MB_wrtn
sdc             750,50         2,87         1,88          5          3
```

So, 750tps/s is a lot, but there are almost double reads than writes. I'm only running that dd. Where do the reads come from?

I infer that it's likely reading+updating file metadata (+128K in file size) at every write of 128K, an operation that would not happen when writing over an already allocated file that is not extended in length at every write.

It may be that this is unnoticeable in HDs or SSD drives, because they have hardware caching. USB flash usually does not have it:

```
[77593.968485] sd 8:0:0:0: [sdc] 122945536 512-byte logical blocks: (62.9 GB/58.6 GiB)
[77593.969752] sd 8:0:0:0: [sdc] Write Protect is off
[77593.969765] sd 8:0:0:0: [sdc] Mode Sense: 2b 00 00 08
[77593.970982] sd 8:0:0:0: [sdc] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
```

**Comment by viric** [comment]
Additional info: the encfs is mounted over an exFAT (another fuse fs).

I noticed that encs translates always the 128K writes to 1K writes, which may be specially painful over drives without write cache.

**Comment by viric** [comment]
For what I straced in encfs, it only does writes of 1K, so the huge amount of reads may come from exfat. That exfat "problem" seems to be unnoticeable without encfs because of some caching or so, that seems to be disabled somehow with encfs.

**Comment by viric** [comment]
I formatted the same USB with fat32, so it uses the Linux kernel driver, and I get proper caching and better performance over encfs:
```
$ dd if=/dev/zero of=prova bs=128K count=1024
134217728 bytes (134 MB, 128 MiB) copied, 3,71333 s, 36,1 MB/s
$ rm prova
$ dd if=/dev/zero of=prova bs=128K count=1024 conv=fdatasync
134217728 bytes (134 MB, 128 MiB) copied, 9,70621 s, 13,8 MB/s
```

**Comment by Adrianzo** [comment]
Please edit the issue title adding the exFAT fs specifity.

**Comment by samrocketman** [comment]
Closing this issue because it appears to be pretty old.  If you want this re-opened, please try a recent `master` branch copy of EncFS to confirm the problem still exists.

**Comment by pldubouilh** [comment]
For those bumping on the issue, moving to `exfat-nofuse` bumped the encfs perfs significantly - close to 10x in my case
