### ISSUE TITLE
Revert commit: "unordered_map value type ..."

### ISSUE THREAD

**Issue by smartbyte** [vgough/encfs#170]
The name of the commit is: unordered_map value type, is of std::pair<const Key, T>, hence a copy…

I am getting Segmentation faults with this patch!!! Please undo!!!!

My scenario is the following:
Cloud storage I access via sshfs. This storage is encrypted via encfs.
Then mount that storage to, let's say /mnt , and then I am accessing this structure with a folder scanning PHP website. -> I am getting a segmentation fault.

I tried the same with just doing a "cat * > /dev/null on a big folder.

On my machine I did a git pull, and replaced the encfs/Context.cpp file with the old version, and everything works fine (I tested that on 3 machines running Ubuntu 12.04 - 16.04 / gcc 4.9-Gcc5.2).

Every machine has the same issue, and I don't know why, but this commit did mess something up!

**Comment by ial0** [comment]
Sorry, I messed that patch up. It should have only remove the string assignment, it obviously still needs to remove the unreferenced files.

**Comment by smartbyte** [comment]
Awesome! When do you put it in the master branch?
