### ISSUE TITLE
Encrypt files with encfsctl (Reverse encfsctl cat)

### ISSUE THREAD

**Issue by RunasSudo** [vgough/encfs#173]
In the same way that `encfsctl cat` works as a standalone tool to directly decrypt a file without mounting the volume, it would be useful to have a command to directly encrypt a file without needing to mount the volume.

**Comment by Torsten85** [comment]
Would really like to see this implemented. 
Ultimately I would like to pipe a decrypted file to encfstl and redirect the encrypted version directly and upload script.

Or is there already a way to do this without mounting?

**Comment by benrubson** [comment]
Feature added by #483 👍
