### ISSUE TITLE
decrypt files in place

### ISSUE THREAD

**Issue by pyed** [vgough/encfs#175]
is it possible to decrypt a directory over itself, meaning that we don't need to mount and use something like `rsyc` to copy the decrypted data somewhere else, this will require double the space that my data needs and I can't afford that.

**Comment by rfjakob** [comment]
Use "mv" ;)

**Comment by pyed** [comment]
Would that be reliable ? Waiting for 'mv' to move 5+ TB of data without any output doesn't sound pleasent

**Comment by rfjakob** [comment]
You can use `mv -v` or a graphical file manager

**Comment by pyed** [comment]
I'll give that a shot tonight.

**Comment by pyed** [comment]
well, this doesn't seem to work, I used `mv -v` on a directory that has ~500Gb of encrypted data, and I can see with `df -h` command that every ~4 seconds the `Used` column is getting increased by 1Gb, my guess is that `mv` is holding the data until it finishes ? and then deletes it ?

**Comment by pyed** [comment]
at the end of the output of `mv -v` it started removing the files which explains everything 
```
removed 'tlac3'
removed 'facdf'
removed 'istac84'
removed 'lac88'
removed 'ue32'
removed 'ifennBälac'
removed 'wolassc'
removed directory 'Wha'
removed directory 'Main/'
```

so the issue stands.

**Comment by pyed** [comment]
if `mv` where to remove the file/directory right after copying it, it would work, because my HDD won't be holding the whole data doubled at one time, so running `mv` in a loop could work, something like
``` bash
$ cd ~/crypt
$ for f in *; do
    mv -v "$f" ~/uncrypted
done
```
now `mv` has to remove before it exists each time, it should work.

**Comment by rfjakob** [comment]
Ha, good point. If I remember correctly, mv removes the original files in directory increments. That is, it completely copies a directory, then removes the original. Unless you have most of the files in one single huge directory with no subdirectories, this may be good enough.

Then there is `rsync --remove-source-files` that *may* delete the original files immediately, but I have not tested it.

**Comment by rfjakob** [comment]
Actually, mv seems to be doing something else, it's not directory increments after all. "t" contains two subdirectories, "a" and "b", each containing a file "foo".
```
/tmp$ mv -v t /var/tmp
‘t’ -> ‘/var/tmp/t’
‘t/a’ -> ‘/var/tmp/t/a’
‘t/a/foo’ -> ‘/var/tmp/t/a/foo’
‘t/b’ -> ‘/var/tmp/t/b’
‘t/b/foo’ -> ‘/var/tmp/t/b/foo’
removed ‘t/b/foo’
removed directory: ‘t/b’
removed ‘t/a/foo’
removed directory: ‘t/a’
removed directory: ‘t’
```

**Comment by rfjakob** [comment]
Testing with `strace`, `rsync -r --remove-source-files` deletes the source files in small batches after the copy, so that could work. It does not delete the directories, so you'll be left with an empty dir structure that you have to delete manually.

**Comment by pyed** [comment]
I've a huge  amount of data to decrypt and I chose the `mv` command in a loop which seems to work just as expected, it moves the directory and all its contents recursively, when it is done it will remove that directory and the loop will move to the next directory ... etc

even tho I prefer `rsync` to do my copying, I was a bit suspicious that this `--remove-source-files` flag will mess things up.

**Comment by rfjakob** [comment]
Good to hear it worked in the end. Closing the ticket.
