### ISSUE TITLE
encfsctl cat outputs debug information to stdout

### ISSUE THREAD

**Issue by jetwhiz** [vgough/encfs#177]
As reported in encfs4win: https://github.com/jetwhiz/encfs4win/issues/42

`encfsctl -v cat [dir] [file] > out.tx` writes debugging output to stdout.  I think this issue was introduced with easylogging++, since it sends debug info to stdout and not stderr.

**Comment by RunasSudo** [comment]
The relevant easylogging++ issue is https://github.com/easylogging/easyloggingpp/issues/201. A workaround is described in that issue. Not sure how robust it is.

**Comment by jetwhiz** [comment]
Nice find ... this seems to be good enough in our case to fix this particular issue.  I guess we'd have to look into seeing if there are any side effects, though.
