### ISSUE TITLE
osxfuse is only located in /usr and /usr/local

### ISSUE THREAD

**Issue by gbeine** [vgough/encfs#18]
The configure script does not find osxfuse if it is installed in another location.

It should provide a way to pass the path to osxfuse's installation directory via --with-osxfuse=<directory>.

The result should be a configure script that does not only search for osxfuse include files in "/usr/include/osxfuse /usr/local/include/osxfuse" but also in "/usr/include/osxfuse /usr/local/include/osxfuse <directory>/include/osxfuse"

**Comment by rfjakob** [comment]
Does

    USER_INCLUDES=/foot/bar ./configure

do what you need?

**Comment by gsal** [comment]
Thanks for the hint. 

`USER_INCLUDES` does not work; or, I do not exactly know what to specify there as we actually need to specify two places, namely, `fuse/include` and `fuse/lib`.

But a bit of google-ing along the same lines yields the use of `CPPFLAGS` and `LDFLAGS`, both before and after the `./configure` command; tried after, it did not work, tried before and apparently it did. 

With this command:

```
env CPPFLAGS="-I/usw/include  -I/home/myid/local/fuse/include" LDFLAGS="-L/usw/lib -L/home/myid/local/fuse/lib" ./configure --prefix=/home/salazag/local/programs/encfs-1.8
```

The fuse library seemed to have been found: 

```
checking fuse.h usability... yes
checking fuse.h presence... yes
checking for fuse.h... yes
checking for fuse_mount in -lfuse... yes
checking for fuse_mount in -losxfuse... no
checking for osxfuse library with -L/usr/lib... no
checking for osxfuse library with -L/usr/local/lib... no
checking for osxfuse library with -L/opt/lib... no
checking for osxfuse library with -L/opt/local/lib... no
checking for fuse_new in -lfuse... yes
checking For supported FUSE API version... yes
```

but then, there seems to be an error in the `./configure` file:

```
./configure: line 20546: syntax error near unexpected token `newline'
./configure: line 20546: `  yes:no:'
```

A visit to such line seems to reveal some malformed code...looks like some accidental, partial paste...refer to lines right after the `case` statement and the well-formed `no:yes:*)`:

```
# So?  What about this header?
case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
  yes:no:
fi

    { $as_echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
$as_echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
    { $as_echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
$as_echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
    ac_header_preproc=yes
    ;;
  no:yes:* )
    { $as_echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
$as_echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
    { $as_echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
$as_echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
    { $as_echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
$as_echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
    { $as_echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
$as_echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
    { $as_echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
$as_echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
    { $as_echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
$as_echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}

    ;;
esac
```

After deleting the guilty rows, I get this final error: 

```
./configure: line 24531: syntax error: unexpected end of file
```

By the way, I generated the `./configure` file myself with the following command: 

```
make -f Makefile.dist
```

as per instructions in the `INSTALL` file, as the sources did not already come with their own `./configure`

And I think that is as much as I can report.

Looking forward to a fixed `./configure`  ; -)

gsal

**Comment by vgough** [comment]
This should no longer be an issue w/ CMake (see the 1.9-rc releases).
