### ISSUE TITLE
segmentation fault after creating new file and then call "ls"

### ISSUE THREAD

**Issue by sgriem** [vgough/encfs#180]
I use encfs v1.9-rc1 on an ARM Cortex-A8 board.

When creating a new file in the decrypt directory and than call "ls" encfs crashes with segmentation fault.
 root@81985528099045761:~/decrypt# touch gdgdg
 root@81985528099045761:~/decrypt# ls

After restart the the new file is available.
 
Else when creating a new file in the decrypt directory, unmounting, remounting and then call "ls" everything is fine and the new file is available.

The valgrind debugger (output see below) localize the problem in "encfs::EncFS_Context::lookupNode(char const*) (Context.cpp:98)".
The relevant method lookupNod() was rebuild at 10. May "Simplify FileNode Cache. Remove the need for PlaceHolder." 

With the previous version "replace getdir with readdir" 282fe77ec778212eff062c817722792a89fe7067 the crash don't occur and all runs error free.

Otherwise I can't locate any problems at an i686 system with v1.9-rc1.

Output: encfs as deamon with valgrind:
-------------------------------------------------

unique: 14, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 1211
getattr /
   unique: 14, success, outsize: 120
unique: 15, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 1211
   unique: 15, success, outsize: 32
unique: 16, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 1211
readdir[0] from 0
   unique: 16, success, outsize: 144
unique: 17, opcode: LOOKUP (1), nodeid: 1, insize: 45, pid: 1211
LOOKUP /hdjf
getattr /hdjf
   NODEID: 2
   unique: 17, success, outsize: 144
unique: 18, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 1211
LOOKUP /gdgdg
getattr /gdgdg
==1202== Thread 4:
==1202== Invalid read of size 4
==1202==    at 0x4889A9E: __shared_ptr (shared_ptr_base.h:912)
==1202==    by 0x4889A9E: shared_ptr (shared_ptr.h:103)
==1202==    by 0x4889A9E: encfs::EncFS_Context::lookupNode(char const*) (Context.cpp:98)
==1202==    by 0x488B663: encfs::DirNode::findOrCreate(char const*) (DirNode.cpp:635)
==1202==    by 0x488B893: encfs::DirNode::lookupNode(char const*, char const*) (DirNode.cpp:653)
==1202==    by 0x489067B: encfs::withFileNode(char const*, char const*, fuse_file_info*, std::function<int (encfs::FileNode*)>) (encfs.cpp:142)
==1202==    by 0x48907A5: encfs::encfs_getattr(char const*, stat*) (encfs.cpp:191)
==1202==    by 0x48CF6DB: lookup_path (fuse.c:2472)
==1202==    by 0x48CF81F: fuse_lib_lookup (fuse.c:2671)
==1202==    by 0x48D5D7B: fuse_ll_process_buf (fuse_lowlevel.c:2443)
==1202==    by 0x48D3E47: fuse_do_work (fuse_loop_mt.c:117)
==1202==    by 0x4A9756F: start_thread (pthread_create.c:336)
==1202==    by 0x4C9B89B: ??? (clone.S:89)
==1202==  Address 0x4 is not stack'd, malloc'd or (recently) free'd
==1202== 
==1202== 
==1202== Process terminating with default action of signal 11 (SIGSEGV)
==1202==  Access not within mapped region at address 0x4
==1202==    at 0x4889A9E: __shared_ptr (shared_ptr_base.h:912)
==1202==    by 0x4889A9E: shared_ptr (shared_ptr.h:103)
==1202==    by 0x4889A9E: encfs::EncFS_Context::lookupNode(char const*) (Context.cpp:98)
==1202==    by 0x488B663: encfs::DirNode::findOrCreate(char const*) (DirNode.cpp:635)
==1202==    by 0x488B893: encfs::DirNode::lookupNode(char const*, char const*) (DirNode.cpp:653)
==1202==    by 0x489067B: encfs::withFileNode(char const*, char const*, fuse_file_info*, std::function<int (encfs::FileNode*)>) (encfs.cpp:142)
==1202==    by 0x48907A5: encfs::encfs_getattr(char const*, stat*) (encfs.cpp:191)
==1202==    by 0x48CF6DB: lookup_path (fuse.c:2472)
==1202==    by 0x48CF81F: fuse_lib_lookup (fuse.c:2671)
==1202==    by 0x48D5D7B: fuse_ll_process_buf (fuse_lowlevel.c:2443)
==1202==    by 0x48D3E47: fuse_do_work (fuse_loop_mt.c:117)
==1202==    by 0x4A9756F: start_thread (pthread_create.c:336)
==1202==    by 0x4C9B89B: ??? (clone.S:89)
==1202==  If you believe this happened as a result of a stack
==1202==  overflow in your program's main thread (unlikely but
==1202==  possible), you can try to increase the size of the
==1202==  main thread stack using the --main-stacksize= flag.
==1202==  The main thread stack size used in this run was 8388608.
==1202== 
==1202== HEAP SUMMARY:
==1202==     in use at exit: 547,040 bytes in 3,467 blocks
==1202==   total heap usage: 222,937 allocs, 219,470 frees, 22,526,032 bytes allocated
==1202== 
==1202== LEAK SUMMARY:
==1202==    definitely lost: 0 bytes in 0 blocks
==1202==    indirectly lost: 0 bytes in 0 blocks
==1202==      possibly lost: 432 bytes in 3 blocks
==1202==    still reachable: 546,608 bytes in 3,464 blocks
==1202==                       of which reachable via heuristic:
==1202==                         stdstring          : 4,512 bytes in 133 blocks
==1202==         suppressed: 0 bytes in 0 blocks
==1202== Rerun with --leak-check=full to see details of leaked memory
==1202== 
==1202== For counts of detected and suppressed errors, rerun with: -v
==1202== ERROR SUMMARY: 1 errors fr

**Comment by ial0** [comment]
This may already be fixed in master, but I can't test ARM and can't recreate this on x86_64.

**Comment by sgriem** [comment]
OK, it runs correct on an ARM board in current master 105a8acd601db392dae6d754c4109aa6367e4b7a, 
thank you.
