### ISSUE TITLE
Rules regarding maximum filename length are confusing, documentation could be improved

### ISSUE THREAD

**Issue by afiskon** [vgough/encfs#183]
Hello.

Recently I faced a strange problem with EncFS. You can find all the details here:

https://github.com/syncthing/syncthing/issues/3338
https://github.com/syncthing/syncthing/pull/3355

Long story short - according to encfs man page it should handle file names up to "approximately" 189 characters since underlying ext4 FS handles up to 255 characters (formula: 3*(N-2)/4). But in practice I couldn't create a file with name containing 145 characters. Syncthing developers and I couldn't figure out why.

I believe it's because by file name you mean absolute file name, but I'm not sure about it and it's not clear from the documentation. Perhaps you could give more details on what are limits on maximum file name length and absolute file name length.

**Comment by rfjakob** [comment]
The limit is 176 characters and I will fix up the man page.

**Comment by aidan-fitz** [comment]
Is it because filenames are encoded in Base64? It would help if the man page stated that.

**Comment by wwp** [comment]
Here I can create file with 175-char names, not 176. Is this intended? Using fuse-encfs-1.9.5-1.el7.

**Comment by benrubson** [comment]
Be sure your filename does not contain special characters :
```
Based on an underlying filesystem supporting a maximum of 255 characters in
filenames, here is the maximum possible filename length depending on the choosen
encoding scheme : stream (189), block (176), block32 (143). Note that we should
rather talk about bytes, when filenames contain special (multi-bytes) characters.
```

**Comment by wwp** [comment]
It was this file: '0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234'
(without the quotes). 
$ echo -n '0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234' | wc -c
175

**Comment by rfjakob** [comment]
Yep, 175 it is. Looks like I got it right in the table: https://nuetzlich.net/gocryptfs/comparison/#file-names

**Comment by benrubson** [comment]
see #540 for a man page fix.
I reproduced this case, I also cross-checked the other max length (stream & block32).
