### ISSUE TITLE
configure.ac:15: warning: macro 'AM_CONFIG_HEADER' not found in library

### ISSUE THREAD

**Issue by lakshmi9165** [vgough/encfs#184]
Compiling encfs v 1.8.1 with "./configure make" is failing on Mac OS 10.11.5 with error:

$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/slakshmi/work/Development/Encryption/encfs-1.8.1/build-aux/missing aclocal-1.13 -I m4
configure.ac:15: warning: macro 'AM_CONFIG_HEADER' not found in library
 cd . && /bin/sh /Users/slakshmi/work/Development/Encryption/encfs-1.8.1/build-aux/missing automake-1.13 --foreign
configure.ac:35: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and will soon be removed.
configure.ac:35: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:35: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
encfs/Makefile.am:18: error: Libtool library used but 'LIBTOOL' is undefined
encfs/Makefile.am:18:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
encfs/Makefile.am:18:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
encfs/Makefile.am:18:   If 'LT_INIT' is in 'configure.ac', make sure
encfs/Makefile.am:18:   its definition is in aclocal's search path.
make: *** [Makefile.in] Error 1

**Comment by rfjakob** [comment]
Please check with 1.9-rc1 (compile using ./build.sh)

**Comment by vgough** [comment]
Encfs no longer uses autoconfig, and a number of OSX-related build improvements have gone in since then.
