### ISSUE TITLE
encfs memory usage keeps increasing

### ISSUE THREAD

**Issue by zma** [vgough/encfs#185]
I noticed after running there for some time (1+ days), the memory usage of encfs increase to a lot.
```

[zma@host201:~]$ rpm -q fuse-encfs
fuse-encfs-1.8.1-1.fc22.x86_64
[zma@host201:~]$ free
              total        used        free      shared  buff/cache   available
Mem:        8045088     7268296      119332      210956      657460      331844
Swap:       8126460     3474248     4652212
[zma@host201:~]$ top

top - 10:44:49 up 14:51,  4 users,  load average: 1.18, 0.86, 0.76
Tasks: 216 total,   2 running, 214 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.4 us,  2.3 sy,  0.0 ni, 77.5 id, 13.9 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8045088 total,   164164 free,  7260864 used,   620060 buff/cache
KiB Swap:  8126460 total,  4655308 free,  3471152 used.   353872 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                            
 2843 zma       20   0 9906720 6.007g    544 S   7.0 78.3  15:02.10 encfs                                                                                                              
 9957 zma       20   0 1844552 446772  66308 S   7.0  5.6   3:03.25 firefox                                                                                                            
 3104 zma       20   0 1571440 302704  33864 R  16.3  3.8  46:13.45 thunderbird                                                                                                        
 2154 zma       20   0 2003524  97304  24732 S   0.0  1.2   1:12.00 gnome-shell                                                       
```
The usage of the FS on encfs is quite a lot (read/write).

Are there memory leaking in version 1.8.1 of encfs? Or should I use some specific options when starting it?

Thanks.

**Comment by rfjakob** [comment]
This should not be happening. What is your workload so I can try to reproduce?

**Comment by zma** [comment]
It mainly contains dirs for thunderbird and firefox profiles and many git repositories.

**Comment by vgough** [comment]
I've not found any leaks using Clang's AddressSanitizer, or using Valgrind.  If you are able to test against the current mainline, or narrow down what operations lead to the behavior you see, that would help.

For now I'm closing since this issue hasn't been reproduced.

**Comment by docbill** [comment]
top - 09:39:16 up 20 days, 12:26,  5 users,  load average: 6.66, 5.71, 5.23
Tasks: 362 total,   2 running, 360 sleeping,   0 stopped,   0 zombie
%Cpu(s): 20.3 us, 13.3 sy, 12.0 ni, 22.2 id, 29.7 wa,  0.7 hi,  1.7 si,  0.0 st
KiB Mem :  7966952 total,   234896 free,  6991464 used,   740592 buff/cache
KiB Swap:  7995388 total,  4018912 free,  3976476 used.   482080 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
  997 root      20   0 6695612 4.178g    748 S  45.4 55.0  10087:04 encfs
