### ISSUE TITLE
Use JSON config files

### ISSUE THREAD

**Issue by aidan-fitz** [vgough/encfs#186]
Using JSON for the config file instead of XML would make it more human-readable. It's just a bunch of key-value pairs, so JSON is appropriate.

**Comment by WarheadsSE** [comment]
This would also remove the requirement for boost_serialization

**Comment by naclander** [comment]
@WarheadsSE we would probably want to keep boost_serialization for backwards compatibility for all the users who would still prefer / still have .xml configuration files. 

I was thinking of tackling this issue, however I am not sure on the best way of adding a json parer dependency to this project. [This](https://github.com/nlohmann/json) parser looks promising, but I am not sure whether to include this json file directly into the encfs project? 

If anyone has any recommendations or tips please let me know.

**Comment by benrubson** [comment]
I would recommend [jansson parser](https://github.com/akheron/jansson) as per [this comparison](http://seriot.ch/parsing_json.php).

**Comment by rfjakob** [comment]
I'm not sure it makes sense to switch. For a new project I'd strongly prefer JSON over XML, but for an existing project that already has a working XML setup AND lots of users that have XML config files on their hard disks, I don't think there is much of a reason to get rid of XML.

**Comment by benrubson** [comment]
>I'm not sure it makes sense to switch.

To switch clearly no.
We would then have to add a JSON parser in addition to the existing XML one, but is it worth it ?

**Comment by benrubson** [comment]
@aidan-fitz perhaps you could close this issue for the moment as it has the `wontfix` flag ?
Many thx 👍
