### ISSUE TITLE
GPU-based cryptography

### ISSUE THREAD

**Issue by aidan-fitz** [vgough/encfs#187]
GPU implementations of AES and Blowfish would be nice for hardware that lacks AES-NI (#118). This might be a job for the OpenSSL people, but until they do it we should either implement it ourselves or find a package that has this.

**Comment by samrocketman** [comment]
https://github.com/adrianbelgun/AES-OpenCL Found a C++ implementation using OpenCL.  I don't have experience with it but am linking it as a reference.

**Comment by rfjakob** [comment]
Not sure about this one. But I'll have to agree that this is way beyond the scope of EncFS.

**Comment by samrocketman** [comment]
Gotcha, no worries.  I'll stop researching it then.
