### ISSUE TITLE
Options like --extpass and --stdinpass for encfsctl passwd

### ISSUE THREAD

**Issue by aidan-fitz** [vgough/encfs#188]
We're evaluating EncFS at my company and we want to be able to use it with key rotation. We like that command-line options like `--standard` and `--extpass` allow us to script EncFS setup and mounting, but in order to change the password you still have to go through an interactive wizard. My idea is to use the flags `--extpass` and `--stdinpass` with `encfsctl passwd`, but because it requires two parameters (the old password to decrypt the inner key and a new password to re-encrypt it), the program would send them to `encfsctl` in JSON format, like so:

```
{
    "old_passwd": "MyOldPassword",
    "new_passwd": "MyNewPassword"
}
```

Maybe the passwords would be entered in Base64 ciphertext instead of plaintext.

**Comment by pepa65** [comment]
Cool to be able to script password changes! But I would think a new commandline option like `--newpass` should be enough.

**Comment by m13253** [comment]
Just a hint: you can use the command line tool "expect" to automate a password change, even without `--stdinpass`.

And I agree that a `--stdinpass` would be helpful, though.

**Comment by 1-eric** [comment]
Does expect work with password strings containing non-printable characters?
I ask this because the passwords I use are actually keyfiles created by: `dd if=/dev/urandom of=key ...`

**Comment by rfjakob** [comment]
I don't think that's a good idea. It's unclear what happens if there are NULL bytes or newlines in it.

How about

    dd if=/dev/urandom bs=32 count=1 status=none | sha256sum

**Comment by 1-eric** [comment]
Yes, it's a bit unclear how encfs deals with non-printable characters.
In `man encfs` it says:
```
--extpass=program
           Specify an external program to use for getting the user password.
           ...
           The program should print the password to standard output.

           EncFS takes everything returned from the program to be the
           password, except for a trailing newline (\n) which will be removed.
```

So, to be on the save side, but still using more than just letters or digits:
`tr -cd '\1-\11\13-\377' < /dev/urandom | head -c 500 > encfs.key`
This will create a keyfile of 500 characters using all possible characters except NUL and LF. This works with encfs using `--extpass='cat encfs.key'`, but I'm afraid that this password can not be changed using plain encfsctl or in combination with expect.

**Comment by rfjakob** [comment]
I don't think there is a reason to do that. 500 bytes is far more than makes sense. The underlying cipher uses at most 256 bits of information. sha256sum gives you 64 hex character which contain 64*4=256 bits of information.

**Comment by benrubson** [comment]
`encfsctl chpasswdAutomaticly` (which reads the 2 passwords from stdin) should do the trick, I then closes this, feel free to re-open if needed 👍
