### ISSUE TITLE
Multithreaded mode slower than single-threaded mode

### ISSUE THREAD

**Issue by aidan-fitz** [vgough/encfs#189]
I ran a benchmark comparing multi- and single-threaded modes, spawning _n_ forks of `dd` to write 1 GB to separate files in EncFS, and found that multithreaded mode consistently performs slower than single-threaded mode. I would expect multithreaded mode to be faster up to _n_ == the number of CPUs.

**Comment by bengoodwyn** [comment]
There are a lot of variables involved here and you have not provided much detail. What is the base file system for your encfs mount? What are you dd'ing from? How much CPU do you have available? Can you provide some of these details and perhaps some output of the commands you are executing for your tests? Have you verified how much CPU is being consumed when your tests run and perhaps the underlying disk's percent busy/idle while running the test?

**Comment by aidan-fitz** [comment]
The command I'm running is:
```bash
for i in {1..8}
do
    dd if=/dev/zero of=$i bs=4096 count=262144 &
done
time -p wait
```

| # of Processes | Multithreaded | Single-threaded |
|---------------:|--------------:|----------------:|
| 4              | 38.53 s       | 40.65 s         |
| 8              | 76.26 s       | 79.75 s         |

I'm getting different test results on my home computer (Ubuntu 16.04 with ext4) than the original machines that I tested this on (CentOS with XFS), and I don't know if I'm at liberty to disclose my results from the original test. But I do remember that single-threaded mode was at least 40% faster.

**Comment by rfjakob** [comment]
I'd recommend to test this on tmpfs (in-memory) or at least on an SSD. I tested on tmpfs and can confirm that 2 threads are not faster than 1 thread. On my two-core CPU, that's surprising.

**Comment by benrubson** [comment]
This sort of test also mainly depends on the underlying storage capacity / bandwidth.
Generally, we will observe performance degradation when multiple threads are writing to the same disk (I assume a home computer has only one disk).

Reading at the test results, 8 processes will write 2x the data of 4 processes, so with the same disk, at its max bandwidth, will take twice the time, which is what we observe.
Looks good then.

Thus closing this.

Thx 👍
