### ISSUE TITLE
configure: error: Could not find a version of the library!

### ISSUE THREAD

**Issue by Vascom** [vgough/encfs#193]
It happen then build for ppc64 little endian.

checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for boostlib >= 1.34... yes
configure: WARNING: BOOST_CPPFLAGS -I/usr/include
checking whether the Boost::Serialization library is available... yes
configure: error: Could not find a version of the library!
error: Bad exit status from /var/tmp/rpm-tmp.j6uzyy (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.j6uzyy (%build)
Child return code was: 1
EXCEPTION: [Error()]

Full log https://kojipkgs.fedoraproject.org//work/tasks/7836/15127836/build.log

ppc64 (big endian) build succeeded

Can you help?

**Comment by vgough** [comment]
Check the config.log file for details.  The current development version of encfs does no longer uses autoconfig, and it no longer depends on Boost.  So an alternative is to check out the current version from github.

**Comment by Vascom** [comment]
Then may be you can make new release?
