### ISSUE TITLE
Can't mount volume

### ISSUE THREAD

**Issue by 5kr1p7** [vgough/encfs#194]
On Ubuntu after install new kernel I need to reboot. So after that I can't mount my encfs volume (export was ok). Here is a log:

```
# encfs --public -v -f /encrypted-mail /decrypted-mail2
08:21:39 (main.cpp:559) Root directory: /encrypted-mail/
08:21:39 (main.cpp:560) Fuse arguments: (fg) (threaded) (keyCheck) (ownerCreate) encfs /decrypted-mail2 -o allow_other -f -o use_ino -o default_permissions
08:21:39 (FileUtils.cpp:174) version = 20
08:21:39 (FileUtils.cpp:177) found new serialization format
08:21:39 (FileUtils.cpp:191) subVersion = 20100713
08:21:39 (Interface.cpp:117) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:0)
08:21:39 (SSL_Cipher.cpp:335) allocated cipher ssl/aes, keySize 32, ivlength 16
08:21:39 (Interface.cpp:117) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:0)
08:21:39 (SSL_Cipher.cpp:335) allocated cipher ssl/aes, keySize 32, ivlength 16
08:21:39 (FileUtils.cpp:1542) useStdin: 0
EncFS Password: *********************
08:21:41 (Interface.cpp:117) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:0)
08:21:41 (SSL_Cipher.cpp:335) allocated cipher ssl/aes, keySize 32, ivlength 16
08:21:41 (openssl.cpp:43) Allocating 41 locks for OpenSSL
08:21:45 (FileUtils.cpp:1550) cipher key size = 52
08:21:45 (Interface.cpp:117) checking if nameio/block(4:0:2) implements nameio/block(3:0:0)
```

Nothing happens after this last line (I was waited long time). What can I do?

> Ubuntu 16.04.1 x64 (Linux 4.4.0-34-generic)
> encfs 1.8.1

**Comment by vgough** [comment]
I have not seen anything like this, and since nobody else has reported the same thing, I suspect a one-off problem with your system.

Some ideas:
* build encfs from source (preferably from github or else a 1.9 release candidate), and see if the same issue occurs.
* try creating a new encrypted filesystem, to narrow down if this issue only occurs when mounting an existing filesystem.

**Comment by samrocketman** [comment]
Closing.  If you encounter the issue again, please open a _new issue_ and reference this one for context.  Thanks @benrubson!  If you think closing this is a mistake, then let me know and I'll re-evaluate.
