### ISSUE TITLE
encfs-fails-on-ubuntu-16-04

### ISSUE THREAD

**Issue by jcalfee** [vgough/encfs#196]
encfs installs and runs but can't mount or create new partitions.  The error when it tries to create a new encrypted folder (after the last step password entry):

    encfs: symbol lookup error: /usr/lib/libencfs.so.6: undefined symbol: _ZN5boost7archive17xml_oarchive_implINS0_12xml_oarchiveEE4saveERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

The error when I try to mount my old folder from Ubuntu 14.04 is exactly the same.

I have the standard boost 1.57 installed using apt-get and I do not have BOOST_ROOT set (a villain system would not have this set).

Build: encfs version 1.8.1

(ref http://askubuntu.com/questions/812944/encfs-fails-on-ubuntu-16-04)

A work-around is appreciated..  Can I setup a specific version of boost and use it?

**Comment by jcalfee** [comment]
I'm thinking I should try with Boost 1.41

**Comment by jcalfee** [comment]
I un-tared Boost 1.41, ran ./bootstrap.sh then the build (as instructed from boostrap.sh): ./bjam ...  I don't know if it ended well or not.  Here is the last part of the build:

> gcc.compile.c++ bin.v2/libs/wave/build/gcc-5.4.0/release/link-static/threading-multi/cpplexer/re2clex/cpp_re.o
> gcc.archive bin.v2/libs/wave/build/gcc-5.4.0/release/link-static/threading-multi/libboost_wave.a
> common.copy stage/lib/libboost_wave.a
> ...failed updating 20 targets...
> ...skipped 27 targets...
> ...updated 753 targets...

After `export BOOST_ROOT=~/opt/boost_1_41_0` same error.

**Comment by vgough** [comment]
Your best bet is to grab the current encfs code from github, which is due to be released as version 1.9.  The code no longer depends on Boost.
