### ISSUE TITLE
encfs 1.9-rc2 seems not install translations files

### ISSUE THREAD

**Issue by Vascom** [vgough/encfs#198]
Then I build and run make install I see only:

Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/lib/libencfs.so.1.9.0
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/lib/libencfs.so.1.9
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/lib/libencfs.so
-- Set runtime path of "/home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/lib/libencfs.so.1.9.0" to ""
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/bin/encfs
-- Set runtime path of "/home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/bin/encfs" to "/usr/lib"
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/bin/encfsctl
-- Set runtime path of "/home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/bin/encfsctl" to "/usr/lib"
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/bin/encfssh
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/share/man/man1/encfs.1
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/share/man/man1/encfsctl.1
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/lib64/libtinyxml2.so.3.0.0
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/lib64/libtinyxml2.so.3
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/lib64/libtinyxml2.so
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/include/tinyxml2.h
-- Installing: /home/vascom/rpmbuild/BUILDROOT/fuse-encfs-1.9.0-2.fc24.R.x86_64/usr/lib64/pkgconfig/tinyxml2.pc

Translation files are not installed.

**Comment by ivfilin** [comment]
i think, 1.9.0 not ready to use in all cases.
https://github.com/vgough/encfs/issues/197

**Comment by vgough** [comment]
Thanks for the report @Vascom
