### ISSUE TITLE
Segmentation Fault on mount, before password check

### ISSUE THREAD

**Issue by valentin-lup** [vgough/encfs#201]
My system: OS X El Capitan 10.11.6, encfs installed through brew.

Create a new mapping (expert or normal) works fine and mounts ok. Created files in it sync as normal.
On reboot or unmount/re-mount I get "segmentation fault encfs /path /path" every time...

**Comment by ivfilin** [comment]
need report, gdb?

install gdb
$gdb encfs <Enter>
in gdb console write:
run -s -f -v /enc_path /mount_path <Enter>
after crashing write:
bt <Enter>

Copy debug information (backtrace) to issue

if, can`t install and use gdb, try to run encfs in foregraund-single mode with verbose info:
encfs -s -f -v /dir1 /dir2

**Comment by ivfilin** [comment]
*foreground

**Comment by valentin-lup** [comment]
Thanks ! This is what gdb outputs:

Program received signal SIGSEGV, Segmentation fault.
0x00007fff8213ff24 in std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush() () from /usr/lib/libc++.1.dylib
(gdb) bt
#0  0x00007fff8213ff24 in std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush() () from /usr/lib/libc++.1.dylib
#1  0x00007fff8213fddc in std::__1::basic_istream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool) () from /usr/lib/libc++.1.dylib
#2  0x00007fff82141b89 in std::__1::basic_istream<char, std::__1::char_traits<char> >::sync() () from /usr/lib/libc++.1.dylib
#3  0x00000001002ef732 in boost::archive::basic_text_iprimitive<std::__1::basic_istream<char, std::__1::char_traits<char> > >::basic_text_iprimitive(std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool) ()
   from /usr/local/opt/boost/lib/libboost_serialization-mt.dylib
#4  0x00000001003022d6 in boost::archive::xml_iarchive_impl<boost::archive::xml_iarchive>::xml_iarchive_impl(std::__1::basic_istream<char, std::__1::char_traits<char> >&, unsigned int) ()
   from /usr/local/opt/boost/lib/libboost_serialization-mt.dylib
#5  0x0000000100041ddd in readV6Config(char const*, std::__1::shared_ptr<EncFSConfig> const&, ConfigInfo*) () from /usr/local/Cellar/encfs/1.8.1_2/lib/libencfs.6.dylib
#6  0x00000001000439b1 in readConfig_load(ConfigInfo*, char const*, std::__1::shared_ptr<EncFSConfig> const&) () from /usr/local/Cellar/encfs/1.8.1_2/lib/libencfs.6.dylib
#7  0x0000000100043b61 in readConfig(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<EncFSConfig> const&) ()
   from /usr/local/Cellar/encfs/1.8.1_2/lib/libencfs.6.dylib
#8  0x000000010004820e in initFS(EncFS_Context*, std::__1::shared_ptr<EncFS_Opts> const&) () from /usr/local/Cellar/encfs/1.8.1_2/lib/libencfs.6.dylib
#9  0x00000001000096fc in main ()

**Comment by valentin-lup** [comment]
If it helps further... before I opened the issue I've tried "encfs -s -f -v /dir1 /dir2" to see what is happening but the output was the same... instant segmentation fault

**Comment by ivfilin** [comment]
just for useful view 
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fff8213ff24 in std::__1::basic_ostream >::flush() () from /usr/lib/libc++.1.dylib
(gdb) bt
#0 0x00007fff8213ff24 in std::__1::basic_ostream >::flush() () from /usr/lib/libc++.1.dylib
#1 0x00007fff8213fddc in std::__1::basic_istream >::sentry::sentry(std::__1::basic_istream >&, bool) () from /usr/lib/libc++.1.dylib
#2 0x00007fff82141b89 in std::__1::basic_istream >::sync() () from /usr/lib/libc++.1.dylib
#3 0x00000001002ef732 in boost::archive::basic_text_iprimitive > >::basic_text_iprimitive(std::__1::basic_istream >&, bool) ()
from /usr/local/opt/boost/lib/libboost_serialization-mt.dylib
#4 0x00000001003022d6 in boost::archive::xml_iarchive_implboost::archive::xml_iarchive::xml_iarchive_impl(std::__1::basic_istream >&, unsigned int) ()
from /usr/local/opt/boost/lib/libboost_serialization-mt.dylib
#5 0x0000000100041ddd in readV6Config(char const, std::__1::shared_ptr const&, ConfigInfo) () from /usr/local/Cellar/encfs/1.8.1_2/lib/libencfs.6.dylib
#6 0x00000001000439b1 in readConfig_load(ConfigInfo, char const, std::__1::shared_ptr const&) () from /usr/local/Cellar/encfs/1.8.1_2/lib/libencfs.6.dylib
#7 0x0000000100043b61 in readConfig(std::__1::basic_string, std::__1::allocator > const&, std::__1::shared_ptr const&) ()
from /usr/local/Cellar/encfs/1.8.1_2/lib/libencfs.6.dylib
#8 0x000000010004820e in initFS(EncFS_Context*, std::__1::shared_ptr const&) () from /usr/local/Cellar/encfs/1.8.1_2/lib/libencfs.6.dylib
#9 0x00000001000096fc in main ()
```

**Comment by ivfilin** [comment]
ok, if make steps:
encfs (any options) /d1 /d2 <Enter>
wizard steps
fusermount -uz /2 <Enter>
encfs /d1 /d2<Enter>
PWD<Enter>
SEGFAULT

no files in d1 & d2 was created , only .encfs6.xml?

filesystem (ext, zfs ...)?

After reboot?

Try to do same steps on another drive, flash or sdcard with ext3 or ext4 file system.

own & access privileges for .encfs6.xml

**Comment by valentin-lup** [comment]
so ...tried:

With DROPBOX:
1. encfs (any options) /d1 /d2 - wizard - works, mounts
2. unmount - works ok
3. encfs /d1 /d2 - SEGFALUT (don't get to password)

Without DROPBOX (external SD card)
1. encfs (any options) /d1 /d2 - wizard - works, mounts
2. reboot 
3. encfs /d1 /d2 - SEGFALUT (don't get to password)
 
In both cases left empty, just with the .encfs6.xml created by wizzard...

ENCFS version: homebrew/fuse/encfs: stable 1.8.1

**Comment by vgough** [comment]
Thanks for the stack trace.  This appears to be a problem with the Boost dependency, which is not something I support any longer.  I suspect that encfs was built with an incompatible version of boost.  Please try the latest release (v1.9-rc2).

**Comment by valentin-lup** [comment]
I will try it and let you know ! Thanks for your help so far !
