### ISSUE TITLE
Support for symbolic links

### ISSUE THREAD

**Issue by JackSabbath** [vgough/encfs#218]
As far as I remember the old EncFS4 had some serious bugs when the mounted folder was used with symbolic link. I don't remember what I did exactly then ago, but I know that I lost some files to it.

What I wanted to ask is: 
1. How well does the current version deal with it?
2. Are symbolic links taken into test scenarios?
3. In case there's still no support: is it planned?

**Comment by vgough** [comment]
Are you referring to encfs4win -- the Windows port of encfs?  I have no involvement with that, so I can't answer what the issue might have been.  I don't recall any issue with symbolic links in the Unix version (for Linux, *BSD, OSX).

**Comment by JackSabbath** [comment]
I see. Yes, I actually had this problem with encfs4win, so I guess it is not an issue of this project.

Thank you :)
