### ISSUE TITLE
Cmake trouble

### ISSUE THREAD

**Issue by a5m0** [vgough/encfs#226]
Following the instructions here https://github.com/vgough/encfs/wiki/Installing-Encfs on ubuntu 14.04 in lxc I run into the following error on cmake ..

`-- Enabled syslog logging support
CMake Warning at CMakeLists.txt:131 (find_package):
  By not providing "FindIntl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Intl", but
  CMake did not find one.

  Could not find a package configuration file provided by "Intl" with any of
  the following names:

```
IntlConfig.cmake
intl-config.cmake
```

  Add the installation prefix of "Intl" to CMAKE_PREFIX_PATH or set
  "Intl_DIR" to a directory containing one of the above files.  If "Intl"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
  GETTEXT_MSGFMT_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindGettext.cmake:58 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  po/CMakeLists.txt:1 (find_package)

-- Configuring incomplete, errors occurred!`

**Comment by makkus** [comment]
Try installing the gettext package.

**Comment by Code7R** [comment]
No, try getting a modern cmake installation. 2.8 sounds like the Debian Stable version which is waaaay too old. Fortunately there 3.6 in Stable Backports (jessie-backports branch) already.
