### ISSUE TITLE
failed install on mac osx (10.11.6) with osxfuse 3.5.2 installed: Could NOT find FUSE (missing: FUSE_INCLUDE_DIR FUSE_LIBRARIES)

### ISSUE THREAD

**Issue by maspotts** [vgough/encfs#232]
Trying to build v1.9 on my macbook.  I have osxfuse 3.5.2 installed, and all its headers, libs are in /usr/local/{include,lib}, but the cmake process can't find them.  I get this:

$ cmake ..
-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /opt/brew/Cellar/cmake/3.6.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find FUSE (missing: FUSE_INCLUDE_DIR FUSE_LIBRARIES)
Call Stack (most recent call first):
  /opt/brew/Cellar/cmake/3.6.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFUSE.cmake:29 (find_package_handle_standard_args)
  CMakeLists.txt:55 (find_package)

$ ls /usr/local/lib/libosxfuse*
/usr/local/lib/libosxfuse.2.dylib     /usr/local/lib/libosxfuse_i64.2.dylib
/usr/local/lib/libosxfuse.dylib       /usr/local/lib/libosxfuse_i64.dylib
/usr/local/lib/libosxfuse.la          /usr/local/lib/libosxfuse_i64.la
$ ls /usr/local/include/osxfuse/
fuse   fuse.h
$ ls /usr/local/include/osxfuse/fuse
fuse.h                 fuse_compat.h          fuse_lowlevel_compat.h
fuse_common.h          fuse_darwin.h          fuse_opt.h
fuse_common_compat.h   fuse_lowlevel.h

I originally saw this issue trying to install encfs via homebrew, but it seems to be an encfs issue, unless something's up with homebrew's cmake.  I tried passing in FUSE_INCLUDE_DIR and FUSE_LIBRARIES via the environment, but no luck.

Any help gratefully received!

Mike

**Comment by maspotts** [comment]
I got this to work by setting CMAKE_INCLUDE_PATH=/usr/local/include and CMAKE_LIBRARY_PATH=/usr/local/lib.  I then had trouble finding additional libraries, presumably because I'd failed to supply explicit paths for them as well, but at least I got past the OSXFUSE issue...

**Comment by benrubson** [comment]
Close this @maspotts if it's OK for you ? Thx 👍

**Comment by maspotts** [comment]
Actually I still get the same error: the upstream fix doesn’t seem to have reached me for some reason.

cmake
..
-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_INSTALL_PREFIX=/opt/brew/Cellar/encfs/1.9.1
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-Wno-dev
-DHAVE_CLOCK_GETTIME:INTERNAL=0

-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /opt/brew/Library/Homebrew/shims/super/clang
-- Check for working C compiler: /opt/brew/Library/Homebrew/shims/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/brew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /opt/brew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /opt/brew/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find FUSE (missing: FUSE_INCLUDE_DIR FUSE_LIBRARIES)
Call Stack (most recent call first):
  /opt/brew/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFUSE.cmake:29 (find_package_handle_standard_args)
  CMakeLists.txt:59 (find_package)

**Comment by benrubson** [comment]
Setting `CMAKE_INCLUDE_PATH=/usr/local/include` and `CMAKE_LIBRARY_PATH=/usr/local/lib` makes the configuration & build pass ?

**Comment by benrubson** [comment]
I tested with latest CMake release : https://cmake.org/download/
Latest OXFuse : https://osxfuse.github.io

```
$ mkdir build
$cd build
$ /Applications/CMake.app/Contents/bin/cmake ..
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found FUSE: /usr/local/include/osxfuse  
(...)
```

As you can see Fuse is correctly found.

**Comment by maspotts** [comment]
Oops, yes it does.  sorry: I mistook this for this (homebrew) thread:

  https://github.com/Homebrew/homebrew-fuse/issues/66

I *can* install encfs with the appropriate CMAKE flags; just can't get the homebrew formula to work as is.

**Comment by benrubson** [comment]
Sounds like a _howebrew_ issue then, not a _encfs_ one.

**Comment by maspotts** [comment]
Yes exactly.

**Comment by benrubson** [comment]
Could you close this issue then ?
Thx 👍
