### ISSUE TITLE
encfs creates folder logs w/ myeasylog.log in current dir

### ISSUE THREAD

**Issue by mtz** [vgough/encfs#234]
hi,

encfs creates an folder "logs" with myeasylog.log in current dir. please move this to an system folder or make this optional with configurable folder.

thanks

**Comment by SanskritFritz** [comment]
Probably related:
https://github.com/easylogging/easyloggingpp/issues/132
https://github.com/easylogging/easyloggingpp/issues/43

**Comment by benrubson** [comment]
Corrected in 1.9.1 :
https://github.com/vgough/encfs/blob/v1.9.1/CMakeLists.txt#L106

Could you then close this ?

Thx 👍

**Comment by benrubson** [comment]
Corrected in 1.9.1 :
https://github.com/vgough/encfs/blob/v1.9.1/CMakeLists.txt#L106

Could you then close this @mtz ?

Thx 👍

**Comment by mtz** [comment]
corrected, thx.
