### ISSUE TITLE
Command line options to pass Cipher, KeySize, Block Size

### ISSUE THREAD

**Issue by koshyg** [vgough/encfs#238]
Is there any command line options to pass cipher, keysize, block size and other similar settings to script EncFS setup for expert configuration mode ? If not how can I achieve the same ?

**Comment by benrubson** [comment]
```
echo "x
1
256
4096
1
...
all
your
options
..." | encfs...
```

**Comment by benrubson** [comment]
```
echo "x
1
256
4096
1
...
all
your
options
..." | encfs...
```

_please close this ticket if it solves your issue, thx !_

**Comment by samrocketman** [comment]
Closing.  If you encounter the issue again, please open a _new issue_ and reference this one for context.  Thanks @benrubson!  If you think closing this is a mistake, then let me know and I'll re-evaluate.
