### ISSUE TITLE
Encrypt the owner/group/perms of files/directories

### ISSUE THREAD

**Issue by mcassaniti** [vgough/encfs#239]
When changing the owner, owning group or permissions of a file, the details are recorded against the encrypted inodes. It would be ideal to either push the data into the start of the encrypted file, or to create a second file alongside the primary encrypted file that stores the metadata. Since the uid, gid and permissions can be fixed length, adding this into the encrypted file shouldn't be too difficult.

The underlying file system would then use the default umask values for file permissions, and the mounting user as the owner and owning group. The only leaked information about metadata is who mounted the file system.

**Comment by benrubson** [comment]
This should not be done as default but through an option, as it would add a big IO overhead (would have to read data instead of metadata to get metadata info), and/or would miss-align IOs (see #80).

**Comment by rfjakob** [comment]
Sorry, not going to happen, I'll close this as WONTFIX.
