### ISSUE TITLE
segfault when running encfs with -S for the first time

### ISSUE THREAD

**Issue by pschiffe** [vgough/encfs#241]
```
$ rpm -q fuse-encfs
fuse-encfs-1.9.1-2.fc24.x86_64
```

I would like to script the creation of encrypted folder with encfs. So I've tried:

```
$ mkdir a b
$ echo 'qwerty' | encfs -S $(pwd)/a $(pwd)/b
Creating new encrypted volume.
Please choose from one of the following options:
 enter "x" for expert configuration mode,
 enter "p" for pre-configured paranoia mode,
 anything else, or an empty line will select standard mode.
?> 
Standard configuration selected.

Configuration finished.  The filesystem to be created has
the following properties:
Filesystem cipher: "ssl/aes", version 3:0:2
Filename encoding: "nameio/block", version 4:0:2
Key Size: 192 bits
Block Size: 1024 bytes
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File holes passed through to ciphertext.

Now you will need to enter a password for your filesystem.
You will need to remember this password, as there is absolutely
no recovery mechanism.  However, the password can be changed
later using encfsctl.

Zero length password not allowed
[1]    31157 done                              echo 'qwerty' | 
       31160 segmentation fault (core dumped)  encfs -S $(pwd)/a $(pwd)/b
```

I'm not sure whether it would work without that seg fault, but that shouldn't occur in any way. Can you reproduce it? Also, is it possible to script creation of encrypted directory without using `expect` utility? Default options are fine with me.

**Comment by samrocketman** [comment]
I've not run into that.  I'll try reproducing it.  For now, check out my script.

https://github.com/samrocketman/home/blob/master/bin/mount-encfs-share.sh

**Comment by samrocketman** [comment]
My script also has an example to set the password via stdin.

**Comment by pschiffe** [comment]
Thanks for your link, I'll check it out. I'm attaching archive with all abrt data about the crash (also containing coredump). Hopefully it will help to investigate the problem [encfscrash.zip](https://github.com/vgough/encfs/files/560778/encfscrash.zip)

**Comment by pschiffe** [comment]
I've created bug report in Fedora bugzilla and we've found a workaround:
`echo -e '\nqwerty' | encfs -S $(pwd)/a $(pwd)/b`

https://bugzilla.redhat.com/show_bug.cgi?id=1390107

**Comment by Vascom** [comment]
> My script also has an example to set the password via stdin.

Main question not how create new encfs filesystem with -S option but **why segfault is present**.

Can you make changes to encfs so segfault not occure in this conditions?

**Comment by ial0** [comment]
Any thoughts on the patch I've just submitted?

Is defaulting to Config_Standard the best option here?

**Comment by pschiffe** [comment]
The PR fixing this issue was merged. Thanks @ial0 !
