### ISSUE TITLE
Hard link creation error

### ISSUE THREAD

**Issue by ftruzzi** [vgough/encfs#245]
Trying to create an hard link from a home folder to an encfs folder, the following error appears:

    plex@ubuntu:~$ touch file1
    plex@ubuntu:~$ ln /home/plex/file1 /home/plex/local-sorted/
    ln: failed to create hard link '/home/plex/local-sorted/file1' => '/home/plex/file1': Invalid cross-device link

The same command worked yesterday and I were able to create hard links. Soft links work but are sadly not an option for my use case. Any ideas? Thanks :)

**Comment by samrocketman** [comment]
This is normal.  You can't hard link across filesystems.  The fuse mounted volume and your disk is treated as completely separate filesystems.  Rather than hard links you can only create symbolic links across filesystems.

```
ln -s src dst
```

**Comment by ftruzzi** [comment]
Thank you for your reply. I understand this, but hard links have worked for me in that very same folder since I first installed encfs (a week ago or so). 

It's almost as if the system didn't notice/treat the encfs filesystem as separate until today. Do you have any idea on what could have happened? 

I think I will solve the issue migrating to a --reverse mounted filesystem, hard linking works there and that makes sense since the mounted filesystem is the encrypted one.

**Comment by samrocketman** [comment]
To be honest I'm not quite sure why it would have worked in the first place.  I would have had to seen it work and under what conditions to give you a better explanation.
