### ISSUE TITLE
acd failing on long file names

### ISSUE THREAD

**Issue by jxer** [vgough/encfs#246]
Member must have length less than or equal to 280

encfs 1.9.1 with block 32 for case insensative

im getting errors on copys due to file length issues, how do i get around this? is there a way to reduce the file size length?

**Comment by dinoboy197** [comment]
> im getting errors on copys due to file length issues, how do i get around this? is there a way to reduce the file size length?

Please see https://github.com/vgough/encfs/blob/master/encfs/encfs.pod#caveats. In short, your unencrypted filesystem's maximum file length limits the length of filenames that you can use. There is a way around this, which is to modify your existing filesystem to have a longer filename length.

**Comment by benrubson** [comment]
Close this non-bug ticket ?
