### ISSUE TITLE
Extended attributes problem with dangling symlinks

### ISSUE THREAD

**Issue by ekalin** [vgough/encfs#247]
On a normal filesystem, this is what happens when one tries to list attributes in a dangling symlink:
```
$ ln -s inexistent_file.txt bad_link

$ attr -l bad_link
[No output]

$ attr -l inexistent_file.txt
attr_list: No such file or directory
Could not list "(null)" for inexistent_file.txt
```

But on an encfs mount, there is an error:
```
$ ln -s inexistent_file.txt bad_link

$ attr -l bad_link
attr_list: No such file or directory
Could not list "(null)" for bad_link

$ attr -l inexistent_file.txt
attr_list: No such file or directory
Could not list "(null)" for inexistent_file.txt
```

It seems that instead of calling llistxattr() (which lists xattrs from the link itself), listxattr() (which lists xattrs from the pointed-to file) is called instead. This is an strace from the "attr -l bad_link" command in a normal filesystem:

`llistxattr("bad_link", "", 65536)       = 0`

And here's the strace of the encfs process of the same command in an encfs mount:

`listxattr("/tmp/e/cryptstore/tTj5KY7uJx3Uf-PDeR0bIV7b", 0x1f7df80, 65536) = -1 ENOENT (No such file or directory)`

**Comment by dinoboy197** [comment]
I believe I'm seeing a manifestation of the same problem in #283 . @ekalin , can you reproduce my problem in #283?
