### ISSUE TITLE
Build failure on kfreebsd

### ISSUE THREAD

**Issue by Code7R** [vgough/encfs#249]
Hi,

looks like easylogging header does not consider any hybrid environments, like kFreeBSD (GNU-based userland on fbsd kernel). To detect this properly, it needs to check not only __FreeBSD__ but alternatively the __FreeBSD_kernel__ too. I just tested this on a porter machine, the build error is gone.

For details, see https://sourceforge.net/p/predef/wiki/OperatingSystems/ and https://buildd.debian.org/status/fetch.php?pkg=encfs&arch=kfreebsd-amd64&ver=1.9.1-2&stamp=1479242148 which happens without the fix.

**Comment by benrubson** [comment]
See if #298 solves your issue.
If not, I think you should open an easylogging++ issue.
Thx 👍

**Comment by benrubson** [comment]
@Code7R some news ?
Could you test `master` branch ?
Many updates have been done around logging.
Thank you 👍

**Comment by samrocketman** [comment]
Closing.  If you encounter the issue again, please open a _new issue_ and reference this one for context.  Thanks @benrubson!  If you think closing this is a mistake, then let me know and I'll re-evaluate.
