### ISSUE TITLE
IDEA: tarball dump function, like git-archive

### ISSUE THREAD

**Issue by Code7R** [vgough/encfs#252]
Hello,

it would be nice if encfs had some kind of export mode which allows you to convert from encrypted filesystem folder into unencrypted tarball (i.e. the executable itself would produce a tar stream, similar to "git archive" utility). It could also work the other way round, export a tarball stream with encrypted files from a plaintext filesystem.

The usecase is, for example: one might have (fast) access to a powerful machine but not have root permissions there to use fuse.

**Comment by benrubson** [comment]
Hi @Code7R,
Can't you write a (Bash ?) tool wrapping `encfsctl` ?

**Comment by rfjakob** [comment]
I don't think this is going to happen, sorry. I'll close this as WONTFIX.
