### ISSUE TITLE
About "dev" branch, version 2, and "NameIO::recodePath"

### ISSUE THREAD

**Issue by javerous** [vgough/encfs#255]
Hello,

I see that "dev" branch (aka version 2 of encfs) was not updated for a while. Is it abandoned ?

Anyway, you add some code in "recodePath" function to append a "+" instead of "/" when it's the first character, so we don't start with a "/".
I'm not sure what the purpose, but it (deeply) breaks compatibility with previous encrypted FS : for some path, it will not be able to find the correct file on the root directory, and so, some operations fail.
If this '+' is really necessary to handle some corner case, do you have plans to handle some backward compatibility ?

Thank you.

**Comment by dinoboy197** [comment]
> I'm not sure what the purpose, but it (deeply) breaks compatibility with previous encrypted FS : for some path, it will not be able to find the correct file on the root directory, and so, some operations fail.

Would you be able to provide the exact commands you're using which show the problem so we can reproduce and verify the issue?

**Comment by benrubson** [comment]
See #314 for some news regarding EncFS v2.
Not sure then the dev branch is still active :|

**Comment by samrocketman** [comment]
Closing.  If you encounter the issue again, please open a _new issue_ and reference this one for context.  Thanks @benrubson!  If you think closing this is a mistake, then let me know and I'll re-evaluate.
