### ISSUE TITLE
Copying/Moving files on encfs/rclone mount

### ISSUE THREAD

**Issue by ajkis** [vgough/encfs#256]
There is a critical bug with copying/moving files in encfs folder mounted over rclone.
The rclone github issue https://github.com/ncw/rclone/issues/961

The rclone dev explanation 
```
This is what I think is happending. When you do a normal cp not through encfs it opens the output file write only. You can see that in the strace

2016/12/18 14:51:17 fuse: <- Open [ID=0x1f Node=0xe Uid=0 Gid=0 Pid=1880] dir=false fl=OpenReadWrite
2016/12/18 14:51:17 fuse: -> [ID=0x1f] Open error=EIO: can't open file - writer failed
However by the time that has gone through encfs it has become a ReadWrite. What encfs appears to do is create the file then open it read write.

2016/12/18 14:51:17 fuse: <- Open [ID=0x1f Node=0xe Uid=0 Gid=0 Pid=1880] dir=false fl=OpenReadWrite
2016/12/18 14:51:17 fuse: -> [ID=0x1f] Open error=EIO: can't open file - writer failed
rclone can't open files read/write it can only open them read or write, not read and write - that is why you are getting the EIO.
```

Is there a way to mount encfs in a way to fix above issue. 

p.s Iam using ubuntu 16.04 with apt install encfs ( version 1.8.1 )

**Comment by rfjakob** [comment]
No, encfs needs read AND write access. It has to do a read-modify-write
cycle if you modify a block.

**Comment by naclander** [comment]
Has anyone found a workaround for this?

**Comment by benrubson** [comment]
I thought about this workaround, but rclone will not allow 2 fd to the same file (one read, one write), as explained in https://github.com/ncw/rclone/issues/961.

> No, encfs needs read AND write access. It has to do a read-modify-write cycle if you modify a block.

Perhaps we could open write by default, and re-open read-write only if needed ?
This perhaps could help solving this issue. It would however I think need some deep modifications.

**Comment by benrubson** [comment]
Please test the rclone solution ?
https://github.com/ncw/rclone/issues/961#issuecomment-379000536 :
> Anyone coming across this issue: note that using --vfs-cache-mode writes will likely fix the problem for you now with a recent rclone.
