### ISSUE TITLE
Additional item needs to be added to the "Installing EncFS" Wiki page

### ISSUE THREAD

**Issue by dellipse** [vgough/encfs#260]
The package 'gettext' also needs to be added to the second apt-get line on the Wiki page.

`apt-get install libfuse-dev libssl-dev librlog-dev libboost-serialization-dev`
should be changed to
`apt-get install libfuse-dev libssl-dev librlog-dev libboost-serialization-dev gettext`

**Comment by dinoboy197** [comment]
I was able to install following those instructions without explicitly specifying `gettext`. Would you show us the exact commands you're using, start to finish, so we can replicate the problem?

**Comment by rubenvarela** [comment]
If you install from the `mini.iso`, http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/netboot/mini.iso

(I only selected the base system)

Then you install the dependencies, `wget` encfs.zip, install `unzip`, then run `cmake ../`

```cmake ..
-- Using local TinyXML2 copy
-- Enabled syslog logging support
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
  GETTEXT_MSGFMT_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindGettext.cmake:87 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  po/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ruben/encfs-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/ruben/encfs-master/build/CMakeFiles/CMakeError.log"'
```

Run `sudo apt install gettext`, the error disappears,

```ruben@sync:~/encfs-master/build$ cmake ..
-- Using local TinyXML2 copy
-- Enabled syslog logging support
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.7")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ruben/encfs-master/build
```

**Comment by benrubson** [comment]
Who has Wiki edit right to make this tiny update ?
Only @vgough ?
Thx 👍

**Comment by rubenvarela** [comment]
The wiki home is authored by @rfjakob 
The installation instructions by @vgough

**Comment by rfjakob** [comment]
Done, thanks
