### ISSUE TITLE
default_settings and allow_others

### ISSUE THREAD

**Issue by FlannelFox** [vgough/encfs#263]
I was trying out the 1.9.1 build and it seems that the inclusion (by default) of default_settings causes issues for people that are using allow_others. This stopped me from being able to share the mounted FS with other users. To get the connection working as it was I had to specify the --no-default-settings flag in my mount script.

While this is not a bug, it is an issue that people are likely to hit moving from  <1.9.1 builds.

**Comment by benrubson** [comment]
Yep, `--no-default-flags -o use_ino` to get the 1.8.x behaviour back 👍

**Comment by benrubson** [comment]
@FlannelFox could you then close this bug report (as it is not a bug :)
users should be able to find it in closed issues :)
Many thx 👍

**Comment by benrubson** [comment]
@FlannelFox (or @rfjakob) could you then close this bug report (as it is not a bug :)
Users should be able to find it in closed issues :)
Many thx 👍

**Comment by benrubson** [comment]
Or perhaps @samrocketman ? :)
I remembered you are the 3rd collaborator in this project 👍
