### ISSUE TITLE
Unable to locate root directory.

### ISSUE THREAD

**Issue by skullscream** [vgough/encfs#264]
Says 'Unable to locate root directory, aborting.Build: encfs version 1.9.1' when I try creating a new drive on a new apricity os installation.

```milan  ~  encfs /.encrypted /encrypted
The directory "/.encrypted/" does not exist. Should it be created? (y,n) **[*I type y here*]**
Directory not created.
Unable to locate root directory, aborting.Build: encfs version 1.9.1

Usage: encfs [options] rootDir mountPoint [-- [FUSE Mount Options]]
```
This is how I tried creating a new one:
```encfs ~/.encrypted ~/encrypted```

**Comment by rfjakob** [comment]
Please try

encfs ~/.encrypted ~/encrypted

**Comment by skullscream** [comment]
It's the same thing I was trying.

**Comment by rfjakob** [comment]
Are you sure? Do you have write permissions to the filesystem root ("/")?

**Comment by skullscream** [comment]
Yes I'm sure. How do I obtain write permissions to root on apricity os (arch)?

I tried ```sudo mount -o rw,remount /``` but still it's the same thing.

**Comment by ial0** [comment]
After looking at the code, the error "Directory not created."  means either 'y' was not pressed or there was an error reading the input.

Could you run, `strace encfs ~/.encrypted ~/encrypted`, and provide the output.

**Comment by skullscream** [comment]
Yeah....I didn't press Y because I'm used to Arch not requiring that. It only requires 'enter' for positive answer. Sorry about that :)
