### ISSUE TITLE
libfuse3

### ISSUE THREAD

**Issue by tcf909** [vgough/encfs#265]
What would be the best way to leverage libfuse3 for encfs?

I'm using encfs against an ACD_CLI fuse mount, and would like to take advantage of writeback cache so that the chunks being written to the underlying fileystem end up being larger than 4k.

Currently performance is really bad (even with an r4.xlarge instance in the same datacenter as amazon cloud drive [us-east-1]).

Hoping this will help.

I was able to get libfuse3 installed on the system (co-exist), but couldn't figure out cmake enough to get it to leverage the new library.

Seems to install to /usr/local/* (/usr/local/lib, etc).

**Comment by benrubson** [comment]
You should need #267 as a first step for encfs to be libfuse3 compatible 👍

**Comment by benrubson** [comment]
You would need to merge #293.
And also you would have to change `FUSE_USE_VERSION` to 30 there :
https://github.com/vgough/encfs/blob/v1.9.1/CMakeLists.txt#L61

**Comment by benrubson** [comment]
#293 merged, should be OK now @tcf909 👍 
Could you confirm and close this issue if it's ?
Thank you !
