### ISSUE TITLE
Display default yes/no choice when creating initial directories

### ISSUE THREAD

**Issue by ial0** [vgough/encfs#268]
This is a follow on from #264.

Currently the text displayed is,
`The directory "..." does not exist. Should it be created? (y,n)`

I'm recommending changing this to
`The directory "..." does not exist. Should it be created? (y,N)`

This affects internationalization, so I'm adding this an issue

**Comment by benrubson** [comment]
Solved by #302 👍

**Comment by rfjakob** [comment]
#302 is merged
