### ISSUE TITLE
--reverse option with existing config

### ISSUE THREAD

**Issue by shadycuz** [vgough/encfs#277]
Hi,

Is it somehow possible to use encfs --reverse with an existing config file (created by using encfs in normal mode)?
I'm using cloud storage, so I encrypted my files using encfs normally.
Now I have a big external drive that I also want to upload, and it seems a bit redundant to first move those unencrypted files to my normal encfs-setup, to get them uploaded (also, I don't have the space to move/copy everything to my internal drive).
So I wanted to use the reverse option and then upload the encrypted content to my online storage, but I get "The configuration loaded is not compatible with --reverse".

I hope there's a better option than getting a second external drive to encrypt everything using the regular encfs setup, and then upload it?

Thanks,
Levi

**Comment by dinoboy197** [comment]
> I'm using cloud storage, so I encrypted my files using encfs normally.

What commands, exactly, did you use to do this?

**Comment by shadycuz** [comment]
`encfs -S -o allow_other /files/encrpyted /files/unencrpyted`

This issue I'm having down is I copied the encfs.xml to the other host, bought a second external drive and encrypted the files like I did on the first host, but now the 2 hosts can't see each others encrypted files with the same config?

**Comment by benrubson** [comment]
@shadycuz did you manage to solve your issue ?
(_If so please close this issue ? Thx !_)
Some options are not compatible with the reverse mode, you should then create your configuration file using reverse mode first, then use it with normal mode.

**Comment by shadycuz** [comment]
@benrubson  not really. Maybe this should be a feature request, but it doesn't appear if you have a "regular" encfs.xml that you can then use it to do a reverse encfs mount.

**Comment by benrubson** [comment]
Depending on the configuration options you used creating your configuration file, you won't be able to use it in reverse mode.

You should then, if you can, re-create a whole new configuration file in reverse mode, and then use it in normal mode, and re-use it in reverse mode :)

PR #279 should help to use paranoia mode in reverse mode (in read only).
Perhaps this is what you need to use your current configuration file in reverse mode.

**Comment by benrubson** [comment]
@shadycuz did my last comment helped you solve your issue ?
Thank you 👍

**Comment by samrocketman** [comment]
Closing this issue; if you think it should be reopened then please let me know.
