### ISSUE TITLE
pod error in last tagged release

### ISSUE THREAD

**Issue by junkblocker** [vgough/encfs#28]
Over at homebrew/homebrew#33479 , ``encfs`` build is running into a pod issue which has already been fixed here.

```
encfs.pod around line 1: =cut found outside a pod block.  Skipping to next block.
encfsctl.pod around line 1: =cut found outside a pod block.  Skipping to next block.
POD document had syntax errors at /usr/bin/pod2man5.18 line 72.
make[2]: *** [encfsctl.1] Error 255
make[2]: *** Waiting for unfinished jobs....
POD document had syntax errors at /usr/bin/pod2man5.18 line 72.
make[2]: *** [encfs.1] Error 255
```

They however prefer to pull stable/tagged builds and your latest ``1.7.5`` tagged build contains this issue. Please consider release a new tagged build with this fixed. Thanks.

**Comment by rfjakob** [comment]
1.8 is released, contains the fix.
