### ISSUE TITLE
HostA and HostB can not unencrpyt each other's file using same config

### ISSUE THREAD

**Issue by shadycuz** [vgough/encfs#284]
Pretty much what the title says. I tried this with a test file and it worked, so I proceeded to encrypt over 100GB of data, but now they can't see each others files when I mount them.

**Comment by rfjakob** [comment]
Are you sure the config ist the same? Is the md5sum of .encfs6.xml the same?

**Comment by shadycuz** [comment]
I will check and post back, but my file don't have a number in the name just encfs.xml

**Comment by rfjakob** [comment]
Oh, really? Is this EncFSMP on Windows?

**Comment by shadycuz** [comment]
No Ubuntu 16.04 maybe I renamed that?

**Comment by shadycuz** [comment]
Yes the files are the same I wondering if during the transfer from host B to A some how the bit's are getting rearranged and making the decryption fail?

**Comment by dinoboy197** [comment]
Would you share with us the exact commands you're using on host A and host B to both perform the encryption and decryption, so we can replicate the problem?

**Comment by shadycuz** [comment]
Yes, let me do some testing, might be as late as next week, but I will document all my steps and the expected outcome.

**Comment by benrubson** [comment]
@shadycuz is it now OK for you ?
If so, could you close this issue ?
Many thx 👍

**Comment by shadycuz** [comment]
@dinoboy197 @benrubson  So this issue is when you move the encrypted files around. I wasn't really thinking straight or I would have realized my error. So if you have /files/encrypted/ServerA/BackupA.zip and you move those encrypted files to a new server and store them in /files/encrypted/mybackups/ServerA/BackupA.zip they now become invisible even though you are using the same key. I have learned my lesson, and now I have a working setup. 

Thanks,
Levi
