### ISSUE TITLE
Portable encfs

### ISSUE THREAD

**Issue by pdroalves** [vgough/encfs#288]
I would like to add some files encrypted with encfs to a pendrive and keep a portable installation of encfs to make it easy to decrypt those files in a non-previously set computer.

I couldn't find instructions about it. Is it possible?

**Comment by benrubson** [comment]
I think U'll need to manually deal with `cmake` to build and link as `static`.
There is currently no built-in option to achieve this.

**Comment by benrubson** [comment]
@pdroalves did you manage to do what you want ?
(_if so close this issue ? thx !_)

**Comment by samrocketman** [comment]
Closing.  If you encounter the issue again, please open a _new issue_ and reference this one for context.  Thanks @benrubson!  If you think closing this is a mistake then let me know and I'll re-evaluate.
