### ISSUE TITLE
Can't change password if empty password was initially set

### ISSUE THREAD

**Issue by samatjain** [vgough/encfs#290]
Regarding https://github.com/vgough/encfs/commit/5994b28542e7f551b71ac471ff9aacf6dcd5a3b0

I had no password on my EncFS volume. I kept my key/configuration in a different, secure location separate from my encrypted files using the ENCFS6_CONFIG environment variable. In EncFS 1.9.1, I started receiving an error when trying to mount my volumes:

    $ encfs /encrypted /plaintext
    EncFS Password:
    fatal: zero-length passwords are not allowed

I rather not have another password to keep track of, but if I have to set a password, then I don't mind. But, when I try to set a password:

    $ encfsctl passwd /encrypted
    Enter current Encfs password
    EncFS Password:
    fatal: zero-length passwords are not allowed

I cannot change it, because EncFS no longer accepts no passwords.

Is there a workaround other than downgrading to an older EncFS to change the password on my volume?

**Comment by rfjakob** [comment]
No, sorry. Allowing empty passwords was a bug, actually, that is fixed now. Please change your password using an older version.
