### ISSUE TITLE
Can't remove directory

### ISSUE THREAD

**Issue by nilbus** [vgough/encfs#30]
I have a directory in my encrypted fs that cannot be deleted.

``` sh
$ sudo rm -rf org.eclipse.e4.workbench/
rm: org.eclipse.e4.workbench/: Directory not empty

$ ls -al org.eclipse.e4.workbench/
total 16
drwxr-xr-x  3 nilbus  staff  102 Nov  6 14:50 .
drwx------@ 3 nilbus  staff  102 Nov  6 14:53 ..
```

Is this perhaps related? https://bugs.launchpad.net/ubuntu/+source/encfs/+bug/160214
I would like to try the mentioned [workaround](https://bugs.launchpad.net/ubuntu/+source/encfs/+bug/160214/comments/2), but I don't know how he was implying that one should be able to find the encrypted folder using the inode number.

**Comment by noproto** [comment]
Leaving a note for anyone else who has this issue in the future. If you have trouble finding the directory in your encrypted directory (such as a very large directory), make a symlink. Browsing to your encrypted directory, you can quickly find it as it is the symlink. This applies to chmod as well.
