### ISSUE TITLE
Password is echoed to terminal when invoked over ssh

### ISSUE THREAD

**Issue by ncoop** [vgough/encfs#311]
```
4.10.1-1-ARCH #1 SMP PREEMPT Sun Feb 26 21:08:53 UTC 2017 x86_64 GNU/Linux
encfs version 1.9.1
```

In normal usage, the password input is hidden:
```shell
encfs /path/private /home/me/private
EncFS Password:
```

But if encfs is called as the ssh command, it is echoed:
```shell
ssh mybox encfs /path/private /home/me/private
EncFS Password: i see my password
```

**Comment by benrubson** [comment]
Try the following ?
`ssh -t mybox encfs /path/private /home/me/private`

**Comment by ncoop** [comment]
Yes, that works.

Can encfs "force pseudo-terminal allocation" itself? If not this is as resolved as it gets.

**Comment by benrubson** [comment]
Unfortunately I'm not sure it can be done.
SSH does not allocate a tty by default when it is given a command (whatever the command is).
You then have to force it with `-t`.
_please close this if your issue is solved ? thx !_
