### ISSUE TITLE
Two encrypted files resolve to same unencrypted name

### ISSUE THREAD

**Issue by jmelton98** [vgough/encfs#313]
I'm using encfs with acd_cli. I have an issue where two encrypted files in the same folder resolve to the same unencrypted file name. This occurs when the first encrypted file is uploaded via acd_cli, then the first file is deleted locally. Later, a second encrypted file of the same name but different characteristics is created locally and is uploaded to the same folder via acd_cli. The resulting scenario appears to be that the second file is lost or invisible as both encrypted files now resolve to the same unencrypted file name and the newer file is superceded by the older file.

This may not really be an issue, but looking for the easiest way to resolve the newest file, when this scenario exists. I have tried to use encfsctl to find the encrypted names using the unencrypted name, but this proves too difficult and time consuming for how frequently it happens. It tends to happen fairly often in my setup, which may be similar to other users out there.

**Comment by rfjakob** [comment]
In EncFS, the *same plaintext name* always encrypts to the *same ciphertext name*. So it's not really possible to have two *different ciphertext names* that decrypt to the *same plaintext name*.

There must be something else going on! Note that there are other bug reports about acd_cli causing data corruption, https://github.com/rfjakob/gocryptfs/issues/59 .

**Comment by jmelton98** [comment]
Ok, thanks for the info. Sounds like I was on the wrong path. Looks like I may be missing the --overwrite argument in acd_cli. I'll give that a shot an see if it fixes my issue.

http://acd-cli.readthedocs.io/en/latest/transfer.html#upload

Thanks
