### ISSUE TITLE
cryptodev improvement, verification

### ISSUE THREAD

**Issue by julianhille** [vgough/encfs#318]
I build encfs against an openssl lib with cryptodev enabled.
Openssl speedtests showed significant improvements on aes and other encryptions.
The speed improvement was around factor 100.

I now build the encfs using these created openssl libs with cryptodev as engine.

Speedtests

`dd if=/dev/urandom of=/mnt/mycrypted_dir bs=200m count=1` did not show any CPU load 
nor disk speed improvments.
The load of 1 cpu just raises to 70-80% and the disk speed stays the same.
I did not expect any big performance jumps on disk speed as im trying to write to an eMMC
but i expected a lot less cpu usage.

Can somebody verify that there is no real gain even if i expected it? 
Is there a way to find out which engine is used by encfs some logging events i may have missed / overlooked?

**Comment by benrubson** [comment]
Bottleneck is certainly `/dev/urandom` which generally has a limited throughput.

**Comment by julianhille** [comment]
I actually dont think so as im using a hardware rng. But ill try
`/dev/random` and see if that makes any difference

Ben RUBSON <notifications@github.com> schrieb am Fr., 24. März 2017, 21:48:

**Comment by rfjakob** [comment]
I think you want to use /dev/zero instead.

**Comment by julianhille** [comment]
tests with `/dev/zero` and `/dev/random` did also not show any improvements.
I also tried creating a list of files from 5-200MB and copied them from one location to the encrypted disk.
The cpu load is still the same.
Versions are 1.8.1 with and without cryptodev. 
CPU is still at 70-90%.

How can i verify if that thing is really using the cryptodev device? 
Im thinking about an lsof while writing a file so that there should be an open fd to the hardware crypto device.

**Comment by benrubson** [comment]
Is this openssl (cryptodev enabled) lib the only one on your system ?

**Comment by julianhille** [comment]
There are two instances of openssl installed one with and one without cryptodev.
But i have replaced every link / file of the one without with the one with cryptodev.
`lsof | grep crypto | grep encfs` showed that encfs is using the cryptodev engine.

**Comment by benrubson** [comment]
Try reading from a raw device (different from the one where your _encfs_ directory is) ?
`dd if=/dev/sdb of=/home/encfs/bigfile bs=4k`

**Comment by julianhille** [comment]
Its the same cpu usage. around 70-80% (btw its only a 1ghz cpu)

btw lsof gives me (only if encfs is running):
```
lsof | grep "dev/crypto"
encfs     16984                   root    3u      CHR      10,56        0t0      42697 /dev/crypto
encfs     16984 16985             root    3u      CHR      10,56        0t0      42697 /dev/crypto
encfs     16984 16986             root    3u      CHR      10,56        0t0      42697 /dev/crypto
encfs     16984 17011             root    3u      CHR      10,56        0t0      42697 /dev/crypto
encfs     16984 17021             root    3u      CHR      10,56        0t0      42697 /dev/crypto
```

**Comment by benrubson** [comment]
Did you perform some speed and CPU usage tests just using `openssl` binaries ?

**Comment by julianhille** [comment]
With cryptodev around 50% cpu usage (the bigger the blocks get the lower the cou usage)
```
OpenSSL 1.0.1u  22 Sep 2016
built on: Thu Mar 23 10:05:10 2017
options:bn(64,32) rc4(ptr,char) des(idx,cisc,16,long) aes(partial) idea(int) blowfish(ptr)
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DHAVE_CRYPTODEV -DUSE_CRYPTDEV_DIGESTS -march=armv7-a -Wa,--noexecstack -O3 -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DGHASH_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-256-cbc      16243.00k    36837.76k   129817.60k   706867.20k  6504448.00k
```


without cryptodev around ~85-95% cpu usage.
```
OpenSSL 1.0.1t  3 May 2016
built on: Thu May 19 05:24:04 2016
options:bn(64,32) rc4(ptr,char) des(idx,cisc,16,long) aes(partial) blowfish(ptr)
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wa,--noexecstack -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DGHASH_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-256 cbc      26955.71k    31424.33k    32571.25k    32972.80k    32889.02k
```

**Comment by benrubson** [comment]
@julianhille did you arrive to a conclusion ?
Certainly that writing to a non-encfs directory takes almost the same CPU amount (70-80%), so that you won't be able to go lower than this.

**Comment by benrubson** [comment]
Closing this, feel free to re-open if needed 👍
