### ISSUE TITLE
How to recover data?

### ISSUE THREAD

**Issue by Jmlevick** [vgough/encfs#32]
I'm currently using Gnome EncFS manager, which it's just a frontend for EncFS...

Recently I changed my Gnome EncFS password for a randomly generated passphrase  and I added some words at the end of it... I actually recall the words I added but I can't remember the FULL passphrase and the password manager didn't saved the new passphrase so now I can't access my data (it still there but it is encrypted); it's worth mentioning that I have access to:

- My physical machine with normal user and super user privileges (obviously)
- My .encfs6.xml file
- Data recovered with photorec/testdisk which seems to be "ciphered with the previous password" (I can tell because of the date)
- All of the encrypted data
- Second half of the passphrase (the one I actually wrote and not just copypasted from some "xkcd random passphrase gemerator")

Is it possible to recover it using some EncFS commands as root or something? (at least the data ciphered with the previous password?) There is like 50GB of CRITICAL data there, YEARS of hard work.

So, Ideas? Thanks...

**Comment by Jmlevick** [comment]
Hello, it's me again with the same problem (kinda, shame on me); Formatted my computer, forgot to print the new EncFS password and now data seems unrecoverable. This time I have:

* My physical machine with normal user and super user privileges (obviously)
* My .encfs6.xml file
* All of the encrypted data

I had a TXT file inside the "clear" mount folder with the plain txt password written inside. I know how it was called but no what words were on it... I'm running photorec right now with the hope of recovering that txt file but... is there a way of "cracking" my password (and/or changing it/decrypting the data) with just my .encfs6.xml file?

I rwmwmber on my previous setup the gnome keyring mounted the folder with it's password when I logged in to the computer, but because I deleted my dotfiles this is not possible anymore.

**Comment by rfjakob** [comment]
Do you have older versions of .encfs6.xml ?

**Comment by Jmlevick** [comment]
@rfjakob Not this time, sadly.

**Comment by Jmlevick** [comment]
Update: Both photorec and scalpel were unable to recover the TXT file with the cleartext password as it was never deleted.

**Comment by rfjakob** [comment]
That file with the password is also encrypted?

**Comment by Jmlevick** [comment]
Yes. I was trying to recover the clear text one (the one that mounts one you enter the password), but it seems unreachable by the tools I used. This time I only have my encrypted data and my .encfs6.xml file basically... I use Linux though, can the password be retrieved in some way or it's these data lost?

**Comment by rfjakob** [comment]
I think "john the ripper" supports cracking `.encfs6.xml`. However, if the passphrase is strong, it will never get it. Otherwise the data is lost.

**Comment by chr15m** [comment]
JTR supports this using the following script:

https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/encfs2john.py

Pipe the output into a file and then run `john` on it.
