### ISSUE TITLE
Decrypt files on Windows that were encrypted on linux?

### ISSUE THREAD

**Issue by skullscream** [vgough/encfs#323]
Is there a way to do this? I've messed up my linux installation but managed to get access to files and copied entire encrypted folder. Can I decrypt it now on windows?

**Comment by benrubson** [comment]
I think this is what you are looking for :
https://github.com/jetwhiz/encfs4win

**Comment by skullscream** [comment]
Found them here https://github.com/jetwhiz/encfs4win/releases but cannot seem to download a windows version. The download doesn't start.

**Comment by skullscream** [comment]
Installed it and now it won't run. I got the driver installed and all those dependencies seem to have been installed without error. Whenever I try to run one of the .exe files in the installation directory it just pops up a cmd, flashes some messages and closes quickly before I can read anything.

**Comment by benrubson** [comment]
You should try to open an issue there :
https://github.com/jetwhiz/encfs4win
Or run a Linux distribution using VirtualBox to be able to use this original UNIX EncFS version.

**Comment by skullscream** [comment]
You think that'd work? I always thought it could only be decrypted on the system it was encrypted.

**Comment by benrubson** [comment]
It will as encryption methods and encryption keys remain the same 👍

**Comment by skullscream** [comment]
Okay. I will try doing that in the VM. Thanks.

**Comment by skullscream** [comment]
Well actually encfs4win works I just didn't know I needed to open it in the sys tray. :D it works on windows, no need for VM.

**Comment by benrubson** [comment]
Perfect 👍 
You should now be able to close this issue :)
Thank you for your feedback !

**Comment by skullscream** [comment]
Thanks for your help. Closed.
