### ISSUE TITLE
Key file stored in alternative location

### ISSUE THREAD

**Issue by Francewhoa** [vgough/encfs#324]
<a name="summary"></a>
## [Summary](#summary)

This ticket is a suggested new feature for EncFS. About the user being able to use a [Graphical User Interface (GUI)](https://en.wikipedia.org/wiki/Graphical_user_interface) to store the EncFS volume key file into an alternative location. In other words, the user being able to do that _without_ the Terminal/Console command line. The suggested [User Story](#user-story) below clarifies the need, the benefits, and [Assumptions](#assumptions).

Any volunteer for a patch for that new feature? The team at Ubertus.org would be happy to contribute testing and documentation.

<a name="user-story"></a>
## [User Story](#user-story)

As a user of EncFS, using the Graphical User Interface (GUI), I need to be able to stored the EncFS key file into an alternative location of my choosing, so that:
* My EncFS volume is more secure
* For each EncFS volume I could store its key file anywhere

<a name="assumptions"></a>
### [Assumptions](#assumptions)

* Assumes that new feature would be deactivated by default. So no change to past already created EncFS volumes. 
* Assumes this [User Story](#user-story) is about the user being able to use a Graphical User Interface (GUI) to store that volume key file into an alternative location. In other words, the user being able to do that _without_ the Terminal/Console command line. For those not familiar with EncFS each time you create a new EncFS volume a new key file is automatically created. That key file is into the `.encfs6.xml` file. That key file is store with the EncFS control file at the top level of each EncFS container. In other words, the EncFS encrypted data is physically store on the same volume as the key file. This process is automated and easy :) But it's currently not easily possible to store that key file into an alternative location using the GUI and without command line.

* Assumes the following mockups and scenario with steps clarify [that User Story](#user-story) 

     1. Using EncFS GUI the user click on the _"Create or import a stash"_ button to create a new EncFS volume/stash. The [number 1 in that screenshot](https://cloud.githubusercontent.com/assets/119942/25784757/5fab5d7c-3327-11e7-81fe-c26168907fa2.png) shows the location of that button. 

     1. User click on the _"Configure"_ button. The [number 2 in that screenshot](https://cloud.githubusercontent.com/assets/119942/25784757/5fab5d7c-3327-11e7-81fe-c26168907fa2.png) shows the location of that button. 

     1. User click on the _"Advanced"_ button. The [number 3 in that mockup](https://cloud.githubusercontent.com/assets/119942/25784765/943354be-3327-11e7-8318-5f0914fb8ce3.png) shows the location of that button. 

     1. The _"Advanced stash configuration"_ overlay window opens. The [number 5 in that mockup](https://cloud.githubusercontent.com/assets/119942/25784787/2dc271dc-3328-11e7-9513-1ddaad25cb6b.png) shows the location of that window. Notice that by default there is no change to the location of the volume key file. In other words, this is the automated default location. In this example `/home/username/encfs/.EncFS-Volume-1/.encfs6.xml`. The [number 6 in that mockup](https://cloud.githubusercontent.com/assets/119942/25784787/2dc271dc-3328-11e7-9513-1ddaad25cb6b.png) shows default location.

     1. Still using the _"Advanced stash configuration"_ overlay window. User click on the radio button to activate an alternative location for the volume key file. The [number 7 in that mockup](https://cloud.githubusercontent.com/assets/119942/25785004/83eba332-332b-11e7-95f0-62bcd12f67d6.png) shows the location of that radio button. User click on the browse button. User is prompt with a new window to navigate to the alternative location for the volume key file. The [number 8 in that mockup](https://cloud.githubusercontent.com/assets/119942/25785004/83eba332-332b-11e7-95f0-62bcd12f67d6.png) shows the location of that browse button.

     1. User click on _"Close"_ button. Back to [that _"Create or import a stash"_ window](https://cloud.githubusercontent.com/assets/119942/25784757/5fab5d7c-3327-11e7-81fe-c26168907fa2.png), user click on _"Create"_ button. 

     1. Done. The new EncFS volume was created. And its key file was store into an alternative location. In this example a USB key. Which is physically separated from the actual encrypted data. Thus adding [2FA](https://en.wikipedia.org/wiki/Multi-factor_authentication). Which significantly increase security. The main benefits with all of the steps above are: 
         * User used exclusively the GUI
         * The user did not use Gnome Encfs Manager _"Advanced" ---> "encfs_config_file:"_ field
         * The user did not use Terminal/Console command line
         * For each EncFS volume user could optionally store its key file anywhere into an alternative location
         * No change to those alternative options. They are still available for software engineers or GUI advanced users.

        Of course the above is a suggested mockup & scenario. So feel really free to suggest another mockup(s) and scenario that could potentially better match [that User Story](#user-story) and [its Assumptions](#assumptions).

* Assumes EncFS volume could optionally benefit from stronger security. For example the key file could be store into a external USB key. Which adds a physical security. In other words, something similar to a [two-factor authentication (2FA)](https://en.wikipedia.org/wiki/Multi-factor_authentication). For example, during EncFS volume mount, if the key file is not accessible into the pre-set alternative location, the EncFS volume could _not_ be mounted.
* Assumes that feature could optionally be added to already created EncFS volumes or future volumes
* Assumes that feature could be activated manually per volume. So some EncFS volumes could use that feature, while other volumes would not.
* Assumes the EncFS each volume key file could store anywhere. Such as another storage, internal storage, external storage, USB key, network mount, DVD, CD, cloud, etc. For example, before the user mount the volume the key file needs to be accessible. For example the user would insert and mount an external USB key. After that the EncFS volume could be mounted. During EncFS volume mount, if the key file is _not_ accessible EncFS would prompt the user for the last known key file location.
* Assume the user would be able to do all of the above assumptions easily and quickly using a Graphical User Interface (GUI), _not_ the command line.

<a name="mockups"></a>
## [Mockups](#mockups)

![mockup---config---advanced---version-001](https://cloud.githubusercontent.com/assets/119942/25784757/5fab5d7c-3327-11e7-81fe-c26168907fa2.png)

![mockup---config---advanced---version-001](https://cloud.githubusercontent.com/assets/119942/25784765/943354be-3327-11e7-8318-5f0914fb8ce3.png)

![mockup---config---advanced---window---open---version-001](https://cloud.githubusercontent.com/assets/119942/25784787/2dc271dc-3328-11e7-9513-1ddaad25cb6b.png)

![mockup---config---advanced---window---alternative-location---version-001](https://cloud.githubusercontent.com/assets/119942/25785004/83eba332-332b-11e7-95f0-62bcd12f67d6.png)

<a name="options-to-consider"></a>
## [Options to consider](#options-to-consider)

The following are options to consider for that new feature
* **ENCFS6_CONFIG environment variable**. For example `export ENCFS6_CONFIG=/foo/bar/.encfs6.xml` 
     > By default, the config file is read from the encrypted directory. Using this option allows to store the config file separated from the encrypted files.
     * Documentation at https://github.com/rfjakob/encfs/blob/next/encfs/encfs.pod#environment-variables
     * Related comment at https://github.com/vgough/encfs/issues/48#issuecomment-69301831
* **eCryptfs** uses EncFS. eCryptfs is able to store key file in alternative location. Maybe some of eCryptfs code could be recycle for EncFS? 
     * Upstream code at https://launchpad.net/ecryptfs
     * Website at http://ecryptfs.org
* **Encryption Keystore (EK)** is a Perl script. Maybe some of its code could by recycle for EncFS? EK aimed at EncFS data stores.  
     > [With EK the] key store' (directory where 'key files' are stored) can be physically separated from the actual encrypted data (on USB sticks, or network mounts), making it more secure (two factor). Also fake 'key files' (name/password pairs) can be added, to the 'key store'. These fake keys can be made to decrypt other data, probably from the same location (interleaved data), or even be made to destroy the access to the real data, to further confuse would be attackers. It means you can give up a password to fake, or less important data, without comprising the real data, creating plausible deniability and prevent rubber hose attacks. Basically a key file could decrypt something else, or run any command!

     * Website at http://www.ict.griffith.edu.au/anthony/software/#ks
     * Perl script at http://www.ict.griffith.edu.au/anthony/software/ks.pl
* Any other options that could contribute to that new feature?

<a name="temporary-workaround"></a>
## [Temporary workaround](#temporary-workaround)

Until this new feature is implemented, if it does, for those interested to store their EncFS volume key file into an alternative location here are two options to choose from.

<a name="option-1"></a>
### [Option 1](#option-1)

Steps using [Gnome Encfs Manager](https://launchpad.net/gencfsm)
1. Unmount the Encfs volume
2. Select the appropriate volume. Click on "Configure the selected stash" button. It looks like a wrench.
4. Click on "Advanced..." button
5. Using "encfs_config_file:" field. Type in the absolute path to you new ".encfs6.xml" file location. For example: "/media/USERNAME/USB-KEY/EncFS/EncFS-Volume-1/.encfs6.xml" without the quotes.
6. Mount the volume. Done :)

Related to Gnome Encfs Manager
* Package for Debian, Fedora and openSUSE at http://software.opensuse.org/download.html?project=home:moritzmolch:gencfsm&package=gnome-encfs-manager
* Homepage at http://libertyzero.com/GEncfsM/ 
* Author's blog at http://www.moritzmolch.com/?s=Gnome+Encfs+Manager

<a name="option-2"></a>
### [Option 2](#option-2)
Simply creating a [Symbolic link (Symlink)](https://en.wikipedia.org/wiki/Symbolic_link) to each `.encfs6.xml` file. It's suggested to keep in mind that EncFS was not designed for that. This is a workaround. Before trying that it's suggested to backup your valuable data and expect the unexpected, LOL ;)

Steps using Debian 8 Jessie
1. If not already done, create a EncFS volume. Let's call it `EncFS-Volume-1`.
1. Unmount that EncFS volume
1. Using Nautilus, navigate to the EnCFS hidden volume `.encfs6.xml` file. For example, depending on your personal configuration that file could be located at `~home/encfs/EncFS-Volume-1/.ENC-HIDDEN-VOLUME`
Note: If you do not see that volume you might need to activate "Show hidden files" in Nautilus.
1. Cut that `.encfs6.xml` file
1. Paste that `.encfs6.xml` file to any alternative location to your liking. A physically different location. Such as an external USB key.
1. Using Nautilus, simply create a Symlink. For example:
   1. From your alternative location: `media/USERNAME/USB-KEY/EncFS/EncFS-Volume-1/.encfs6.xml`
   1. To: `~home/encfs/EncFS-Volume-1/.ENC-HIDDEN-VOLUME/.encfs6.xml` (Symlink)
1. Using EncFS, mount your EncFS volume
1. Using EncFS, unmount your EncFS volume. Unmount your USB key. Try to mount your EncFS volume again. As expected it will _not_ work because its key file is not accessible. Joy :) EncFS will return an error message. Insert and mount the USB key. Try to mount your EncFS volume again. It will mount. Done. Enjoy :)

**Comment by Francewhoa** [comment]
Related tickets: #48, #122, #188

**Comment by rfjakob** [comment]
Are you aware of the environment variable?

export ENCFS6_CONFIG=/foo/bar/.encfs6.xml

**Comment by Francewhoa** [comment]
Hi @rfjakob :) Thanks for your reply. Yes we're aware of that variable. It works well. But it does not meet the primary need of [that User Story](#user-story). Because to use that variable the user has to use the command line Terminal/Console. That User Story is about the user using the Graphical User Interface (GUI) exclusively. Maybe that User Story was not clear on that. Today I updated it accordingly.

To clarify [that User Story](#user-story) here is a suggested mockup and scenario with steps

1. Using EncFS GUI the user click on the _"Create or import a stash"_ button to create a new EncFS volume/stash. The [number 1 in that screenshot](https://cloud.githubusercontent.com/assets/119942/25784757/5fab5d7c-3327-11e7-81fe-c26168907fa2.png) shows the location of that button. 

1. User click on the _"Configure"_ button. The [number 2 in that screenshot](https://cloud.githubusercontent.com/assets/119942/25784757/5fab5d7c-3327-11e7-81fe-c26168907fa2.png) shows the location of that button. 

1. User click on the _"Advanced"_ button. The [number 3 in that mockup](https://cloud.githubusercontent.com/assets/119942/25784765/943354be-3327-11e7-8318-5f0914fb8ce3.png) shows the location of that button. 

1. The _"Advanced stash configuration"_ overlay window opens. The [number 5 in that mockup](https://cloud.githubusercontent.com/assets/119942/25784787/2dc271dc-3328-11e7-9513-1ddaad25cb6b.png) shows the location of that window. Notice that by default there is no change to the location of the volume key file. In other words, this is the automated default location. In this example `/home/username/encfs/.EncFS-Volume-1/.encfs6.xml`. The [number 6 in that mockup](https://cloud.githubusercontent.com/assets/119942/25784787/2dc271dc-3328-11e7-9513-1ddaad25cb6b.png) shows default location.

1. Still using the _"Advanced stash configuration"_ overlay window. User click on the radio button to activate an alternative location for the volume key file. The [number 7 in that mockup](https://cloud.githubusercontent.com/assets/119942/25785004/83eba332-332b-11e7-95f0-62bcd12f67d6.png) shows the location of that radio button. User click on the browse button. User is prompt with a new window to navigate to the alternative location for the volume key file. The [number 8 in that mockup](https://cloud.githubusercontent.com/assets/119942/25785004/83eba332-332b-11e7-95f0-62bcd12f67d6.png) shows the location of that browse button.

1. User click on _"Close"_ button. Back to [that _"Create or import a stash"_ window](https://cloud.githubusercontent.com/assets/119942/25784757/5fab5d7c-3327-11e7-81fe-c26168907fa2.png), user click on _"Create"_ button. 

1. Done. The new EncFS volume was created. And its key file was store into an alternative location. In this example a USB key. Which is physically separated from the actual encrypted data. Thus adding [2FA](https://en.wikipedia.org/wiki/Multi-factor_authentication). Which significantly increase security. The main benefits with all of the steps above are: 
   * User used exclusively the GUI
   * The user did not use Gnome Encfs Manager _"Advanced" ---> "encfs_config_file:"_ field
   * The user did not use Terminal/Console command line
   * For each EncFS volume user could optionally store its key file anywhere into an alternative location
   * No change to those alternative options. They are still available for software engineers or GUI advanced users.

The user click on the "Browse" button to navigate to any other location. The [number 5 in that mockup](mockup---config---advanced---version-001.png######) shows the location of that browser button.In this example `/home/username/encfs/.EncFS-Volume-1/.encfs6.xml`.


Of course the above is a suggested mockup & scenario. So feel really free to suggest another mockup(s) and scenario that could potentially better match [that User Story](#user-story) and [its Assumptions](#assumptions).

<a name="mockups"></a>
## [Mockups](#mockups)

![mockup---config---advanced---version-001](https://cloud.githubusercontent.com/assets/119942/25784757/5fab5d7c-3327-11e7-81fe-c26168907fa2.png)

![mockup---config---advanced---version-001](https://cloud.githubusercontent.com/assets/119942/25784765/943354be-3327-11e7-8318-5f0914fb8ce3.png)

![mockup---config---advanced---window---open---version-001](https://cloud.githubusercontent.com/assets/119942/25784787/2dc271dc-3328-11e7-9513-1ddaad25cb6b.png)

![mockup---config---advanced---window---alternative-location---version-001](https://cloud.githubusercontent.com/assets/119942/25785004/83eba332-332b-11e7-95f0-62bcd12f67d6.png)

**Comment by Francewhoa** [comment]
Hi all :) I'm not a developer, for this ticket my strength is Product Manager services. So I need help to understand the present scope of EncFS. Is EncFS a command line software only? Or both a command line and a GUI? If EncFS is a command line without GUI maybe that ticket would be more appropriate for another project? Such as [gnome-encfs-manager](https://launchpad.net/gencfsm). Which is focus on a GUI for EncFS.

**Comment by rfjakob** [comment]
Yes, EncFS is command line only. The GUI tools are independent projects. I'd recommend to create a ticket at gnome-encfs-manager!

**Comment by Francewhoa** [comment]
Thanks for your recommendation @rfjakob :) Done I created a ticket for _Gnome Encfs Manager_ at https://bugs.launchpad.net/gencfsm/+bug/1688988

Closing this ticket #324
