### ISSUE TITLE
can't mount when mount point is on nfs

### ISSUE THREAD

**Issue by michaelvanhorn** [vgough/encfs#325]
In trying to use encfs on RHEL 6.9, I have found that I can't have the mount point be on an nfs-mounted file system. For example, if /home/user is mounted via nfs, then

` encfs /home/user/encryptdir /home/user/decryptdir` 

fails with 

fusermount: failed to open mountpoint for reading: Permission denied
fuse failed.  Common problems:
 - fuse kernel module not installed (modprobe fuse)
 - invalid options -- see usage message

However, if I use /tmp (which is local to the machine), as in 

 `encfs /home/user/encryptdir /tmp/user/decryptdir`

then everything works as expected. The encrypted files are written just fine to the nfs filesystem.

encfs package version is 1.7.4-25.el6 from the epel repository. 
 
Has anyone else ever seen this behavior?

**Comment by rfjakob** [comment]
My guess is that the nfs server runs with root_squash an fusermount (suid binary) tries to open the directory as root

**Comment by michaelvanhorn** [comment]
I could see that as being a problem (I haven't been able to test it), but why would it try to open the decrypted as root, but not the encrypted directory?

**Comment by benrubson** [comment]
@michaelvanhorn did you manage to solve your "issue" ?

**Comment by michaelvanhorn** [comment]
No, the problem still exists. The user has just figured out a workflow that works around the problem.

**Comment by benrubson** [comment]
Did you try to update the nfs server with `no_root_squash` option ?

As `mount`, `fusermount` has the `suid` bit :
```
# ls -l /bin/mount /bin/fusermount 
-rwsr-xr-- 1 root fuse 30864 May 21  2015 /bin/fusermount
-rwsr-xr-x 1 root root 94776 Dec 11  2012 /bin/mount
```

**Comment by michaelvanhorn** [comment]
No, because it’s a production environment and we have that for security.

I want to try adding that on just one particular partition, but I haven’t had a chance to test it out.

---
Mike VanHorn
Senior Computer Systems Administrator
College of Engineering and Computer Science
Wright State University
265 Russ Engineering Center
937-775-5157
michael.vanhorn@wright.edu

On 6/12/17, 10:10 AM, "Ben RUBSON" <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you try to update the nfs server with no_root_squash option ?

**Comment by benrubson** [comment]
As I'm not sure that with `root_squash` you'll find a solution, what about the following workaround ?
```
encfs /home/user/encryptdir /tmp/user/decryptdir
ln -s /tmp/user/decryptdir /home/user/decryptdir
```

**Comment by samrocketman** [comment]
Possibly related -> https://unix.stackexchange.com/questions/102617/having-trouble-exporting-fuse-via-nfs

**Comment by michaelvanhorn** [comment]
Yes, that is the workaround we are using.

---
Mike VanHorn
Senior Computer Systems Administrator
College of Engineering and Computer Science
Wright State University
265 Russ Engineering Center
937-775-5157
michael.vanhorn@wright.edu

On 7/3/17, 6:08 AM, "Ben RUBSON" <notifications@github.com<mailto:notifications@github.com>> wrote:


As I'm not sure that with root_squash you'll find a solution, what about the following workaround ?

encfs /home/user/encryptdir /tmp/user/decryptdir

ln -s /tmp/user/decryptdir /home/user/decryptdir

**Comment by samrocketman** [comment]
Closing since this appears to be a problem with FUSE+NFS and not something EncFS can control directly.  I recommend checking if an issue is already filed with FUSE and, if not, file one.

If you think this shouldn't be closed then please elaborate.
