### ISSUE TITLE
What OS's are desirable for testing?

### ISSUE THREAD

**Issue by samrocketman** [vgough/encfs#326]
It's nice to have a Travis CI build.  But I gather from comments in different places that it's desirable to support different variations of Linux.

What Linux operating systems are desirable to test building EncFS?  I ask because I can add support to build EncFS on multiple Linux OS's through Travis CI.

**Comment by rfjakob** [comment]
That's possible? Nice! How many variants are there? Let's test all of them?

**Comment by samrocketman** [comment]
Well, I meant distributions.  So far, what I think are important is:

* Debian Jessie
* CentOS 7
* Ubuntu 16.04

[Here's an example](https://github.com/samrocketman/encfs/tree/platforms/tests/molecule) of building and verifying across Debian and Ubuntu.  This follows conventions of [how I manage GIMP infrastructure](https://github.com/gimp-ci/documentation/blob/master/creating-ansible-roles.md) but with just test building EncFS.

**Comment by samrocketman** [comment]
Are there any others that should be test built each time?

**Comment by samrocketman** [comment]
Perhaps https://hub.docker.com/_/opensuse/

**Comment by benrubson** [comment]
Do you have FreeBSD available ?

**Comment by samrocketman** [comment]
Unfortunately, containers run inside of the Linux kernel.  Linux can't run FreeBSD binaries.

To run FreeBSD one could use the vagrant driver (with VirtualBox) but [Travis CI does not support running VirtualBox](https://github.com/travis-ci/travis-ci/issues/6060).  I can still integrate VirtualBox so that FreeBSD is run locally.  How does that sound?

**Comment by benrubson** [comment]
Well, perhaps you could start with Linux distributions only, integrating VirtualBox to run FreeBSD seems to be a little bit "complicated" design.
But as I understand, and according to what I found, Travis does not support FreeBSD so that the only solutions are QEMU, VirtualBox...
Note that for the moment there is still an issue to correct in FreeBSD Fuse (#315), EncFS build will be OK but one of the reverse tests will fail.

**Comment by Aikhjarto** [comment]
@samrocketman 
> Edit: tried and failed at openSUSE

Build definitely works on openSUSE https://build.opensuse.org/package/show/security/encfs
Test, however, fails due Perl-Test-More missing on openSUSE.

**Comment by samrocketman** [comment]
Thanks for letting me know @Aikhjarto.

**Comment by asomers** [comment]
Cirrus CI now supports FreeBSD builds.  For an example, see https://github.com/freebsd/pkg/blob/master/.cirrus.yml .  See docs here: https://cirrus-ci.org/guide/quick-start/ .

**Comment by benrubson** [comment]
Good news good tip, thank you Alan 👍

**Comment by benrubson** [comment]
I added FreeBSD in https://github.com/vgough/encfs/pull/580.
I'll perhaps work on a Cygwin CI, interesting as EncFS now correctly builds and works with it.

_Closing this for now..._
