### ISSUE TITLE
Increase FUSE_USE_VERSION ?

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#328]
Hi,

Is there any reason to keep `FUSE_USE_VERSION` to `26` ?
https://github.com/vgough/encfs/blob/v1.9.1/CMakeLists.txt#L61

What about increasing it to last 2.x series, `29` ?
Any benefits ? Any drawbacks ?

(_Debian Jessie has libfuse 2.9_)

Many thx 👍 

Ben

**Comment by l29ah** [comment]
Drawback: the users of the old libfuse won't be able to use it.

**Comment by benrubson** [comment]
Thnak you for your feedback Sergey 👍 
Even Debian Wheezy (oldoldstable, may 2013) has libfuse 2.9.
But perhaps you personally use an older version or think about systems having it ?
Thank you !

**Comment by benrubson** [comment]
@vgough, any thoughts ?
Thx 👍

**Comment by vgough** [comment]
Linux isn't a problem, we could probably bump significantly.  I'm more worried about non-Linux FUSE implementations.  Digging into OSXFuse, it looks like it uses 26 API: https://github.com/osxfuse/fuse/blob/master/include/fuse.h#L22

If the benefits are big enough, we could probably make encfs work with either 26 or later APIs.  I don't really know what the benefits are.

**Comment by benrubson** [comment]
I'm not sure either what are the benefits, perhaps we should ask libfuse guys.
I did not notice OSXFuse was stuck to 26 API.
Of course Linux has 2.9 since a long time, FreeBSD too.

**Comment by benrubson** [comment]
Here's at least the changelog :

```
What is new in 2.9

 - Add "zero copy" support for kernel 2.6.35 or newer

 - Make maximum background requests tunable on kernel 2.6.32 or newer

 - Require --no-canonicalize in (u)mount (util-linux version 2.18 or
   newer) to fix security problems with fusermount

 - Use dynamically sized hash tables in high level library

 - Memory use of filesystem daemon can shrink more easily

 - Add "auto_unmount" option

 - Add "remember" option

 - Add man pages for fusermount, mount.fuse and ulockmgr_server

 - API changes:

    o Introduce "store" and "retrieve" for accessing kernel buffers on
      kernel 2.6.36 or newer

    o Introduce abstract buffer for zero copy operations

    o Allow path calculation to be omitted on certain operations

    o Allow batching forget requests

    o Add "flock" method

    o Add support for ioctl on directories

    o Add delete notification

    o Add fallocate operation (linux kernel 3.5 or newer)

 - Bug fixes and small improvements

============================================================================

What is new in 2.8

 - More scalable directory tree locking

 - Atomic open(O_TRUNC) support

 - Support big write requests on kernels 2.6.26 and newer

 - Out-of-tree fuse module removed

 - Better NFS exporting support

 - New ioctl and poll requests

 - New CUSE (Character Device in Userspace) interface

 - Allow umask processing in userspace

 - Added cache invalidation notifications

 - Bugfixes and small improvements

============================================================================

What is new in 2.7

 - Stacking support for the high level API

 - Add filename charset conversion module

 - Improved mounting
```

**Comment by Nikratio** [comment]
libfuse upstream here. Just bumping FUSE_USE_VERSION isn't going to give you any benefits. Most likely, it's going to give you a compile error, actually, because you also need to change your code to correspond to the newer API. Once you have done that, you could also start taking advantage of some of the newer features. How important that is really depends on your application.

OSXFUSE supports FUSE_USE_API up to 29, it just defaults to 26. FreeBSD uses libfuse, so it will always be up-to-date.

The really interesting new features (writeback cache, readdirplus, ..) only become available when you transition to libfuse 3.x. But this means you need a lot of #ifdefs until OSXFUSE catches up.

**Comment by benrubson** [comment]
Thank you very much @Nikratio for your feedback, much appreciated !

The FUSE calls we use are both in 26 and 29, and a quick first test did not return compilation errors.
According to the changelog, there are some bug fixes and improvements between these 2 versions.
Would we benefit from these bug fixes bumping up to 29 ? Or are they also backported to lower versions (so to 26 for example) ?

Thank you again Nikolaus !

**Comment by Nikratio** [comment]
I have not checked in detail, but I would be surprised if bumping just FUSE_USE_VERSION would make any difference at all.

**Comment by benrubson** [comment]
OK, thank you again Nikolaus for your feedback !
