### ISSUE TITLE
Is EncFS FIPS 140-2 complaint?

### ISSUE THREAD

**Issue by arun-c-g** [vgough/encfs#349]
Is EncFS FIPS 140-2 complaint?  Will it use FIPS_mode_set during runtime ?

regards
cg

**Comment by samrocketman** [comment]
Disclaimer: I am neither an EncFS developer nor am I qualified to determine compliance with US government standards.

I don't know if EncFS has ever been certified for FIPS.  After briefly, reading FIPS 140-2 it appears to primarily deal with hardware encryption modules and different security levels around physical protection (like tampering).  As far as I know, EncFS is only software.

There are also security issues disclosed in a security audit.  Some _may_ have been addressed but there's no formal follow up on the audit.  Ref: https://defuse.ca/audits/encfs.htm

**Comment by arun-c-g** [comment]
Is there any config in EncFS which allows me:-
(a) To specify to use fips mode Openssl ?
or 
(b) To specify the ciphers that are to be used?

regards,
cg

**Comment by rfjakob** [comment]
Everything that can be configured is listed in the man page at:
https://github.com/vgough/encfs/blob/master/encfs/encfs.pod

**Comment by benrubson** [comment]
@arun-c-g did you find info you need ? Thx 👍

**Comment by benrubson** [comment]
Feel free to re-open this ticket if needed 👍
