### ISSUE TITLE
Creation of new directory not working on translated version

### ISSUE THREAD

**Issue by plafl** [vgough/encfs#353]
I'm running version encfs 1.8.1 using Ubuntu 16.04.

Since I'm spanish running encfs to create a new directory in my system prompts:

`El directorio "/home/plf/.projects/" no existe. ¿Debería ser creado? (S,N)`

Which translated is something like:

`Folder  "/home/plf/.projects/" does not exist. Should it be created? (Y,N)?`

Notice that the spanish translation expects `S`or `N` for an answer. If I answer `S` (yes) then it gives me the equivalent error for `Unable to locate root directory`. After looking at issue #264 I thought of instead of answering `S` let's answer in english `Y`, which surprisingly solved the problem. So it seems that although the questions are translated the expected answers are hardcoded to the english versions.

**Comment by benrubson** [comment]
This issue has been corrected by #302 which is in EncFS 1.9.2 👍

**Comment by plafl** [comment]
Ah, OK, thanks! :+1: 
I close the issue then.
