### ISSUE TITLE
.asc signature file missing for the latest stable source

### ISSUE THREAD

**Issue by svetlemodry** [vgough/encfs#354]
Hi all!
I would like to be able to verify the source code tarball with gpg for the community Arch Linux package. For that the appropriate .asc signature file would be needed. Currently the github page states, that the release is verified, but I know of no way how to check the source tarball with gpg myself without the .asc file. Those have been provided with the earlier releases. Any chance to provide the .asc file for the latest stable release too?
Thank you!

**Comment by rfjakob** [comment]
Done: https://github.com/vgough/encfs/releases/tag/v1.9.2

Signed with my "gocryptfs signing key", key ID 23A02740, https://nuetzlich.net/gocryptfs-signing-key.pub

**Comment by svetlemodry** [comment]
Awesome, thank you!
