### ISSUE TITLE
Build tests fail on the latest stable release

### ISSUE THREAD

**Issue by svetlemodry** [vgough/encfs#358]
Hi!
The `make test` command fails with the below output on the latest stable source.

`==> Starting check()...`
`Running tests...`
`Test project /build/encfs/src/build`
`    Start 1: checkops`
`1/2 Test #1: checkops .........................   Passed    0.09 sec`
`    Start 2: scriptedtests`
`2/2 Test #2: scriptedtests ....................***Failed    0.14 sec`
`50% tests passed, 1 tests failed out of 2`
`Total Test time (real) =   0.24 sec`
`The following tests FAILED:`
`	  2 - scriptedtests (Failed)`
`Errors while running CTest`

**Comment by rfjakob** [comment]
Ok can you run

    ./test.sh

this runs the same tests but gives us more output.
