### ISSUE TITLE
pwrite could return 0 and set errno

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#392]
Just not to forget the reviews in #391.

Thx 👍 

Ben

**Comment by vgough** [comment]
From pwrite man page:
```
       On error, -1 is returned and errno is set to indicate the cause of the error.
```

**Comment by benrubson** [comment]
I found some discussions where old implementations of `pwrite` were said to be able to return 0.
But then they were certainly not POSIX compliant...
You're right, not sure we should care about them...
