### ISSUE TITLE
Recommend adding Ben Rubson as a maintainer

### ISSUE THREAD

**Issue by samrocketman** [vgough/encfs#394]
cc @vgough @rfjakob 

Hey guys, @benrubson has made a lot of great contributions for PRs and regularly reaches out to me about issues which need to be closed.  For example, he's emailed me about closing the following issues:

- https://github.com/vgough/encfs/issues/358
- https://github.com/vgough/encfs/issues/341
- https://github.com/vgough/encfs/issues/325
- https://github.com/vgough/encfs/issues/277
- https://github.com/vgough/encfs/issues/126
- https://github.com/vgough/encfs/issues/169
- https://github.com/vgough/encfs/issues/259
- https://github.com/vgough/encfs/issues/286
- https://github.com/vgough/encfs/issues/288
- https://github.com/vgough/encfs/issues/249
- https://github.com/vgough/encfs/issues/238
- https://github.com/vgough/encfs/issues/325
- https://github.com/vgough/encfs/issues/277
- https://github.com/vgough/encfs/issues/255
- https://github.com/vgough/encfs/issues/237
- https://github.com/vgough/encfs/issues/231
- https://github.com/vgough/encfs/issues/194
- https://github.com/vgough/encfs/issues/70

As a result, many of those issues were indeed closed to help clean up our issue queue.  He's additionally [proposed 40 pull requests](https://github.com/vgough/encfs/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Abenrubson) to improve EncFS; [18 of which were merged](https://github.com/vgough/encfs/pulls?utf8=%E2%9C%93&q=is%3Amerged%20is%3Apr%20author%3Abenrubson).

I feel he's proven himself reliable enough to be promoted to a maintainer.  Of course, regular code review and discussion should still happen on pull requests but I would like to not be his barrier of productivity.  What are your thoughts?

**Comment by vgough** [comment]
Thanks, done.

**Comment by benrubson** [comment]
Many thanks for this proposal, and thank you all for your trust 👍

**Comment by samrocketman** [comment]
🎉
