### ISSUE TITLE
File holes improvement

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#399]
Hi,

Here is an idea to improve file holes.
When writing blocks full of 0, we could simply avoid encoding them, so that zeros are then written to storage.
EncFS already knows how to correctly read these 0 blocks them thanks to its _file holes_ feature.

Some storage FS, such as ZFS, have built-in compression (ZLE for example) and would then benefit from this.

I had a look to the source code, rather simple to implement.
Not sure however about security concerns.

Ben

**Comment by rfjakob** [comment]
From a security perspective, this could be problematic. The users may actually want a random ciphertext blob when they execute

    dd if=/dev/zero of=solidblob bs=1M count=100

On the other hand, if users want zero-blocks in the ciphertext, they can (this will create a sparse file):

    truncate -s 104857600 sparseblob

What you currently cannot do is to preallocate the disk space AND have zero-blocks. This can be done with `fallocate`, and gocryptfs actually has it implemented like this.

**Comment by benrubson** [comment]
> From a security perspective, this could be problematic. The users may actually want a random ciphertext blob...

Yes this could be proposed through an option (or extending current `file holes` feature ?).
Appart from the fact that we may know the file contains some 0, are there other security concerns ?

Goal is not only to preallocate a file, some applications may write bunches of 0 in their files.
Underlying FS may then benefit from directly dealing with these 0.

**Comment by rfjakob** [comment]
> Appart from the fact that we may know the file contains some 0, do you think there other security concerns ?

That's it, I guess. Depending on what the users store, this can be a big problem, or no problem at all. Anyway, we did not leak this information till now - so I think this has to be explicitely enabled.

**Comment by benrubson** [comment]
Closing this for now, there are more important things to deal with before 👍
