### ISSUE TITLE
encfs doesn't compile with musl libc

### ISSUE THREAD

**Issue by ScrumpyJack** [vgough/encfs#40]
g++ -DHAVE_CONFIG_H -I. -I..  -I../intl  -Os -fomit-frame-pointer  -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D__STDC_FORMAT_MACROS -DRLOG_COMPONENT="encfs" -I/usr/include   -W -Wall -Wpointer-ar
ith -Wwrite-strings -Os -fomit-frame-pointer   -MT encfsctl.o -MD -MP -MF .deps/encfsctl.Tpo -c -o encfsctl.o encfsctl.cpp
encfsctl.cpp:298:29: warning: unused parameter 'argc' [-Wunused-parameter]
 static int cmd_showKey( int argc, char **argv )
                             ^
encfsctl.cpp: In function 'int cmd_decode(int, char**)':
encfsctl.cpp:331:18: error: 'PATH_MAX' was not declared in this scope
         char buf[PATH_MAX+1];
                  ^
encfsctl.cpp:332:27: error: 'buf' was not declared in this scope
         while(cin.getline(buf,PATH_MAX))
                           ^
encfsctl.cpp: In function 'int cmd_encode(int, char**)':
encfsctl.cpp:355:18: error: 'PATH_MAX' was not declared in this scope
         char buf[PATH_MAX+1];
                  ^
encfsctl.cpp:356:27: error: 'buf' was not declared in this scope
         while(cin.getline(buf,PATH_MAX))
                           ^
encfsctl.cpp: In function 'int copyContents(const boost::shared_ptr<EncFS_Root>&, const char*, const char*)':
encfsctl.cpp:517:31: error: 'PATH_MAX' was not declared in this scope
             char linkContents[PATH_MAX+2];
                               ^
encfsctl.cpp:519:37: error: 'linkContents' was not declared in this scope
             if(readlink (d.c_str(), linkContents, PATH_MAX + 1) <= 0)
                                     ^
encfsctl.cpp:524:47: error: 'linkContents' was not declared in this scope
             symlink(rootInfo->root->plainPath(linkContents).c_str(), 
                                               ^
encfsctl.cpp: In function 'int cmd_showcruft(int, char**)':
encfsctl.cpp:691:13: error: 'ngettext' was not declared in this scope
   filesFound), filesFound) << "\n";
             ^
Makefile:636: recipe for target 'encfsctl.o' failed
make[2]: *** [encfsctl.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by ScrumpyJack** [comment]
can we have a configure script so that we don't depend on autoreconf?
also, it would be great to have a release number in the download file so that we can check versions. at the moment the changelog doesn't have versions. I have master.zip so i *think* i've got 1.8rc1, but i can't tell.

**Comment by pepa65** [comment]
Agree about a configure script, it would be very helpful. For instance, I'm building on Ubuntu, and luckily I can refer to the wiki page on how to build, but I haven't memorized it.

Version in every release would be great.

**Comment by rfjakob** [comment]
@ScrumpyJack: Is that good enough w.r.t. versioning? https://github.com/vgough/encfs/archive/v1.8-rc1.tar.gz Tagged releases are always available like that at https://github.com/vgough/encfs/releases .

@pepa65: Yes, we lack documentation of how to build at the moment. I will write an INSTALL.md file for 1.8. In the meantime: We are doing automated Travis build tests, so the Travis configuration files always contains up-to-date build instructions: https://github.com/vgough/encfs/blob/master/.travis.yml

**Comment by rfjakob** [comment]
@ScrumpyJack: The first line in `configure.ac` contains the version:

    AC_INIT([encfs], [1.8-rc2])

However, in 1.8-rc1, this was not updated and still says `1.7.5`. It is fixed in encfs-next ( https://github.com/rfjakob/encfs ) and will be released in 1.8-rc2.

**Comment by ScrumpyJack** [comment]
yes, i'll use archive for versioning, thanks for the tip.
I'll wait for version 1.8rc2 before building if it contains a configure script.

**Comment by rfjakob** [comment]
Hehe, I'm not sure about that. The configure script is 22000 lines of autogenerated ugliness, I don't think we want it checked it. Instead, I have posted it here: https://gist.github.com/anonymous/9de6af3bb1555fe944d5

**Comment by ScrumpyJack** [comment]
how did configure get in there? http://encfs.googlecode.com/files/encfs-1.7.4.tgz

**Comment by ScrumpyJack** [comment]
can you join #encfs on freenode

**Comment by rfjakob** [comment]
Yes, 22:00 CET?

**Comment by ScrumpyJack** [comment]
still not able to

**Comment by rfjakob** [comment]
What's the error it fails with now?

**Comment by ScrumpyJack** [comment]
it works now! probably an environment variable
