### ISSUE TITLE
Regenerate 1.9.2 tarball

### ISSUE THREAD

**Issue by vaygr** [vgough/encfs#402]
**1.9.1** was only 445K big, but because of `ci` and cmake tarball with x86_64 binaries in it, **1.9.2** is now over 10 megs.

**Comment by rfjakob** [comment]
I also noticed that, but unfortunately only after I have released v1.9.2. I have removed the cmake blob in
https://github.com/vgough/encfs/commit/6ed2001c2e7682ef5e968b8f165c927c535f2d77 , and v1.9.3 will be smaller again.

**Comment by rfjakob** [comment]
Sorry for the inconvenience, but v1.9.2 is already released and cannot be changed.

**Comment by samrocketman** [comment]
I agree.  If it needs to be fixed then bump the version.
