### ISSUE TITLE
Documentation: Small fixes for install documentation

### ISSUE THREAD

**Issue by joseba4242** [vgough/encfs#413]
A few very minor points on the installation documentation

INSTALL.md should add a "cd build" after ./build.sh so that the subsequent makes work

wiki/Installing-Encfs should also install package "attr" as otherwise make test fails (was needed on a Debian jessie here)

I'd suggest to remove the "Compile, test and install" instructions from wiki/Installing-Encfs as they are already in INSTALL.md but not the same (eg test isn't mentioned in the wiki)

"make integration" doesn't exist although suggested in INSTALL.md

**Comment by benrubson** [comment]
Thank you @joseba4242 for this !

`INSTALL.md` has changed with last commits to master.
Best is then to refer to the right version, I added this into the wiki.

I also added the `attr` package to the list, you're right, thank you !

Feel free if you have any other comment 👍
