### ISSUE TITLE
Configuration fails if CXXFLAGS set

### ISSUE THREAD

**Issue by mouse07410** [vgough/encfs#420]
MacOS Siera 10.12.6, Xcode-9.0, ton of packages installed via Macports into `/opt/local` - including `OpenSSL-1.0.2l` and `gnuregex-0.12.2`.

Problems:

1. Build process does not figure to look for installed packages in `/opt/local`.
2. Build process fails to find `gnuregex` installed by Macports in `/opt/local`.
3. Build process stitches compiler flags from CXXFLAGS and whatever CMake cares to add using ";", ending up with:

```
. . . . .
Building CXX object CMakeFiles/cmTC_f7efa.dir/src.cxx.o
/opt/local/bin/clang++    -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4.2 -mtune=native -Os -Ofast -std=c++11;-Wall -Wextra -DHAVE_CXX_FLAG_COVERAGE  --coverage   --coverage -o CMakeFiles/cmTC_f7efa.dir/src.cxx.o -c /Users/uri/src/encfs/build/CMakeFiles/CMakeTmp/src.cxx
clang: error: no input files
/bin/sh: -Wall: command not found
```

Would be great to have this resolved.

**Update**
This is the ugly hack I had to apply to make it working (but once applied - all the tests passed ;).
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8ae405e4..a23caeec 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -37,17 +37,18 @@ if (${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} GREATER 3.0)
 else ()
   if (CMAKE_COMPILER_IS_GNUCXX)
     message ("** Assuming that GNU CXX uses -std=c++11 flag for C++11 compatibility.")
-    list(APPEND CMAKE_CXX_FLAGS "-std=c++11")
+    list(APPEND CMAKE_CXX_FLAGS " -std=c++11 ")
   elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
     message ("** Assuming that Clang uses -std=c++11 flag for C++11 compatibility.")
-    list(APPEND CMAKE_CXX_FLAGS "-std=c++11")
+    list(APPEND CMAKE_CXX_FLAGS " -std=c++11 ")
   else()
     message ("** No CMAKE C++11 check. If the build breaks, you're on your own.")
   endif()
 endif ()
 
 # Let's enable some compilation warnings
-list(APPEND CMAKE_CXX_FLAGS "-Wall -Wextra")
+#list(APPEND CMAKE_CXX_FLAGS " -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4.2 -mtune=native -Os -Ofast -std=c++11 ")
+set(CMAKE_CXX_FLAGS " ${CMAKE_CXX_FLAGS} -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4.2 -mtune=native -Os -Ofast -std=c++11 ")
 
 add_definitions( -DPACKAGE="encfs" )
 
diff --git a/vendor/github.com/google/benchmark/CMakeLists.txt b/vendor/github.com/google/benchmark/CMakeLists.txt
index 4265a6c2..465e5784 100644
--- a/vendor/github.com/google/benchmark/CMakeLists.txt
+++ b/vendor/github.com/google/benchmark/CMakeLists.txt
@@ -74,7 +74,7 @@ if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
 else()
   # Try and enable C++11. Don't use C++14 because it doesn't work in some
   # configurations.
-  add_cxx_compiler_flag(-std=c++11)
+  add_cxx_compiler_flag(" -std=c++11 ")
   if (NOT HAVE_CXX_FLAG_STD_CXX11)
     add_cxx_compiler_flag(-std=c++0x)
   endif()
@@ -188,7 +189,7 @@ cxx_feature_check(STEADY_CLOCK)
 find_package(Threads REQUIRED)
 
 # Set up directories
-include_directories(${PROJECT_SOURCE_DIR}/include)
+include_directories(${PROJECT_SOURCE_DIR}/include /opt/local/include)
 
 # Build the targets
 add_subdirectory(src)
```

Probably not all of the above are necessary - I suspect the key offender is `list(APPEND blah-blah)` in the main `CMakeLists.txt`.

**Comment by benrubson** [comment]
Could you please test master branch @mouse07410 and tell us ?
You should still see some compilation warnings (which will be solved), but at least you should not have to modify `CMakeLists.txt` to successfully compile & test.
Thx 👍

**Comment by mouse07410** [comment]
I am running on the master branch. On one macOS Sierra 10.12.6 it builds and works fine. On another Sierra machine it fails with: 
```
. . . . .
[ 92%] Building CXX object CMakeFiles/encfs-bin.dir/encfs/main.cpp.o
[ 94%] Building CXX object CMakeFiles/encfsctl.dir/encfs/encfsctl.cpp.o
[ 94%] Linking CXX executable encfsctl
/usr/bin/ld: cannot find -ltinyxml2
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [encfsctl] Error 1
make[1]: *** [CMakeFiles/encfsctl.dir/all] Error 2
```
Apparently `TinyXML2` doesn't get built in some cases for some reason...

I see the same failure on Travis CI: https://travis-ci.org/mouse07410/encfs/jobs/286825348

**Comment by benrubson** [comment]
You changed `set(TINYXML_LIBRARIES tinyxml2_static)` to `set(TINYXML_LIBRARIES tinyxml2)` in your `CMakeLists.txt`, certainly the reason why it fails ?

Thank you for telling us `CXXFLAGS` are no more an issue 👍

**Comment by mouse07410** [comment]
> You changed `set(TINYXML_LIBRARIES tinyxml2_static)` to `set(TINYXML_LIBRARIES tinyxml2)` in your `CMakeLists.txt`, certainly the reason why it fails ?

Thanks for pointing that one. But certainly not the only reason. Messing up with linker flags definitely contributed:
```
. . . . .
CMake Error at CMakeLists.txt:249 (add_library):
  Target "encfs" links to item "-Wl,--as-needed " which has leading or
  trailing whitespace.  This is now an error according to policy CMP0004.
```

Why do we need "-Wl,--as-needed"?

**Comment by mouse07410** [comment]
> The following line from yours is buggy...

Correct. 

But wasn't it's purpose accommodating for *other* linker flags in addition to `-Wl,--as-needed`? If so, how is that taken care of?

**Comment by benrubson** [comment]
No, `EXTRA_LINKER_FLAGS` is not used elsewhere, it's an internal var, this is why `CMakeLists.txt` enforces it to the required value in order to avoid the `CMP0004` issue.

**Comment by mouse07410** [comment]
Ah, I see. Thanks!
