### ISSUE TITLE
Solve clang-tidy warnings

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#427]
See [Travis CI log](https://travis-ci.org/vgough/encfs/branches) on master branch, the clang build, to list clang-tidy warnings to correct.

**Comment by benrubson** [comment]
The following :
```
autosprintf.cpp:38:14: warning: do not define a C-style variadic function; consider using a function parameter pack or currying instead [cert-dcl50-cpp]
autosprintf::autosprintf(const char *format, ...) {
 ^
```
Leads to :
https://www.securecoding.cert.org/confluence/display/cplusplus/DCL50-CPP.+Do+not+define+a+C-style+variadic+function

And I then found several implementations :
https://gist.github.com/sehe/3374327
https://github.com/tromey/typesafe-printf
https://github.com/fmtlib/fmt

@vgough what do you think about this ?
Would you be OK to implement a solution to fix this warning ?
(I tried but I'm stuck somewhere trying to match the old constructor with the first method above...)
Many thx 👍

**Comment by benrubson** [comment]
May I ask some help to correctly solve the following warnings ?
@rfjakob, would you please handle them ?
Will make the build log even more clean.
Thank you very much 👍 
```
/home/travis/build/vgough/encfs/encfs/DirNode.cpp:133:7: warning: class 'RenameOp' defines a destructor and a copy constructor but does not define a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
class RenameOp {
      ^
/home/travis/build/vgough/encfs/encfs/NullCipher.cpp:50:7: warning: class 'NullKey' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
class NullKey : public AbstractCipherKey {
      ^
/home/travis/build/vgough/encfs/encfs/NullCipher.cpp:56:7: warning: class 'NullDestructor' defines a destructor, a copy constructor and a copy assignment operator but does not define a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
class NullDestructor {
      ^
/home/travis/build/vgough/encfs/encfs/SSL_Cipher.cpp:277:7: warning: class 'SSLKey' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
class SSLKey : public AbstractCipherKey {
      ^
/home/travis/build/vgough/encfs/encfs/XmlReader.cpp:165:7: warning: class 'XmlNode' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
class XmlNode : virtual public XmlValue {
      ^
```

**Comment by benrubson** [comment]
OK, so just one Clang-tidy warning remaining, the tiny one above.
Any thoughts perhaps @vgough ?
We could simply disable this warning class, but perhaps it's simple and worth making the required definitions, as a best practice ?

**Comment by benrubson** [comment]
Link to the rule :
http://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-special-member-functions.html

**Comment by benrubson** [comment]
Your thoughts regarding this last Clang warning @rfjakob, when U'll have some time ?
We are not so far from the final goal 👍 
Many thanks 👍

**Comment by benrubson** [comment]
OK, last thing to solve before we could I think release [1.9.3](https://github.com/vgough/encfs/milestone/2).
Thx for your help 👍

**Comment by rfjakob** [comment]
I'll take a look at this.

**Comment by benrubson** [comment]
Many thanks @rfjakob 👍

**Comment by rfjakob** [comment]
How about undefining the other operations? Like, for RenameOp
```diff
diff --git a/encfs/DirNode.cpp b/encfs/DirNode.cpp
index 2c6271b..7bb6a32 100644
--- a/encfs/DirNode.cpp
+++ b/encfs/DirNode.cpp
@@ -142,10 +142,16 @@ class RenameOp {
     last = renameList->begin();
   }
 
+  // copy contructor
   RenameOp(const RenameOp &src) = default;
 
+  // destructor, defined below
   ~RenameOp();
 
+  RenameOp(RenameOp&& other) = delete; // move constructor
+  RenameOp& operator=(const RenameOp& other) = delete; // copy assignment
+  RenameOp& operator=(RenameOp&& other) = delete ;// move assignment
+
   explicit operator bool() const { return renameList != nullptr; }
 
   bool apply();
```
Compiles + tests fine. Undefining used operations would result in a compile error I guess, so this would be safe?

**Comment by benrubson** [comment]
> Undefining used operations would result in a compile error I guess

I also guess, but I'm not sure at all. Perhaps @vgough could tell us ?
Or what about the following test, adding a dummy code operation with a deleted operator, and see if compilation fails ?

**Comment by benrubson** [comment]
Did you finally found a solution ?
Thank you 👍

**Comment by benrubson** [comment]
Hi @rfjakob, did you manage to make progress on this ?
Many thx 👍

**Comment by vgough** [comment]
Seems reasonable to me.  I'd also be fine with disabling that lint check.

**Comment by benrubson** [comment]
OK, thank you @vgough.
Let's then go with Jakob's idea 👍 
@rfjakob, would you push your work to a new PR ?
Many thx !

**Comment by rfjakob** [comment]
Sorry, the copy-pasted diff above is all I have

**Comment by benrubson** [comment]
OK, I then just have pushed a change in #458 based on your idea 👍
