### ISSUE TITLE
How to auto mount dir on centos7 using systemd

### ISSUE THREAD

**Issue by MadhuSudhanCS** [vgough/encfs#437]
Hi,

I am trying to auto mount the encrypted dir using systemd service.
I get the below error during start up
```
Oct 26 04:16:06 localhost.localdomain encfs[958]: DEBUG op: getattr error: No such file or directory [encfs.cpp:171]
Oct 26 04:16:06 localhost.localdomain encfs[958]: DEBUG getAttr error on /usr/.local/jGefqJaE2jAQLVa1MZYFZHBV/MvsJ1E5fjh8U4R3cR5PUx2MC/rGqqZeFtmWctlcKAMMcDsZMc/twxQiCCX1NldXyJl5uwsw6Xj: No such file or directory [RawFileIO.cpp:167]
Oct 26 04:16:06 localhost.localdomain encfs[958]: DEBUG getAttr error on /usr/.local/jGefqJaE2jAQLVa1MZYFZHBV/MvsJ1E5fjh8U4R3cR5PUx2MC/rGqqZeFtmWctlcKAMMcDsZMc/twxQiCCX1NldXyJl5uwsw6Xj: No such file or directory [RawFileIO.cpp:167]
Oct 26 04:16:06 localhost.localdomain encfs[958]: DEBUG op: getattr error: No such file or directory [encfs.cpp:171]
Oct 26 04:16:07 localhost.localdomain encfs-mount[654]: VER cipher key size = 52 [FileUtils.cpp:1596]
```

If I rerun the service manually after system comes up, service starts properly.

I have added these lines to make sure service starts after these services
```
After=local-fs.target
After=sys-fs-fuse-connections.mount
Before=display-manager.service getty@tty1.service
```

Can any one help me in adding proper dependencies so that service starts during boot.

Regards,
--Madhu C S

**Comment by Vascom** [comment]
Can you show full content of your service file (except password)?

**Comment by MadhuSudhanCS** [comment]
Service File

```
[Unit]
Description=Mount EncFS
DefaultDependencies=no
After=local-fs.target
After=sys-fs-fuse-connections.mount
Before=display-manager.service getty@tty1.service
 
[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/usr/lib64/encfs-mount
 
[Install]
WantedBy=sysinit.target
```

encfs-mount file
```
#!/bin/bash
fusermount -u /usr/local
fusermount -u /opt
fusermount -u /crypt	

rm -rf /usr/local/* /usr/local/.*
rm -rf /crypt/* /crypt/.*
rm -rf /opt/* /opt/.*

encfs -v --extpass='echo $ENC_PASSWORD' /usr/.local /usr/local
encfs -v --extpass='echo $ENC_PASSWORD' /.crypt /crypt
encfs -v --extpass='echo $ENC_PASSWORD' /.opt /opt"
```

Regards,
Madhu C S

**Comment by Vascom** [comment]
On my system it work.
You can try look at selinux errors, sure that /usr/.local exist and readable for script running by systemd service.
Also look at systemd boot plot and sure that your servise start at requred moment
`systemd-analyze plot > file.svg`

**Comment by benrubson** [comment]
@MadhuSudhanCS OK for you ? Did you solve your issue ?

**Comment by MadhuSudhanCS** [comment]
I analyzed the system boot plot and my service starts before fuse connection is starting. Some times I get file not found error. This error is random. I am not able to figure out the exact dependency to be added.
Do you suggest me to add an entry in /etc/fstab ?

Regards,
--Madhu C S

**Comment by benrubson** [comment]
[This](https://unix.stackexchange.com/questions/246935/set-systemd-service-to-execute-after-fstab-mount) might help you.

**Comment by MadhuSudhanCS** [comment]
Thank you. Will try to write  systems mount service and test. Will update the status.

**Comment by benrubson** [comment]
Feel free to close once solved 👍 Thx 👍
