### ISSUE TITLE
Build failed with libeasyloggingpp.a

### ISSUE THREAD

**Issue by Vascom** [vgough/encfs#441]
I am try build master of F26 and has this error:

> /usr/bin/ld: vendor/github.com/muflihun/easyloggingpp/libeasyloggingpp.a(easylogging++.cc.o): relocation R_X86_64_PC32 against symbol `_ZN2el11LevelHelper15convertToStringENS_5LevelE' can not be used when making a shared object; recompile with -fPIC

Full build log https://paste.fedoraproject.org/paste/W3ZefkWyQToZ9QEODrSbGg

How it can be solved?

Also please add cmake option to use system shared libeasyloggingpp library (so entire "vendor" directory can be removed and no bundled libs present). If I am add it to Fedora repo in the future.

**Comment by Vascom** [comment]
Can you add `-fPIC` to **CMAKE_CXX_FLAGS** if `-DBUILD_STATIC_LIBS=OFF -DBUILD_SHARED_LIBS=ON` used?

**Comment by benrubson** [comment]
@Vascom in #450 in added `USE_INTERNAL_EASYLOGGING` cmake option so that you can now use -`DUSE_INTERNAL_EASYLOGGING=OFF`.
Does this help you ?

**Comment by Vascom** [comment]
Thanks. But now easylogging still not in Fedora repo so encfs builded with internal one and `-fPIC` needed for it. Also in Fedora all shared libraries bulded with `-fPIC` and libencfs.so too.

**Comment by benrubson** [comment]
Then use the default static build ?
Why would you need to build libs shared if they are only used by EncFS ?
Thx 👍

**Comment by Vascom** [comment]
https://fedoraproject.org/wiki/Packaging:Guidelines#Shared_Libraries
> Whenever possible (and feasible), Fedora Packages containing libraries should build them as shared libraries.

https://fedoraproject.org/wiki/Packaging:Guidelines#Packaging_Static_Libraries
> Packages including libraries SHOULD exclude static libs as far as possible (eg by configuring with --disable-static). Applications linking against libraries SHOULD link against shared libraries not static versions.

**Comment by benrubson** [comment]
OK, these are Fedora best practices :)
Let's then add the required flag 👍

**Comment by benrubson** [comment]
Of, flag added in #450, you should then just have to use `-DBUILD_SHARED_LIBS` 👍

**Comment by benrubson** [comment]
So, flag added in #450, you should then just have to use `-DBUILD_SHARED_LIBS=ON` 👍
@Vascom could you test applying #450, and let us know ?
Many thx 👍

**Comment by Vascom** [comment]
Yes, it works.
