### ISSUE TITLE
How likely is it to have encFS not recognize a valid password?

### ISSUE THREAD

**Issue by working-name** [vgough/encfs#442]
Hello there, 

I set up sovereign on a server (everything is via ansible playbook) and I've retraced my steps, tried *all of the passwords* I have on file for the sever. I use 1Password, so highly unlikely that I misplaced a password. I never changed the encFS password, never touched config files, the server was up for about 260 days and then it was forcefully rebooted by the host. Now I can't decode the FS. I can't think of anything that has changed other than upgrading openssl and probably libxml or whatever this project uses to parse its own config file.

Anything I can do or should I just cut my losses?

And most importantly, should I stay away from EncFS? Does it ever screw up like this where you simply lose everything?

My version:
```
Build: encfs version 1.7.4
```

The encrypted folder:
```
/encrypted$ ls -la
total 40
drwxrwxr-x+  9 root     mail     4096 Oct 15  2016 .
drwxr-xr-x  25 root     root     4096 Oct 24 19:07 ..
-rw-r--r--   1 root     root     1092 Oct 15  2016 .encfs6.xml
drwxrwxr-x   2 root     root     4096 Oct 15  2016 9c3GIrDaqUznL1vYywb0pA,r
drwxr-xr-x   3 prosody  prosody  4096 Oct 15  2016 BptL79s86UEF,gQgRrktdaRz
drwxr-xr-x   3 vmail    dovecot  4096 Oct 15  2016 RHm5NBNC1TtNGUeLe9yNwUEX
drwxr-xr-x   2 www-data www-data 4096 Oct 15  2016 VFG0DWNiCrGF12wl-CK49u-O
-rw-r--r--   1 root     root        0 Oct 15  2016 VTLtQIjtTaN140tyrPEJGnVk
drwxr-xr-x   4 tomcat7  tomcat7  4096 Oct 15  2016 aRwd3joPERX1IKtihbXQroJq
drwxrwx---   4 vmail    dovecot  4096 Oct 17  2016 pllNvNXRVtJ169clYhpfVx,E
drwxr-xr-x   2 www-data www-data 4096 Oct 15  2016 ykQoS,LMPuS0sVU17963fskW
```

Every attempt at mounting a decrypted volume:
```
encfs -f -v /encrypted /decrypted --public
17:51:03 (main.cpp:523) Root directory: /encrypted/
17:51:03 (main.cpp:524) Fuse arguments: (fg) (threaded) (keyCheck) (ownerCreate) encfs /decrypted -f -o allow_other -s -o use_ino -o default_permissions
17:51:03 (FileUtils.cpp:177) version = 20
17:51:03 (FileUtils.cpp:181) found new serialization format
17:51:03 (FileUtils.cpp:199) subVersion = 20100713
17:51:03 (Interface.cpp:165) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:0)
17:51:03 (SSL_Cipher.cpp:370) allocated cipher ssl/aes, keySize 32, ivlength 16
17:51:03 (Interface.cpp:165) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:0)
17:51:03 (SSL_Cipher.cpp:370) allocated cipher ssl/aes, keySize 32, ivlength 16
17:51:03 (FileUtils.cpp:1620) useStdin: 0
EncFS Password:
17:51:09 (Interface.cpp:165) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:0)
17:51:09 (SSL_Cipher.cpp:370) allocated cipher ssl/aes, keySize 32, ivlength 16
17:51:12 (FileUtils.cpp:1628) cipher key size = 52
17:51:12 (SSL_Cipher.cpp:604) checksum mismatch: expected 2524369136, got 3238340236
17:51:12 (SSL_Cipher.cpp:605) on decode of 48 bytes
Error decoding volume key, password incorrect
17:51:12 (openssl.cpp:48) Allocating 41 locks for OpenSSL
```

encfsctl info /encrypted/
```
Version 6 configuration; created by EncFS 1.7.4 (revision 20100713)
Filesystem cipher: "ssl/aes", version 3:0:0 (using 3:0:2)
Filename encoding: "nameio/block", version 3:0:0 (using 3:0:1)
Key Size: 256 bits
Using PBKDF2, with 1200166 iterations
Salt Size: 160 bits
Block Size: 1024 bytes, including 8 byte MAC header
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File data IV is chained to filename IV.
File holes passed through to ciphertext.
```

config file
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="10">
<cfg class_id="0" tracking_level="0" version="20">
        <version>20100713</version>
        <creator>EncFS 1.7.4</creator>
        <cipherAlg class_id="1" tracking_level="0" version="0">
                <name>ssl/aes</name>
                <major>3</major>
                <minor>0</minor>
        </cipherAlg>
        <nameAlg>
                <name>nameio/block</name>
                <major>3</major>
                <minor>0</minor>
        </nameAlg>
        <keySize>256</keySize>
        <blockSize>1024</blockSize>
        <uniqueIV>1</uniqueIV>
        <chainedNameIV>1</chainedNameIV>
        <externalIVChaining>1</externalIVChaining>
        <blockMACBytes>8</blockMACBytes>
        <blockMACRandBytes>0</blockMACRandBytes>
        <allowHoles>1</allowHoles>
        <encodedKeySize>52</encodedKeySize>
        <encodedKeyData>
**removed**
        </encodedKeyData>
        <saltLen>20</saltLen>
        <saltData>
**removed**
        </saltData>
        <kdfIterations>1200166</kdfIterations>
        <desiredKDFDuration>3000</desiredKDFDuration>
</cfg>
</boost_serialization>
```

**Comment by rfjakob** [comment]
> Does it ever screw up like this where you simply lose everything?

No, I don't think so.

A few questions:

1) Has this filesystem ever be mounted apart of the mount on creation?

2) Are you aware of the `ENCFS6_CONFIG` environment variable? Are you sure it was not set?

**Comment by working-name** [comment]
1. Yes a few unmounts, and remounts by myself in the console and a few restarts in between when I first set up the vps.
2. I bumped into `ENCFS6_CONFIG` when reading through other threads but I ignored it since it was not set on my system. I just tried it again to see what happens when I set the variable to `/encrypted/.encfs6.xml` and I got the same error.

I'm pretty much out of ideas unfortunately. The sovereign project `testPassword` that's the default for things you forget to configure is not valid either.

**Comment by rfjakob** [comment]
Do you have older backup copies of the encfs6.xml ? I don't why it should have changed, but on the other hand, I don't see why an encfs6.xml config file that has not changed would stop accepting a password.

**Comment by rfjakob** [comment]
A few more ideas: 

Does the password contain non-ASCII characters that may be affected by some language setting?

Does it start or end with whitespace?

**Comment by benrubson** [comment]
Yes I was also thinking about something like a locale change after server reboot.

**Comment by working-name** [comment]
Hi,

No spaces in the password, and no non-ascii characters. The password I have is just alphanumeric with dashes, 32 characters. The locale has not changed, it's still en_US.

Also, I just realized /encrypted was not being backed up, so no other copies of .enfs6.xml, which was last modified Oct 15, 2016.

I suppose I'll have to chalk this up to one of two possibilities: I am an idiot and somehow don't have the password I set, or there was some inexplicable filesystem damage when the server was forcefully shut down 22 days ago.

**Comment by benrubson** [comment]
The filesystem damage would especially had to damage `.enfs6.xml` file (one of its last 5/6 parameters) to get the `Error decoding volume key, password incorrect` message.
Sounds quite strange at it's let's say a read-only file, but during the FS creation.

Put your password in a file to be sure you correctly spell it, and use `--extpass="cat passfile"` as a test ?

**Comment by working-name** [comment]
Thank you, @benrubson, I tried that when I started to doubt iTerm thinking it was somehow appending spaces when pasting my password.

I am actually hoping that this is a rookie mistake on my part. I didn't think about running a `modprobe fuse` until now. It seems it's no longer there, so I'll bug the host to have it enabled then report back. They may have upgraded the kernel and forgot to restore the mod.
```
modprobe: FATAL: Module fuse not found.
```

**Comment by benrubson** [comment]
Let us know, but not sure `Error decoding volume key, password incorrect` message is related to fuse module being there or not. U'll tell us 👍

**Comment by working-name** [comment]
This host is a mess (SSDNodes). I've been getting up-sell offers as replies to my requests, even by the owner. Does not bode well. 

Anyway, whatever happened – whether an openVZ fuse device misconfiguration or forgetting to load the fuse kernel module at the host level, it seems now fuse is "magically" back to working. I was able to mount a new encrypted folder, I rebooted the VPS, I tried to mount again, no issues.

The old fuse encrypted folder still will not accept any passwords. I moved the encrypted folder over to a ubuntu, a debian, and finally a darwin machine. None of them were able to mount it. The folder somehow got corrupted. Don't know how, don't know why, but it happened.

**Comment by benrubson** [comment]
@working-name did you manage to solve your issue ?
Perhaps you definitely scraped your "old" encrypted folder ? :-/

**Comment by working-name** [comment]
@benrubson I could not mount the encFS folder anywhere else. Files were damaged somehow, so yes unfortunately I had to give up and scrape it. Most data was available offline on my machine but nonetheless quite unfortunate. Since nothing else makes sense I blame the host for screwing it up, as the failure/corruption corresponds to the forced reboot and a period in which encFS kernel mod was not available to my VPS. **Thank you** for all the time and attention to this!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benrubson** [comment]
Thank you @working-name for your answer.
Hopefully you had the data offline somewhere, good news 👍 
I then close this issue, thx.
