### ISSUE TITLE
Store encrypting files in temp dir

### ISSUE THREAD

**Issue by Slyke** [vgough/encfs#451]
Is it possible to optionally specify a temporary directory for encFS?

Currently if it's encrypting a file it stores the partially completed file in the encrypted directory even when the file hasn't been fully written to yet. This poses issues with rclone (I'm getting I/O errors).

So I was wondering if encFS could write the files it's currently encrypting to a temporary directory, and once a file is encrypted, it is then moved to the target encrypted directory.

**Comment by benrubson** [comment]
As a ref here is an already opened rclone issue : #256.
Unfortunately I'm not sure your idea is a good one as it is too far from what a FS should be.
In addition, the FS can't know when the file is fully written, it's an application matter.
We would have to deal with timeouts, errors...
This should be implemented at (sync ?) application level.
Anyway, thanks for the idea 👍

**Comment by Slyke** [comment]
@benrubson 
It doesn't appear that there has been any updates on rclone to deal with this issue for about a year right now. It may be worth putting this feature into encFS sometime in the future, as an option of course. I'll still look around and report back if I find a solution, but it doesn't appear anyone else has yet.

**Comment by benrubson** [comment]
I thought about a possible solution in #256.
Let's continue discussion there 👍
