### ISSUE TITLE
Hard links out of sync

### ISSUE THREAD

**Issue by rfjakob** [vgough/encfs#452]
Interesting that nobody noticed that in all these years:
```
$ touch f1
$ ln f1 f2
$ ls -li f1 f2 ; echo ; echo asdasd > f1 ; ls -li f1 f2
1048515 -rw-rw-r--. 2 jakob jakob 0 12. Nov 13:33 f1
1048515 -rw-rw-r--. 2 jakob jakob 0 12. Nov 13:33 f2

1048515 -rw-rw-r--. 2 jakob jakob 7 12. Nov 13:35 f1
1048515 -rw-rw-r--. 2 jakob jakob 0 12. Nov 13:33 f2
```

The reason seems to be that EncFS represents hard links as independent nodes to the kernel:
```
LOOKUP /f1
getattr /f1
   NODEID: 2

LOOKUP /f2
getattr /f2
   NODEID: 4
```

I'm unsure if we should even fix / change the behavoir, but at least it's now documented in this ticket.

**Comment by rfjakob** [comment]
The [passthrough_fh](https://github.com/libfuse/libfuse/blob/master/example/passthrough_fh.c) example from libfuse does not have the same problem:

```
$ ls -li f1 f2 ; echo ; echo asdasd > f1 ; ls -li f1 f2
1062681 -rw-rw-r--. 2 jakob jakob 0 12. Nov 13:50 f1
1062681 -rw-rw-r--. 2 jakob jakob 0 12. Nov 13:50 f2

1062681 -rw-rw-r--. 2 jakob jakob 7 12. Nov 13:50 f1
1062681 -rw-rw-r--. 2 jakob jakob 7 12. Nov 13:50 f2
```

**Comment by rfjakob** [comment]
Well, actually, it does have the same problem.
It's just that it disables caching at [passthrough_fh.c#L61](https://github.com/libfuse/libfuse/blob/8ec7fd92eb5f41f3baffba91a397296afcd926ab/example/passthrough_fh.c#L61). When you re-enable caching, you get the same result as with encfs.

**Comment by rfjakob** [comment]
Duplicate of https://github.com/libfuse/libfuse/issues/79

**Comment by benrubson** [comment]
I intensively use hard-links, but I never noticed this as I don't modify the hard-linked files.

A workaround to this should then be to use `--nocache`.
Did you try ?
