### ISSUE TITLE
Mount Hangs - 1.9.2

### ISSUE THREAD

**Issue by vindicatorr** [vgough/encfs#453]
I just had a kernel panic and restarted my machine and now encfs hangs while trying to mount:
```
/usr/bin/encfs -vd /<.encryptionPath> /<decryptionPath> --extpass=cat /<passwordFile>
VER Root directory: /<.encryptionPath>/ [main.cpp:540]
VER Fuse arguments: (daemon) (threaded) (keyCheck) encfs /<decryptionPath>/ -d /<passwordFile> -o use_ino -o default_permissions  [main.cpp:541]
VER found new serialization format [FileUtils.cpp:294]
VER subVersion = 20100713 [FileUtils.cpp:308]
VER checking if ssl/aes(3:0:2) implements ssl/aes(3:0) [Interface.cpp:110]
VER allocated cipher ssl/aes, keySize 32, ivlength 16 [SSL_Cipher.cpp:333]
VER getUserKey: fds = 3, 4 [FileUtils.cpp:1450]
```
```
$ ls -la /proc/<encfsPID>/fd
total 0
dr-x------ 2 root root  0 Nov 16 15:56 .
dr-xr-xr-x 9 root root  0 Nov 16 15:56 ..
lrwx------ 1 root root 64 Nov 16 15:56 0 -> /dev/pts/0
lrwx------ 1 root root 64 Nov 16 15:56 1 -> /dev/pts/0
lrwx------ 1 root root 64 Nov 16 15:56 2 -> /dev/pts/0
lrwx------ 1 root root 64 Nov 16 15:56 4 -> 'socket:[31839]'
```

**Comment by benrubson** [comment]
`--extpass="cat /<passwordFile>"` ?

**Comment by vindicatorr** [comment]
Yeah, I just santize any personal info. I figured you would get the gist.
Essentially it worked, and eventually I had a kernel panic leading me to reboot and now I can't mount it again.
The folders exist as does the encfs*.xml and pw file.

**Comment by benrubson** [comment]
Sure, but I wanted to say that some `" "` must be missing around your `extpass` command.

**Comment by vindicatorr** [comment]
Ugh... shoot me. I was having issues with syncthing after the panic and simply copy/pasted what was displayed in "$ ps" I think.

Close this on account of my own stupidity.

But on a side note, what WAS happening in reference to what "extpass" was given?

And on another side note, a curiosity I just noticed regarding an ls -la on an encfs dir after the kernel panic... There were perhaps 5 syncthing database files that said "input/output error" at the top of the ls and displayed '???????????? ? ?       ?         ? <filename.ldb>' for each file.
I think I might have rebooted one more time and now that I can mount it (correctly), only one file shows the "????..." but no "input/output" error, but instead now says "no such file or directory". I'm guessing there is some file in the <.encryptedPath> that isn't really there but encfs thinks it is.

**Comment by rfjakob** [comment]
What was happening is that encfs waited for `cat` to return (cat without any arguments waits for CTRL-D)
