### ISSUE TITLE
encfs using a lot of CPU time on CentOS 7

### ISSUE THREAD

**Issue by mdsalman729** [vgough/encfs#456]
Over a period of time, I see that encfs ends up taking a large amount of CPU time. 
This is not the case with eCryptfs. 

Is this expected?

**Comment by Vascom** [comment]
Are you use fuse-encfs from EPEL repo?

**Comment by mdsalman729** [comment]
Yes

**Comment by Vascom** [comment]
May be it on large file or slow CPU or slow HDD or small RAM size?
Give any additional information: model of CPU, size (and sample) of files you need encrypt.

Also may be wait release of encfs 1.9.3.

**Comment by mdsalman729** [comment]
It is a virtual machine running on ESXi. 8 cores, 8GB memory and disk 100GB
model name	: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

Output of df command 
/dev/sdb2      188855084 7104676 172134076   4% /
devtmpfs         3994564       0   3994564   0% /dev
tmpfs            4005132       4   4005128   1% /dev/shm
tmpfs            4005132     552   4004580   1% /run
tmpfs            4005132       0   4005132   0% /sys/fs/cgroup
/dev/sda6        5913348  216496   5373424   4% /shared
/dev/sda1         194241  160616     19289  90% /boot
encfs          188855084 7104676 172134076   4% /opt
encfs          188855084 7104676 172134076   4% /usr/local
encfs          188855084 7104676 172134076   4% /crypt

**Comment by benrubson** [comment]
Of course EncFS consumes CPU, depending on how you work with the encrypted FS.
Be sure to have OpenSSL compiled with AES-NI support, without EncFS will be much slower / will eat much more CPU.
