### ISSUE TITLE
Release tarball 1.9.3 has version 1.9.2 defined in CMakeLists.txt

### ISSUE THREAD

**Issue by vaygr** [vgough/encfs#461]
Therefore it leads to version 1.9.2 shared object creation.

**Comment by rfjakob** [comment]
Oh, darn.

**Comment by rfjakob** [comment]
I think the only clean way to fix this is to release v1.9.4 immediately. Even if its embarrassing, that's the only way to avoid confusion.

**Comment by vaygr** [comment]
I'm also working on a linking PR, which should be ready soon, so it might be better to postpone this just a bit.

**Comment by rfjakob** [comment]
What does the PR do?

**Comment by rfjakob** [comment]
I have added a note about the error for now: https://github.com/vgough/encfs/releases/tag/v1.9.3

> NOTE: The v1.9.3 release incorrectly reports version 1.9.2 when compiled. I'll publish a new release sortly.

**Comment by vaygr** [comment]
Oh, it fixes encfs compilation with `BUILD_SHARED_LIBS` enabled:

- `tinyxml2_static` target is invalid, since it's there only for a static library => encfs couldn't find it via `-ltinyxml2`
- easylogging is a header library, so it doesn't even have an option to be built as shared => encfs couldn't find it via `-leasyloggingpp`

**Comment by rfjakob** [comment]
Sounds like it is worth waiting for :)

**Comment by benrubson** [comment]
Perhaps we should think about a `BUILD_SHARED_LIBS` Travis job to avoid such issue.

**Comment by rfjakob** [comment]
Absolutely, we need that.

**Comment by rfjakob** [comment]
v1.9.4 released, thanks!
https://github.com/vgough/encfs/releases/tag/v1.9.4
