### ISSUE TITLE
Variable res should be of type off_t in FileNode::getSize() method

### ISSUE THREAD

**Issue by vandeir** [vgough/encfs#467]
Variable res in method FileNode::getSize() should be of type off_t. It is declared with type int. This causes int overflow when getting size of big files.

**Comment by benrubson** [comment]
Nice catch, thank you very much @vandeir 👍 

Did you hit this bug on a 32 bits platform ?

**Comment by vandeir** [comment]
Nope. 64 bits. I found this bug because I am studying a CTR mode implementation applied to EncFS. By the way, to call this method from another one in FileNode, I had to disable the Lock inside getSize to avoid double locking. Is locking really necessary inside getSize()?

**Comment by benrubson** [comment]
As for every other method, to be sure operations to be consistent ?
To avoid getting size while file is being written, truncated... ?
I'm not sure about the drawbacks of disabling lock in `FileNode::getSize()`, I did not have a deep look.
@rfjakob or @vgough could perhaps tell us more :)
