### ISSUE TITLE
encfs process keeps growing in memory

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#469]
Hi,

I noticed that `encfs` process keeps growing when browsing files.

On a daily basis I'm rsync-ing a repository of more than 1.300.000 files.
All along the task, `encfs` process keeps growing, until around 400 MB in memory.
_(`rsync` keeps around 3 MB)_

Some questions then :
- is it the expected behavior ?
- can we make it release memory (FileNodes ?) when no more needed ?
- without impacting performance ?

Many thx 👍 

Ben

**Comment by benrubson** [comment]
On the contrary, copying a huge file (450 GB) does not make `encfs` process grow.

**Comment by rfjakob** [comment]
The kernel keeps the inodes open in its cache, so encfs cannot drop them from memory.

Experiment: does 

echo 3 > /proc/sys/vm/drop_caches

free the memory?

**Comment by benrubson** [comment]
Mmmmh FreeBSD does not propose such an option.

So here was the process :
```
# ps
   VSZ    RSS     TIME COMMAND
427464 395640 12:45.60 /usr/local/bin/encfs
```

Let's have a look at the server memory.
FS dismounted at 22:17:44.

And just after, the `inact` part of the memory reduced from 576 to 203 MB, then freeing 373 MB, which is almost around the RSS part of the process above.

![before](https://user-images.githubusercontent.com/6764151/36247678-3005edba-1235-11e8-81af-e85b8f1bd363.png)
![after](https://user-images.githubusercontent.com/6764151/36247681-33f559e2-1235-11e8-90a3-aece5e2fd109.png)

Inactive bytes are bytes that could be re-used, but also dropped, in case OS needs more memory.

Perfect, seems to confirm your thoughts @rfjakob 👍 

I should have done this without opening a ticket... Let's then close this :)
