### ISSUE TITLE
Google Drive, Insync, EncFS, Ubuntu and Raspberry Pi Project?

### ISSUE THREAD

**Issue by dairefagan** [vgough/encfs#472]
On my Ubuntu desktop I have a LUKS dm-crypt, drive which I mount when necessary, and another unencrypted drive which Insync syncs with my unlimited storage Google Drive account.
I would like to also sync the encrypted drive, but I would like the contents, including folder names, to be encrypted on Google Drive, but easily accessible, with on-the-fly encryption, from my Ubuntu desktop using Insync, and a Raspberry Pi server I will be configuring.

Boxcryptor seemed a perfect solution, at least from the desktop perspective, and it even offers apps for Android, but unfortunately no client for Linux. Having a directory in my Insync directory which would automatically encrypt before syncing would be ideal.

I have since read up on EncFS but I am unsure if it is the way to go or not. Is what I propose a feasible project?

**Comment by benrubson** [comment]
EncFS in reverse mode is I think what you need 👍 
I see no reason why it would not work.
Did you give it a try ?

**Comment by benrubson** [comment]
Closing this for now, feel free to re-open if needed !
Thx 👍
