### ISSUE TITLE
encfs_link and DirNode::link methods parameters named wrong

### ISSUE THREAD

**Issue by vandeir** [vgough/encfs#475]
In encfs.cpp, function encfs_link is defined this way:
int encfs_link(const char *from, const char *to)

And in DirNode.cpp:
int DirNode::link(const char *from, const char *to)

The parameters are named wrong. The first parameter should be "to" and the second "from".

This is not a bug, just causes confusion when analysing the code.
The parameters should be named in order equal to encfs_symlink, witch is correct.

**Comment by benrubson** [comment]
yes it should be consistent you're right.
If you are on a PR for this, feel free, it'll be merged 👍

**Comment by benrubson** [comment]
Thx @vandeir, #482 closes this 👍
