### ISSUE TITLE
Per-file encryption key?

### ISSUE THREAD

**Issue by andrisi** [vgough/encfs#479]
Dear contributors, does encfs support or planning to support separate keys for each file? We need to store files that only the owner can access with their own key. Thanks.

**Comment by benrubson** [comment]
Hi @andrisi, I'm not sure this is in the next plans.
Perhaps @vgough or @rfjakob could tell more.

What about an EncFS directory per user ?
This is what Fuse is intended for 👍

**Comment by andrisi** [comment]
Thanks! (It looks like it would not be a good solution for me anyway.)
