### ISSUE TITLE
Allow encfs6.xml in different directory

### ISSUE THREAD

**Issue by lazyadmins** [vgough/encfs#48]
Can you please allow for the encfs6.xml config file to be located in a folder different from the encrypted folder for better security when syncing with cloud providers such as Google drive and Dropbox.

**Comment by rfjakob** [comment]
export ENCFS6_CONFIG=/foo/bar

But, this does not seem to be mentioned in the man page. I am leaving this bug open until I add it.

**Comment by pepa65** [comment]
Makes me wonder, to what degree is the security enhanced by an attacker not having access to the configuration file?

**Comment by rfjakob** [comment]
Added: https://github.com/rfjakob/encfs/blob/next/encfs/encfs.pod#environment-variables
Will be in 1.8-rc2.
