### ISSUE TITLE
Encrypt filenames only / use nullCipher for data

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#481]
Hi,

Would be nice to be able to encrypt filenames only.
Useful if files' content is already encrypted (whatever the method is), but goal is also to have filenames encrypted.
EncFS should then be able to use nullCipher for data itself.

Thank you 👍 

Ben

**Comment by benrubson** [comment]
As a quick test I replaced :
`fsConfig->cipher = cipher;`

with :
`static Interface NullInterface("nullCipher", 1, 0, 0);`
`fsConfig->cipher = Cipher::New(NullInterface, 4096);`

here :
https://github.com/vgough/encfs/blob/v1.9.4/encfs/FileUtils.cpp#L1650

It works.

In the code, the `cipherAlg` used for the key is automatically used for data.
I think we would have to create a `fileAlg`, as for the existing `nameAlg`.

**Comment by rfjakob** [comment]
Hmm, sounds like a good way to shoot yourself in the foot. Directory looks encrypted, but actually is not

**Comment by benrubson** [comment]
This would be an option for advertised users.
I have some use cases where data is already encrypted, thus I would only need to encrypt filenames.
No need to loose CPU time to re-encrypt data.
Others may certainly encounter such a use case.
