### ISSUE TITLE
how to tell ./configure to use my installation of fuse?

### ISSUE THREAD

**Issue by gsal** [vgough/encfs#49]
The system I use does not have fuse and, so, I have installed the latest version of it in my own home directory, say, /home/*myuserid*/local/fuse

How to tell ./configure to look for fuse in the above path? 

Otherwise, it insists in looking for fuse in the usual system places and it does not find it. 

checking fuse.h usability... no
checking fuse.h presence... no
checking for fuse.h... no
checking for fuse.h library with -I/usr/include/fuse... no
checking for fuse.h library with -I/usr/local/include/fuse... no
checking for fuse.h library with -I/opt/include/fuse... no
checking for fuse.h library with -I/opt/local/include/fuse... no
checking for fuse.h library with -I/usr/include/osxfuse... no
checking for fuse.h library with -I/usr/local/include/osxfuse... no
checking for fuse.h library with -I/opt/local/include/osxfuse... no
checking for fuse_mount in -lfuse... no
checking for fuse library with -L/usr/lib... no
checking for fuse library with -L/usr/local/lib... no
checking for fuse library with -L/opt/lib... no
checking for fuse library with -L/opt/local/lib... no
checking for fuse_mount in -losxfuse... no
checking for osxfuse library with -L/usr/lib... no
checking for osxfuse library with -L/usr/local/lib... no
checking for osxfuse library with -L/opt/lib... no
checking for osxfuse library with -L/opt/local/lib... no
checking for fuse_new in -lfuse... no
configure: error: Unable to find libfuse.

Thanks in advance for any help you may offer...I know this is not an issue, but otherwise, I don't know how to ask for help

**Comment by rfjakob** [comment]
This is also discussed in #18 - please try the `USER_INCLUDES` solution and report back in #18!
