### ISSUE TITLE
encfsctl cat : segmentation fault

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#492]
Hi,

`encfsctl cat` tests added in the last commits to master tend to generate a segmentation fault.

Sometimes on Linux, sometimes on Mac OS, sometimes both...
See for example this [Travis job](https://travis-ci.org/vgough/encfs/builds/354980072?utm_source=github_status&utm_medium=notification).

Related commits : https://github.com/vgough/encfs/commit/dcf8435d4c3d1926e65bcac7f07a7aaa6ca0a6ea and https://github.com/vgough/encfs/commit/154839d67c9b7504687bcc2301fd2782ff9f3368

Unfortunately segmentation faults are rather sporadic, and I can't manage to reproduce them locally.

Any thoughts ?

Thank you 👍

**Comment by rfjakob** [comment]
Will try to reproduce here on Linux

**Comment by benrubson** [comment]
Thx. I tried on both Linux (Debian 9) & FreeBSD without succeeding, even with tests running many times in a loop.
Still trying to find the culprit.

**Comment by rfjakob** [comment]
We could run it with gdb on Travis

**Comment by rfjakob** [comment]
...or maybe not. Looks like quite a lot of pain.

**Comment by rfjakob** [comment]
I have added catchsegv at https://github.com/rfjakob/encfs-next/commit/d12b13776347c1a45828f7d1ba5754f8e416b207 ( see https://stackoverflow.com/a/6599348 for details). I'll click rebuild a few times in Travis and hope I catch a crash.

**Comment by benrubson** [comment]
Nice findings 👍
Fingers crossed !
Rather strange and quite embarrassing to have a seg-fault in master...
Thx for your help.

**Comment by rfjakob** [comment]
Well, it's not in any release yet, so I think we are good

**Comment by rfjakob** [comment]
No luck with Travis yet, unfortunately: https://travis-ci.org/rfjakob/encfs-next/builds/355607145
(the Mac failure is because it does not have catchsegv and not interesting)

**Comment by benrubson** [comment]
As at the casino :)
I tried to reproduce the issue only keeping the `encfsctl` test :
https://travis-ci.org/vgough/encfs/builds/355614015
So it should confirm issue is with `encfsctl`.

**Comment by benrubson** [comment]
I managed to get a job with `catchsegv` here :
https://travis-ci.org/vgough/encfs/builds/355621748
Unfortunately it does not provide much more output :-|

**Comment by benrubson** [comment]
Well I think this is due to `Test::More` which redirects stderr.

**Comment by benrubson** [comment]
I modified test to only keep `encfsctl` calls, without `Test::More` :
https://github.com/vgough/encfs/pull/493
Unfortunately I did not manage to make Travis fail yet !

**Comment by benrubson** [comment]
I modified test to only keep `encfsctl` calls, without `Test::More` : https://github.com/vgough/encfs/pull/493
Unfortunately I did not manage to make Travis fail yet !
Even modifying Travis job file to run 4 Linux tests at the same time, running the job several times... No success !
Even the last 2 commits added to master are successful. Quite strange.

**Comment by benrubson** [comment]
Ah, the changelog PR #486 just failed...

**Comment by benrubson** [comment]
The command _seems_ to fail more easily being call with `qx()` Perl command.
Using `system()` in my previous tests, it did not want to fail.
I managed to make it fail again with `qx()`, but did not catch catchsegv output...
catchsegv must then send to stdout, which was redirected to the encfsctl output file...
Let's then cat output files...

**Comment by benrubson** [comment]
Dump here !
https://travis-ci.org/vgough/encfs/jobs/355745576

**Comment by benrubson** [comment]
With `-O0` compilation option :
https://travis-ci.org/vgough/encfs/jobs/355749104
https://travis-ci.org/vgough/encfs/jobs/355749106
(does not seem much different)
