### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by pepa65** [vgough/encfs#50]
I have pulled the latest master, configure/made it, and now I get:
undefined symbol: _Z6initFSP13EncFS_ContextRKSt10shared_ptrI10EncFS_OptsE

**Comment by pepa65** [comment]
Started from scratch, cloned current master, prepped for Ubuntu, but the configure step now ends with:
cannot find input file: `po/Makefile.in.in'

**Comment by rfjakob** [comment]
Which ubuntu version?

**Comment by pepa65** [comment]
14.04.1

**Comment by rfjakob** [comment]
Could you copy-paste the whole shell output from "git clone" to the error?

**Comment by pepa65** [comment]
$ git clone https://github.com/vgough/encfs
Cloning into 'encfs'...
remote: Counting objects: 1997, done.
remote: Total 1997 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1997/1997), 1021.05 KiB | 93.00 KiB/s, done.
Resolving deltas: 100% (1434/1434), done.
Checking connectivity... done.
$ libtoolize --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: linking file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file `m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file `m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file `m4/lt~obsolete.m4'
$ aclocal
$ autoheader
$ touch build-aux/config.rpath
$ automake --force-missing --add-missing
configure.ac:29: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/config.guess'
configure.ac:9: installing 'build-aux/config.sub'
configure.ac:7: installing 'build-aux/install-sh'
configure.ac:7: installing 'build-aux/missing'
encfs/Makefile.am: installing 'build-aux/depcomp'
$ autoconf
$ ./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for a sed that does not truncate output... /bin/sed
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for boostlib >= 1.34... yes
configure: WARNING: BOOST_CPPFLAGS -I/usr/include
checking whether the Boost::Serialization library is available... yes
checking for exit in -lboost_serialization... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking fuse.h usability... yes
checking fuse.h presence... yes
checking for fuse.h... yes
checking for fuse_mount in -lfuse... yes
checking for fuse_mount in -losxfuse... no
checking for osxfuse library with -L/usr/lib... no
checking for osxfuse library with -L/usr/local/lib... no
checking for osxfuse library with -L/opt/lib... no
checking for osxfuse library with -L/opt/local/lib... no
checking for fuse_new in -lfuse... yes
checking For supported FUSE API version... yes
checking attr/xattr.h usability... no
checking attr/xattr.h presence... no
checking for attr/xattr.h... no
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking whether xattr interface takes additional options... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for OPENSSL... yes
checking for EVP_aes_128_cbc... yes
checking for EVP_aes_192_cbc... yes
checking for EVP_aes_256_cbc... yes
checking for EVP_bf_cbc... yes
checking for EVP_CIPHER_CTX_set_padding... yes
checking for HMAC_Init_ex... yes
checking for RLOG... yes
checking for pod2man... /usr/bin/pod2man
checking for pod2html... /usr/bin/pod2html
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating encfs/Makefile
config.status: creating encfs.spec
config.status: creating makedist2.sh
config.status: creating m4/Makefile
config.status: error: cannot find input file: `po/Makefile.in.in'

**Comment by pepa65** [comment]
(And there was a "cd encfs" after the clone...)

**Comment by rfjakob** [comment]
Is there a specific reason you do not use "autoreconf -if"? Does it yield
the same error?

**Comment by pepa65** [comment]
I was just following encfs.wiki/Compiling-encfs-on-Ubuntu-14.04.md
At what point should I use it?

**Comment by pepa65** [comment]
I used it just before the configure, and then the configure went fine, as did the make, and the resulting binary worked as well! Thanks.

**Comment by rfjakob** [comment]
I have updated the wiki page, it now lives at: https://github.com/vgough/encfs/wiki/Installing-Encfs
Thanks for the report!

**Comment by pepa65** [comment]
Great, thanks. It's so easy now, I will no longer need the wiki..! ;-)
