### ISSUE TITLE
A request for a binary version of encfs for windows to be uploaded

### ISSUE THREAD

**Issue by mhogomchungu** [vgough/encfs#508]
This[1] pull request made it possible to run encfs on windows.

I have a project called SiriKali[2] and would like to add support for encfs on windows and will appreciate very much for a binary version of encfs for windows to be uploaded to give some of us an opportunity to play with it.

I plan to make a new release of SiriKali on the first of April, 2018 and i'll need something to play with much sooner than that date.

[1] https://github.com/vgough/encfs/pull/499
[2] http://mhogomchungu.github.io/sirikali

**Comment by benrubson** [comment]
@mhogomchungu, to be as fast as possible, as a first solution, did you try to compile it by yourself ?
It's rather easy, as per [the Wiki instructions](https://github.com/vgough/encfs/wiki/Cygwin).

For runtime, you should be able to run the compiled binary out of the Cygwin files' tree.
You will however require some DLLs such as `cygwin1.dll` : missing ones will be notified when you'll start `encfs`. Just copy them from Cygwin file's tree next to the binary, it should do the trick 👍
And of course you'll still need WinFsp, as the "FUSE layer".

Not sure how a Windows binary would have to be distributed ?
- directly as a Cygwin package, among all the other Cygwin packages ?
- here in EncFS repository, with required DLLs ? As both 32 and 64bits ?
- something else ?

Every solution would require for sure some additional maintenance.

**Comment by mhogomchungu** [comment]
Best thing in my opinion is to distribute the binary here as one of the released files.

Best solution will be to statically build everything to end up with a single executable. This way,the user can put the executable anywhere on their system is just use it.

Second best thing is to ship the binary and all of its dependencies in a folder. An installer will be best used here. 

With both alternatives, it will probably be necessary to ship 32 bit and 64 bit packages.

Will see if i can build it locally.

**Comment by mhogomchungu** [comment]
I managed to build it and i think i found a bug

```
C:\encfs-master\build\encfs>encfs -f C:\cipher Z:
A drive is prefered for mouting, so a path like /cygdrive/x should rather be used. Mounting anyway.
EncFS Password:
Cannot create WinFsp-FUSE file system: invalid mount point.

C:\encfs-master\build\encfs>
```
A drive letter of something like ```Z:``` is rejected as it wants something like```Z```. I think the first way is the correct way when writing drive letters.

**Comment by benrubson** [comment]
Simply use `/cygdrive/z` as mount point, as proposed 👍

**Comment by mhogomchungu** [comment]
```C:\cipher``` does work.
```/cygdrive/XYZ``` seems wrong because it exposes an internal detail of the tool. Will these paths continue to work when encfs removes its dependency on cygwin?

git version of SiriKali now works with encfs on windows. 

Is the "-u" option supposed to work? It doesnt work here on windows when using it to unmount a volume and i have never used it on Linux since "fusermount" works there and "umount" works on MACOS.

![screenshot 17](https://user-images.githubusercontent.com/3496115/38709529-333adf20-3ec4-11e8-8f4b-85b6db0a8745.png)

**Comment by mhogomchungu** [comment]
SiriKali currently reads a register value[1] to find out where encfs is installed and this suggests an installer was involved when encfs was installed on a user's machine.

I can create an installer for 32 bits windows if you guys want.

[1] https://github.com/mhogomchungu/sirikali/blob/6de2840606c3856060381d559b96b54fdca9ad24/src/winfsp.cpp#L171-L173

**Comment by benrubson** [comment]
> Best solution will be to statically build everything to end up with a single executable.

Unfortunately not possible, Cygwin DLLs can't be statically linked (as per my last readings).

> `/cygdrive/XYZ` seems wrong because it exposes an internal detail of the tool.

Not really, this is just `Z:` translated to how Cygwin handles paths.
But I agree we could add the `Z:` writing to be correctly handled by EncFS.
I'll push a PR.

>Will these paths continue to work when encfs removes its dependency on cygwin?

It's not planned to remove Cygwin dependency for now, as it would require some quite important work to translate UNIX functions (`readdir` etc...) to Windows ones.

> git version of SiriKali now works with encfs on windows.

Excellent, nice job 👍 

> Is the "-u" option supposed to work?

Yes, it works, you have to provide same path as you provided while mouting, for example :
`encfs -u /cygdrive/z`
On Windows you also need `pkill` binary, in `/usr/bin` directory :
https://github.com/vgough/encfs/commit/1a8a5e02465af7dd7a863edfc185060614bcda30#diff-d629907b59574b8da8d9b05e5bba64e0R1745

> I have never used it on Linux since "fusermount" works there and "umount" works on MACOS.

You can now use it everywhere 👍 

> I can create an installer for 32 bits windows if you guys want.

Or embed EncFS binaries into SiriKali ?
Not sure what's the best way here.
Installer would have to be maintained and everything rebuilt / repackaged for each release, which would be something new here.
@rfjakob your thoughts ?

**Comment by mhogomchungu** [comment]
Supporting windows almost by definition implies providing binary packages. @rfjakob provides binary packages for linux in his gocryptfs project and i dont see why he will object with encfs doing the same for windows.

I think this[1] part of the code is wrong, if "/usr/bin/pkill" is not found, a user will get an error that says 
```Filesystem unmount failed: no such file or directory``` and that error is not very informative(I was getting this error message). The code should check for the presence or ```pkill``` and give a descriptive error if the tool is found to not be present.

[1] https://github.com/vgough/encfs/commit/df7403c256084a620d47f5f550544f8e0f0fabf6#diff-d629907b59574b8da8d9b05e5bba64e0R1751

**Comment by rfjakob** [comment]
I'm traveling right now, will think abou it mid next week. A few gut feelings:
- a binary release should be tested on the most common windows versions
- is there a CI service for windows?
- can packaging an installer be automated?

**Comment by benrubson** [comment]
> But I agree we could add the Z: writing to be correctly handled by EncFS.
I'll push a PR.

Done in #509 / #510.

**Comment by rfjakob** [comment]
After thinking a bit about it, I think we should

1) Try to have an Installer for Windows - @mhogomchungu you said you could help with that, would be very appreciated. Publish the installer with the next or next+1 version as we see fit, maybe marked "BETA" or something. I expect lots of user trouble and questions, so maybe limit exposure at first.

2) If at all possible, the Windows installer should build on appveyor to make it reproducible and so that you don't need a local Windows box to make an EncFS release. This would otherwise be a long time burden.

3) We should clarify the relation between EncFS and [EncFSMP](https://encfsmp.sourceforge.io/). Why should a user choose on over the other? It seems that EncFSMP uses Pismo File Mount

> The file system component that allows EncFSMP volumes to be mounted is called Pismo File Mount and is developed by Pismo Technic Inc.. Other than that, EncFSMP is 100% open source.

which is probably the fundamental technical difference. It also seems to provide a GUI on [Windows](https://encfsmp.sourceforge.io/docs_win.html) and [MacOS](https://encfsmp.sourceforge.io/docs_osx.html).

@benrubson can you add a paragraph to the Windows wiki page?

**Comment by benrubson** [comment]
There's also [EncFS4win](https://github.com/jetwhiz/encfs4win). I'm not sure there are others.

**Comment by benrubson** [comment]
> @benrubson can you add a paragraph to the Windows wiki page?

Done, see the [Wiki](https://github.com/vgough/encfs/wiki).

**Comment by rfjakob** [comment]
Very good! I changed the wording a little, maybe clearer ([diff](https://github.com/vgough/encfs/wiki/Windows/_compare/b4c4d5b5118ac77aed8b4f4a924424c20dc8a9bb...10dd6581c2c653c7280ebfce14093bd9618f3920))
`"Native" with Cygwin` ---> `Mainline EncFS with Cygwin`

**Comment by mhogomchungu** [comment]
The installer for windows is done.

The installer script is here[1] and the installer binary is here[2].

From the script, the ```MySourcePath``` variable has info of where encfs filesto be packaged are located, the ```MyOutPutPath``` holds a path to where to create the installer.

The installer is build with this[3] tool.

[1] https://github.com/mhogomchungu/encfs/blob/master/windows-installer.iss
[2] https://github.com/mhogomchungu/encfs/releases/tag/v1.9.4
[3] http://www.jrsoftware.org/isinfo.php

**Comment by mhogomchungu** [comment]
According to this[1] line in a pull request,encfs will not use pkill in the install folder because it specifically looks for it some place else. This reason is also why SiriKali does not use -u option to unmount encfs volumes on windows[2]

It will be nice if encfs will be able to detect if winfsp is installed and report the problem if it isnt. I requested the same thing with securefs here[3].

[1] https://github.com/vgough/encfs/pull/507/commits
/0c9e4087181b7fcd1eac8a9fe755eb374cba6dea#diff-d629907b59574b8da8d9b05e5bba64e0R1752
[2] https://github.com/mhogomchungu/sirikali/blob/587c5999ac637836dca6be017327ecf253141cf8/src/winfsp.cpp#L387
[3] https://github.com/netheril96/securefs/issues/53

**Comment by mhogomchungu** [comment]
securefs uses winfsp API[1] to load winfsp module and gives a descriptive error when it fails to do so.

I think ```fuse_main```[2] should fail if winfsp is not installed.

Will add pkill to the installer.

[1] https://github.com/netheril96/securefs/blob/3ed2bcb323ef0c9e420d7035f9e4efe478d90ce3/sources/win.cpp#L1077

[2] https://github.com/vgough/encfs/blob/cc256a657eefc37d27cb180bc901edbcb5c2789b/encfs/main.cpp#L788

**Comment by mhogomchungu** [comment]
The installer now has pkill bundled in.

Can i make a pull request for the installer script?

encfs properly detects if winfsp is not installed and gives a descriptive error message as shown below.
```
C:\Program Files (x86)\Encfs\bin>encfs.exe C:\vault Z:
EncFS Password:
cygfuse: initialization failed: winfsp-x86.dll not found
```

**Comment by rfjakob** [comment]
Yes, go ahead with the PR!

**Comment by benrubson** [comment]
> With both alternatives, it will probably be necessary to ship 32 bit and 64 bit packages.
> I can create an installer for 32 bits windows if you guys want.

Don't you face https://github.com/billziss-gh/winfsp/issues/161 with Cygwin 32 bits @mhogomchungu ?
I then just advised for Cygwin64 in the Wiki page.

**Comment by mhogomchungu** [comment]
My understanding is that winfsp console applications can not be sent to the background. More info on this is here: https://github.com/netheril96/securefs/issues/60

**Comment by benrubson** [comment]
The Cygwin ones can :

https://github.com/netheril96/securefs/issues/47#issuecomment-347957579 :
> (...)
[For this reason `fuse_daemonize` is a no-op when running WinFsp in native Windows. It actually works and turns the process into a Cygwin daemon when running under Cygwin.]

And :
https://github.com/billziss-gh/winfsp/wiki/SSHFS-Port-Case-Study

And according to what I encounter (https://github.com/billziss-gh/winfsp/issues/161), it only fails with Cygwin32 on 64 bits OS.

**Comment by mhogomchungu** [comment]
I didnt notice the problem because i always run encfs in SiriKali as a foreground process: https://github.com/mhogomchungu/sirikali/blob/50be722ec6829d4410300315d1bab2afbf9e1bfb/src/siritask.cpp#L462

**Comment by mhogomchungu** [comment]
The -u option of encfs now works and SiriKali is using it: https://github.com/mhogomchungu/sirikali/blob/85d652d74b22f55989d69d0205852f52903eb81b/src/winfsp.cpp#L403

**Comment by mhogomchungu** [comment]
No, i already made promises to release SiriKali on the first of May but i released it a bit early because i will be traveling on May first and will probably be a bit very busy for a while.

I decided to go with a manual build for the moment to have it "out there" and do things "properly" later one when things calm down.

**Comment by benrubson** [comment]
> Btw, did you manage to already experiment a bit with AppVeyor ?

As stated in https://github.com/vgough/encfs/issues/326#issuecomment-591683907, I should have a look at this, using Cirrus or Travis 👍
