### ISSUE TITLE
Request to let encfs work WITH gocryptfs.

### ISSUE THREAD

**Issue by ccchan234** [vgough/encfs#518]
I am a paranoid and wish I could DOUBLE encryption
my things on cloud.

encfs is good, gocryptfs also good.
But why not BOTH?

Now I tried using encfs for outer layer but then
gocryptfs need the .conf file put in the same
folder as .encfs6.xml.
Yet the dokan or something make the FUSE drive
with only 512MB, so files > 512MB could not be
encrypted.

The reverse of using gocryptfs on outside,
as encfs4win seems dont allow user-choose
location (in windows), the above trick cant be used
and I cant make it run.

Thanks for the authors and others.

Thank you.

ps:
Double Encryption, for the Win!
http://blog.dustinkirkland.com/2014/05/double-encryption-for-win.html
Someone's thought after openSSL's bug of heartbleed.

my system:
win ver of encfs: encfs4win
win ver of gocryptfs: cppcryptfs

**Comment by benrubson** [comment]
Hi @ccchan234,

With EncFS you can use `ENCFS6_CONFIG` environment variable to put configuration file somewhere else.
With EncFS 1.9.5, we also added `-c` which does the same thing.
I hope this could help you.

As for now encfs4win is not yet built upon EncFS 1.9.5.
You could also choose to build EncFS with Cygwin to get last features (see Wiki).

**Comment by ccchan234** [comment]
I made a wordpress page:
https://wordpress.com/page/bullshitmanblog.wordpress.com/73

will try to summarize my trial and errors at a user level.

**Comment by ccchan234** [comment]
Thx for reply.

But akaik it's a GUI for multi solution.

But my problem now is that the solutions are NOT compatible by SOME reason (I am not a programmer).

So I could just try combination of existing softwares and report.

thanks

(PS I will read about sirikali and report if it help, thx)

**Comment by benrubson** [comment]
SiriKali links to a build of EncFS (1.9.5) in its documentation.

**Comment by benrubson** [comment]
There should be no reason both can't work together.

I gave a quick test.
gocryptfs ([cppcryptfs](https://github.com/bailey27/cppcryptfs) 1.4.0.15) crypted folder `enc` mounted to `X:`.
EncFS (1.9.5) crypted folder `X:` mounted to `Y:`.
Sounds like it works 👍 

![screen shot 2018-05-03 at 08 58 24](https://user-images.githubusercontent.com/6764151/39563630-4df59ae2-4eb1-11e8-8cd7-9744167f880a.png)

**Comment by ccchan234** [comment]
I use the same ccpcryptfs, which use dokan.
yet I use encfs4win, which also use dokan.

the encfs1.9.5 with cygwin is using winfsp I think.

i will try later to figure out if it is the problem.

Thx very much for helping.

**Comment by ccchan234** [comment]
it seems encfs 1.9.5 that release ~THREE days ago is the 1st release for cygwin?

so in my view, encfs4win is more mature... yet i am willing to change into whatever can give what I want.

thx

**Comment by benrubson** [comment]
Yes it is.
Of course @ccchan234 you should test by yourself and choose the right solution according to your needs and findings.

Feel free to close this issue if/when you don't have no more question regarding EncFS 👍 
Thx !

**Comment by ccchan234** [comment]
Hi~
Thanks MUCH for help because I think I solved.

I tried again.
Previous attempt:  "unenc folder" mount to W: , then W:\ mount to Y:
(this failed for outer-encfs, inner-gocryptfs).
BUT if i make a W:\i-xxxxx and mount W:\i-xxxxx to Y:
it WORKed.

seems with the additonal folder,
outer-encfs-inner-gocryptfs
AND the outer-gocryptfs-inner-encfs will work.

thanks again otherwise I have given up.

ps:
my system
64b, win7 pro.
encfs4win 1.10.rc13
cppcryptfs.1.4.0.15

**Comment by ccchan234** [comment]
ps: so if u simply put the 2nd container directly in 1st container's drive letter without a folder,
say w:\

then when gocryptfs is inner, it will only have 512MB free.
when encfs is inner, it simply wont mount.

my problem now is...

which one be the outer encryption layer is better? or same at all?
