### ISSUE TITLE
Google File Drive Stream -Encfs

### ISSUE THREAD

**Issue by GerhardtCT** [vgough/encfs#525]
After upgrading from Google Drive to Drive File Stream, Encfs is giving me error messages and cannot open files.
Assert failure at f:/projects/encfsMP/src/encfs/MACFileIO.cpp:225 -- MAC comparison failure, refusing to read
How can I fix this problem?
Thanks

**Comment by ccchan234** [comment]
from what I see u are using encfsMP,

i think you should ask in encfsMP's forum instead?

this forum is for the ORIGINAL encfs, even NOT the encfs4win.

the author from encfsMP may implement encfs differently,
so other author May not know what's happening?

thx

**Comment by rfjakob** [comment]
Yes, sorry, I have to confirm what @ccchan234 said. I cannot help with EncfsMP on Windows :/
