### ISSUE TITLE
fusermount: Operation not permitted (GuixSD)

### ISSUE THREAD

**Issue by Ambrevar** [vgough/encfs#527]
On [GuixSD](https://www.gnu.org/software/guix/) encfs fails to mount anything:

```
> encfs -v /home/ambrevar/temp/exp/foo  /home/ambrevar/temp/exp/foo_dc
VERBOSE Root directory: /home/ambrevar/temp/exp/foo/ [main.cpp:686]
VERBOSE Fuse arguments: (daemon) (threaded) (keyCheck) encfs /home/ambrevar/temp/exp/foo_dc/ -o use_ino -o default_permissions  [main.cpp:687]
VERBOSE found new serialization format [FileUtils.cpp:299]
VERBOSE subVersion = 20100713 [FileUtils.cpp:313]
VERBOSE checking if ssl/aes(3:0:2) implements ssl/aes(3:0) [Interface.cpp:103]
VERBOSE allocated cipher ssl/aes, keySize 24, ivlength 16 [SSL_Cipher.cpp:395]
VERBOSE useStdin: 0 [FileUtils.cpp:1660]
EncFS Password: 
VERBOSE checking if ssl/aes(3:0:2) implements ssl/aes(3:0) [Interface.cpp:103]
VERBOSE allocated cipher ssl/aes, keySize 24, ivlength 16 [SSL_Cipher.cpp:395]
VERBOSE cipher key size = 44 [FileUtils.cpp:1673]
VERBOSE checking if nameio/block(4:0:2) implements nameio/block(4:0) [Interface.cpp:103]
fusermount: mount failed: Operation not permitted
fuse failed.  Common problems:
 - fuse kernel module not installed (modprobe fuse)
 - invalid options -- see usage message
VERBOSE Allocating 41 locks for OpenSSL [openssl.cpp:47]
```

Fuse is fine (I can use ntfs-3g).  It looks like a permission issue.  Any idea?

**Comment by rfjakob** [comment]
fusermount needs to have the setuid bit - this is how it looks at my box:
```
$ ls -l /usr/bin/fusermount /dev/fuse
crw-rw-rw-. 1 root root 10, 229 Jun  1 22:06 /dev/fuse
-rwsr-xr-x. 1 root root   32848 Feb  7 11:29 /usr/bin/fusermount
```
Could you check? That ntfs-3g works is a counter-argument to a missing setuid bit, though. Maybe it does not user fusermount but has it's own wrapper?

**Comment by Ambrevar** [comment]
Fixed it!
So basically `fuse` and `fusermount` are properly installed on Guix and `fusermount` has the setuid bit:
```
> ll /run/setuid-programs/fusermount
-r-sr-sr-x   1 root           root          37k 2018-06-02 10:03 /run/setuid-programs/fusermount
```

The issue is that I had installed fuse in my user profile, which then does not have the setuid bit while taking precedence of `/run/setuid-programs/fusermount`.

Removing `fuse` from my user profile fixed it!

**Comment by ElBatou** [comment]
Hi I'm facing a similar issue
`-rwxr-xr-x 1 jorge jorge   30800 ago 11  2016 /bin/fusermount
crw-rw-rw- 1 root  root  10, 229 ago 15 07:19 /dev/fuse`

Can you share with me what how to remove the fuse from your user profile? I'm just starting with Linux and this issue its way over my current knowledge.

**Comment by Ambrevar** [comment]
Do you use Guix?  My issue was Guix-specific.
I just removed it from my user profile:

    guix remove fuse

**Comment by Ambrevar** [comment]
Or maybe

   guix remove ntfs-3g

I don't remember.

**Comment by ElBatou** [comment]
Thanks! i'm not sure what could be the issue but the error its very similar and your post could give me some direction on what to check next
