### ISSUE TITLE
kernel 4.17.4 hang

### ISSUE THREAD

**Issue by didierga** [vgough/encfs#529]
Hi,
I am not sure this is an encfs issue but FYI I just opened https://bugzilla.redhat.com/show_bug.cgi?id=1598462 about kernel hand using kernel 4.17.4
Best regards.

**Comment by Vascom** [comment]
Hang occurs on nonencrypted drive?

**Comment by didierga** [comment]
I cannot be affirmative so my answer is:
- on this external drive I use mostly encrypted directory
- hang occurred writing or reading files in this encrypted directory
- until now I have been unable to get hang occurrence writing or reading files in nonencrypted directory on the same drive

**Comment by didierga** [comment]
This hang occurs also writing on NO encrypted directory.
