### ISSUE TITLE
exec issue on musl encfs build

### ISSUE THREAD

**Issue by ScrumpyJack** [vgough/encfs#53]
running encfs i get this:

Error relocating /usr/lib/libencfs.so.6: __cxa_throw_bad_array_new_length: symbol not found

Can provide environment to repeat this and any other information you need.

env:linux 3.14.27-2-grsec, musl-1.1.5, fuse-2.9.3, libencfs.so.6.0.2

**Comment by vgough** [comment]
Sounds like a mismatch between the compiler used to build libencfs, and the C++ runtime library being used.  That symbol comes from the stdc++ library.  Is musl replacing stdc++ in your build?

**Comment by ScrumpyJack** [comment]
building encfs with libstdc++ fix this issue. thanks
