### ISSUE TITLE
Keep `rootdir` in sync, while mounted

### ISSUE THREAD

**Issue by btwe** [vgough/encfs#535]
I never had troubles to rsync an `encfs-rootdir` from host A to B. Even though A was mounted.

Now my question is, is it supported to keep the root directories of host A and B in sync (technically syncthing) even when the directories may both be mounted?

Many thanks,

**Comment by benrubson** [comment]
If you perform 2-ways syncing, you may end with some data corruption.
If you perform one-way syncing (from A to B), directories may be mounted on the 2 sides. Be then sure to mount with cache options disabled on B side.

**Comment by jjakob** [comment]
There's no way to do 2-way syncing? With cache on both sides disabled perhaps?

What if we make sure to only write to a certain file (directory) at one end while keeping the other end read-only?

**Comment by benrubson** [comment]
> There's no way to do 2-way syncing? With cache on both sides disabled perhaps?

Dangerous as said above, without a mechanism to lock file being written, which is not covered.

> What if we make sure to only write to a certain file (directory) at one end while keeping the other end read-only?

This will work, see my [previous message](https://github.com/vgough/encfs/issues/535#issuecomment-445548740).
