### ISSUE TITLE
I got this error message: "Bad message"

### ISSUE THREAD

**Issue by Oscar65** [vgough/encfs#539]
This is the output running cat:

`[user@pc ~]$ LC_ALL=C cat folder/file.txt~`
`    cat: folder/file.txt~: Bad message`

I have Archlinux kernel 4.19.4-arch1-1-ARCH, encfs 1.9.5-2, openssl 1.1.1-1, fuse2 2.9.8-1 and tinyxml2 7.0.1-1.

After many years using encfs this is the first time that I got an error and lost data.

Days ago I started to make backup in MEGA with MEGAsync and it created .debris folder inside the encripted folder (.folder).

I don't see the folder .debris with `ls -la folder`, but I can see other hidden folder (.Trash-1000). With `ls -la .folder` I can see the .debris folder. MEGAsync runs without running  `$ encfs .folder folder`

 Could be this the cause? Creating folders and files directly in .folder could damage data?

Thanks in advance
Oscar

**Comment by Oscar65** [comment]
Researching I found that MEGAsync download files from MEGA that usually are backup files (end with ~). Today all files in .debris/2018-12-07/ folder return error "Bad message" when I try to read them minus one.

I don't know why these files return this error. In theory, they are correct files, but from another date.

The file that doesn't return error is also in another folder from another date inside .debris folder. If I copy this file and cat the file in folder mounted I can see the old file and doesn't return "Bad message" error. I don't know why the others return this error.

I think that MEGAsync is not the best tool for backup encfs folders. I will deactivate sync for this encfs folder and I will upload the encfs folder every time I make changes.

**Comment by rfjakob** [comment]
Hmm. Do you have file name encryption enabled?

**Comment by Oscar65** [comment]
I selected pre-configured paranoia mode.

**Comment by benrubson** [comment]
Same issue as in #141 you think @rfjakob ?

**Comment by benrubson** [comment]
_Closing this for now, feel free to re-open if you still face your issue._
