### ISSUE TITLE
Encfs occasionally doesn't recognize correct password

### ISSUE THREAD

**Issue by lbaulig** [vgough/encfs#546]
I get the error that the volume key could not be decoded due to an incorrect password occasinally, even though I supply the exact same password (in fact for testing purpose, I simply saved the password in a file and copy/paste it) on both windows (encfs.win v1.10.1-RC14, based on 1.9.1) and on a Ubuntu 18.04 system (arm processor, odroid xu4) using version 1.9.2. I've have the encfs6.xml backed up and I know that they are not corrupted (because as I said sometimes it does work).
A reboot sometimes fixes this, and if it does, it usually works for the whole session. Even weirder than that, sometimes supplying an obviously wrong password first and than supplying the real one also fixes the problem. 
I've checked both whether ENCFS6_CONFIG is set, but it isn't (atleast for the user running it), and also if the filesystem is corrupt.
How can this happen and how to fix this?

**Comment by benrubson** [comment]
Still facing your issue ?
Or did you manage to solve this ?
