### ISSUE TITLE
Performance issue when storing chrome data dir on encfs mount

### ISSUE THREAD

**Issue by cherio** [vgough/encfs#556]
I launch chrome with its data directory stored in an encrypted encfs volume as 
`google-chrome --user-data-dir=/home/user/.config/google-chrome-private`. This brings not just chrome but the whole system to a crawl with long freezes and pauses between simple actions like mouse clicks, mouse scroll, tab switch etc. This doesn't happen when chrome data dir is on a LUKS partition or in unencrypted space.

Chrome is surely a resource intense application. It uses special socket files, it performs very frequent reads and operates on a large set of small files.

I experience the same issues both in Ubuntu 16.04 (v 1.8.1) & 18.04 (v 1.9.2).

EDIT: possibly a significant nuance. `/home/user/.config/google-chrome-private` is a symlink to a directory on an encfs volume.

**Comment by benrubson** [comment]
Try using EncFS normal mode instead of paranoia mode, if you use the later ?

**Comment by benrubson** [comment]
_Closing this, feel free to re-open if still facing the issue..._
