### ISSUE TITLE
Mounted FS not showing in Desktop Environment

### ISSUE THREAD

**Issue by xserty** [vgough/encfs#558]
Hi guys, I've an issue that is probably nothing to do with encFS, but was not sure where else to post it.
I have two encrypted directories and whichever I mount first show's up in the desktop environment (accessible through Nemo file manager, or the Removable Devices applet, etc.).
The second encrypted directory mounted is not accessible through normal GUI. It's as if it was not mounted. Even though it's accessible through CLI.
I tried Cinnamon and Mate desktop environments, but same result.
I've following system:
- Debian 10
- 4.19.0-6-amd64
- encfs 1.9.5-1+b1  amd64
- Mate 1.20.4-2 / Cinnamon 3.8.1-2
Any help or pointers to other forums welcome!
Xserty

**Comment by benrubson** [comment]
Try giving a different FS name to every mounted FS ?
Adding `-o fsname=<FSNAME>` to your _encfs_ command.

**Comment by benrubson** [comment]
_Closing this, feel free to reopen if needed..._
