### ISSUE TITLE
how to brute force the key stored in `.encfs6.xml`

### ISSUE THREAD

**Issue by mrVanDalo** [vgough/encfs#563]
This might be a strange issue, but I lost my `.encfs6.xml` file and I tried everything to get it back. (I did not properly backup that file). I created the a new `.encfs6.xml` by accident, because syncthing was not started, once syncthing started the `.encfs6.xml` was overwritten on all my other servers. So kids **always** backup the `.encfs6.xml`!

Now to my question, I have a lot of encrypted data now, which I would love to see decrypted at some point in time (maybe in 20 years). How would you try to recover the key needed to decrypt the data?

I guess it makes no sense to randomly generate the `.encfs6.xml` and try to decrypt the folder, and verify if a file looks like it should look.

**Comment by benrubson** [comment]
Unfortunately, due to how the encryption key is randomly generated, I think you're stuck 😕

**Comment by mrVanDalo** [comment]
@benrubson yes, but my question was more in the direction on how would I verify very quickly if the key is wrong or correct? So I can brute force it in a few years maybe.

**Comment by rfjakob** [comment]
The [SSL_Cipher::readKey()](
https://github.com/vgough/encfs/blob/ce200c83f0d9b5309f3e8fae7283c4cad598f637/encfs/SSL_Cipher.cpp#L590) function seems to be what decrypts the key using the password.

Interesting here is:

    // First N bytes are checksum bytes

However, that checksum is quite weak and only 4 bytes long (MAC32).

So this checksum can be used to quickly check if a key **could** be correct or is definitely incorrect. You will still have lots of possible keys that give the right MAC32, though. For those you need a second validation step, possilby trying to decrypt a file or a filename and looking at the content.

**Comment by mrVanDalo** [comment]
thanks, that sounds like a useful start.

**Comment by benrubson** [comment]
_Closing this for now, feel free to re-open if needed._
