### ISSUE TITLE
Unable to delete fille mounted on reverse

### ISSUE THREAD

**Issue by syaifulnizamyahya** [vgough/encfs#564]
encfs used:
encfs-1.9.5-x86_64-3cf.txz 

mount command:
echo mypassword | ENCFS6_CONFIG='/mnt/user/Cloud/skygmail/encfs/.encfs6.xml' encfs \
--reverse \
-S -o rw -o allow_other -o uid=99 -o gid=100 \
/mnt/user/Cloud/ijm/move/ \
/mnt/user/Cloud/ijm/.move/ 

problem when deleting file:
![PUTTY_FxTrHQ6e6w](https://user-images.githubusercontent.com/10744241/67611930-b9902280-f7d0-11e9-8ff8-5c9eaa38eeaf.png)

Please advise.
Thanks.

**Comment by benrubson** [comment]
Hi,
You should use `--reversewrite` instead of `--reverse` to enable write in reverse mode.

**Comment by syaifulnizamyahya** [comment]
I have updated the command to use reversewrite. Now im getting other error.
Here are my command.
```
echo Mount encrypted reverse
echo 258456 | ENCFS6_CONFIG='/mnt/user/Cloud/skygmail/encfs/.encfs6.xml' encfs \
--reversewrite \
--nocache \
-S -o rw -o allow_other -o uid=99 -o gid=100 \
/mnt/user/Cloud/ijm/move/ \
/mnt/user/Cloud/ijm/.move/ 
```
https://i.imgur.com/ZWVrxyS.png
As you can see from the putty, the files are in red color and have alias symbol at the end. The file actually doesnt exist. Either it has been deleted, or its something else altogether. I have thousands of not existing files in that state.

Thanks.

**Comment by syaifulnizamyahya** [comment]
![PUTTY_9ZBaxcqK0V](https://user-images.githubusercontent.com/10744241/67724396-d8cdc080-fa19-11e9-96aa-811faecf6ed0.png)
after run stat and ls -al

**Comment by syaifulnizamyahya** [comment]
![PUTTY_9ZBaxcqK0V](https://user-images.githubusercontent.com/10744241/67724855-5c3be180-fa1b-11e9-867c-8dad1e336683.png)
Im sorry. The file does exist. This are the file. Seems to me the file is a symbolik link. Any advise?

**Comment by syaifulnizamyahya** [comment]
By the way, what encfs reversewrite command to :
1. when reading symlinks file, follow it.
2. when editing symlinks file, follow it.
3. when deleting symlinks file, dont follow it. only delete the symlinks.

**Comment by benrubson** [comment]
This is what encfs does.

> Seems to me the file is a symbolik link. Any advise?

Yes these are symlinks. And this is what your `stat` command reports. Any problem with them ?

**Comment by benrubson** [comment]
_Closing this, feel free to re-open if needed._
