### ISSUE TITLE
Allow invalid filenames when writing to an encfs --reversewrite folder

### ISSUE THREAD

**Issue by fergalish** [vgough/encfs#565]
Hi all,
Use case is to synchronize a --reversewrite folder between one server and different clients.
The sync software is "syncthing", which:
(1) places some additional files called ".stignore" and ".stfolder" in the folder it is synchronizing.
(2) writes data to a temporary filename when syncing: ".syncthing.filename.tmp"

For issue (1) there is a workaround by having the --reversewrite folder as a subfolder of the sync folder, e.g. ./syncfolder/reversewritefolder
For issue (2) I have a workaround to save the temp file in the parent syncthing folder, then copy-and-delete to the correct place in the --reversewrite folder. However that could lead to corrupted data if an error occurred in the copy-and-delete stage.

So I wonder, is it possible for encfs to somehow store files that are written to a --reversewrite folder even when the filename or the file contents don't match the cipher and can't be decrypted?

More info at https://github.com/syncthing/syncthing/issues/2208.

**Comment by benrubson** [comment]
> So I wonder, is it possible for encfs to somehow store files that are written to a --reversewrite folder even when the filename or the file contents don't match the cipher and can't be decrypted?

Unfortunately no.
But you could encrypt your filename (thanks to `encfsctl` binary for example), and then write this encrypted filename into your `--reversewrite` directory. Filename would then be correctly decrypted into the plain directory.
