### ISSUE TITLE
Reverse man page description reversed

### ISSUE THREAD

**Issue by Keisial** [vgough/encfs#566]
The  man page of `--reverse` option states:
> This can be useful for creating remote encrypted backups, where you do not wish to keep the
local files **un**encrypted.

However, I think it is wrong and it should be the opposite:
> This can be useful for creating remote encrypted backups, where you do not wish to keep the
local files encrypted.

Storing the local files in encrypted form is the _normal_ usage, with `--reverse` letting you have the local files unencrypted, which is suitable for users that **not** wish to keep the
local files _encrypted_.

**Comment by benrubson** [comment]
IMO the man page is OK :

> This can be useful for creating remote encrypted backups, where you do not wish to keep the
local files unencrypted.

_where you do not wish to keep the local files unencrypted_ means that you don't want to have your files unencrypted on the remote location.

@rfjakob you understand the same ? Thx 👍

**Comment by rfjakob** [comment]
Hmm, I think I agree with @Keisial here

**Comment by benrubson** [comment]
_This can be useful for creating remote encrypted backups, where you do not wish to **store** the local files encrypted._

Would this be OK ?

**Comment by rfjakob** [comment]
Yes sounds good
