### ISSUE TITLE
MacOS: weird failure of CI

### ISSUE THREAD

**Issue by mouse07410** [vgough/encfs#568]
Could you please take a look at https://travis-ci.org/mouse07410/encfs/jobs/610664135 and help me figure why one test is failing?

**Comment by benrubson** [comment]
Strange, as if `rmtree($workingDir);` was failing here :
https://github.com/vgough/encfs/blob/7fc3730f67888106ade57a66d3da10a9f825d199/integration/normal.t.pl#L394-L403

Did you reproduce this issue, or can we close it ?

**Comment by mouse07410** [comment]
> Did you reproduce this issue?

No, current master (using my build script and your `FindFUSE.cmake`) passes CI tests.
