### ISSUE TITLE
Permission denied if unlocked inside a VirtualBox guest OS

### ISSUE THREAD

**Issue by ramfree17** [vgough/encfs#569]
I have an encrypted volume in my host OS (Manjaro 64-bit) where I place my work files which includes git workspaces.  If I decrypt and mount the volume while inside the guest OS (Ubuntu 19.04 64-bit), I cannot update the workspaces as the pull operations fails due to a permission denied in the .git/objects/pack/  directory. I checked that every directory starting from the workspace is owned by my guest OS user and that the permission is 777. I even did a recursive chmod and chown for good measure but the error still persists. 

If I rsync the workspace to outside the volume (i.e. /tmp ) then I can pull the updates and I can rsync it back without any issues. 

Does the volume retain any identity information of the original user that created the files and directories? Most if not all of the files in the volume is created and owned by my host OS user.

**Comment by benrubson** [comment]
Did you try to git-pull from your guest OS, inside a plain host shared folder (so without EncFS) ?
I wonder whether or not this issue could be a lock related issue in shared folders.

**Comment by ramfree17** [comment]
Hi,

   Yes I did try outside of a plain shared directory and a native
directory. Only the encfs-decrypted shared mount is exhibitin the  error. I
can create files (i.e. touch filename ) inside the encfs-hosted .git
repository which is puzzling because if its a user-level lock issue then I
shoudlnt be able to do that. It is as if git uses a different user when it
executes and hits a permission issue but I can't find any reference to that
either.

   Note:  I am unable to perform actual validation as this is happening in
my machine at home (host Manjaro, guest: Ubuntu) and I am away from it.

   Thanks.

**Comment by benrubson** [comment]
A hint perhaps, at least issue seems identical :
https://bugzilla.samba.org/show_bug.cgi?id=7151

**Comment by benrubson** [comment]
_Closing this, please re-open if still experiencing._
