### ISSUE TITLE
Mount encrypted external disk on a Mac

### ISSUE THREAD

**Issue by konstantinmiller** [vgough/encfs#572]
I've used to encrypt my external disks using EncFS on Linux. Now I switched to Mac and tried to decrypt and mount such an external disk on the Mac. However, it seems that on Mac, EncFS only supports encrypting/decrypting directories, not disks. Is that the case?

Is there a way I can decrypt an external disk that was encrypted using EncFS on a Mac?

**Comment by benrubson** [comment]
Even on Linux EncFS encrypts directories and files.
On MacOS, once your external disk is mounted, you certainly have the `.encfs6.xml` file stored at disk root.
If so, you'll have to run something like :
`encfs /Volumes/<your_disk_name> /your/mount/point`

**Comment by konstantinmiller** [comment]
Sorry for not reacting earlier, it has been a while, but I still can't access the external disk. 

When I connect the disk, the Disk Utility shows that it's mounted as `disk2s1`, and indeed with `ls /dev` I can see `/dev/disk2s1`. But when I do `encfs /dev/disk2s1 /some/mount/point` I get the error: `The directory "/dev/disk2s1/" does not exist. Should it be created? (y,N) N`.

Under `/Volumes` no new entry is created.

[By the way, @benrubson you are writing that "Even on Linux EncFS encrypts directories and files". Well, my question is not about directories and files, it's about accessing an external USB disk that has been encrypted with EncFS.]

**Comment by konstantinmiller** [comment]
Here is a screenshot of the Disk Utility after connecting the external disk:

<img width="1552" alt="Screenshot 2020-11-15 at 15 35 43" src="https://user-images.githubusercontent.com/2629945/99187686-63ce4580-2758-11eb-96ce-d064e285ca94.png">
