### ISSUE TITLE
Different encryption result with --reverse

### ISSUE THREAD

**Issue by noma** [vgough/encfs#575]
I tried creating an encrypted view using `--reverse` on exact copies, including the `.encfs6.xml` of the same folder on different machines using different encfs versions.

encfs version 1.8.1
encfs version 1.9.2

When I compared random files using `md5sum` from the two encrypted views, I got different hashes on both systems. The files do actually differ, while the size is the same.

Is the encryption result not stable across versions, or is another input - other than the file-content and the `.encfs6.xml`, e.g. the file's metadata or something, used for the encryption?

Thanks.

**Comment by benrubson** [comment]
Depending on the chosen options, `--reverse` can use the inode number of the files to encrypt them.
And of course, they are certainly different across your different machines.
Disable `Per-File Initialization Vectors` and you should get consistent results (see man page which explains this).
