### ISSUE TITLE
Is it possible to choose the number of kdfiterations during creation?

### ISSUE THREAD

**Issue by 1-eric** [vgough/encfs#586]
I ask this because I want to share an encfs directory between my desktop computer and my Android phone. Kdfiterations around 100k work without problems, but my desktop computer always creates encfs directories with kdfiterations of around 300k.

**Comment by benrubson** [comment]
As per the man page :
```
Key Derivation Function
       As of version 1.5, EncFS now uses PBKDF2 as the default key derivation
       function.  The number of iterations in the keying function is selected
       based on wall clock time to generate the key.  In standard mode, a
       target time of 0.5 seconds is used, and in paranoia mode a target of
       3.0 seconds is used.
```

Unfortunately it's not possible to tune this for now.

**Comment by benrubson** [comment]
https://github.com/vgough/encfs/issues/496
