### ISSUE TITLE
test script does not run on openSUSE 13.1

### ISSUE THREAD

**Issue by Aikhjarto** [vgough/encfs#59]
I'm using openSUSE 13.1 64-bit. With the latest 1.8 of encfs I'm able to compile and use encfs. Howerver the test script fails on my openSUSE with an "undefined" symbol error.

Build was done with:
autoreconf -fiv
./configure
make

Then encfs test was invoked with:
./encfs/test
Supported Crypto interfaces:
AES ( ssl/aes 3:0:2 ) : 16 byte block cipher
 - key length 128 to 256 , block size 64 to 4096
Blowfish ( ssl/blowfish 3:0:2 ) : 8 byte block cipher
 - key length 128 to 256 , block size 64 to 4096

Testing interfaces
AES, key length 128, block size 256:  /home/thomas/home:Aikhjarto:branches:security/encfs/encfs-1.8/encfs/.libs/test: symbol lookup error: /home/thomas/home:Aikhjarto:branches:security/encfs/encfs-1.8/encfs/.libs/test: undefined symbol: _ZN12StreamNameIOC1ERKN3rel9InterfaceERKSt10shared_ptrI6CipherERKS4_I17AbstractCipherKeyE

**Comment by rfjakob** [comment]
Does that also happen on a fresh clone?

**Comment by Aikhjarto** [comment]
Sry, to bother you. I found the problem myself using strace.
The colons in my build-path (introduced by the openSUSE build service) made a mess in my LD_LIBRARY_PATH environmental variable. Building testing in a path without colons works fine.
