### ISSUE TITLE
Encrypted side on case insensitive file system. Possible data corruption?

### ISSUE THREAD

**Issue by gianfrus** [vgough/encfs#608]
The encrypted side of an EncFS directory pair clearly assumes a case-sensitive filesystem for file names.
While agreeing on the fact that **case-insensitivity is madness**, in the case we are forced to have the encrypted side on a case-insensitive filesystem (for file names) is it possible to incur in data loss/corruption, given the case in which a new encrypted file name could differs from an exiisting one only in some uppercase/lowercase letters? Could be considered reasonably unlikely or not after all?

**Comment by rfjakob** [comment]
You can select base32 on fs creation.

In any case, collisions are very unlikely, check https://github.com/rfjakob/gocryptfs/issues/466 for numbers.
