### ISSUE TITLE
--nocache option not mentioned in man page

### ISSUE THREAD

**Issue by Aikhjarto** [vgough/encfs#61]
Based on the discussions about --nocache in #60, I noticed that this option is not mentioned in the man page.

**Comment by rfjakob** [comment]
Hehe, good find! I will add it.

**Comment by Aikhjarto** [comment]
Just another thing in the man page: in the --reverse section the config file is mentioned as
```
/home/me/.encfs5
```
but IMHO should be 
/home/me/.encfs6.xml

**Comment by rfjakob** [comment]
Both fixed in encfs-next (
https://github.com/rfjakob/encfs/commit/021d60c8e5ef7c764b7e5399051ed3325adf8d12 ), thanks!
