### ISSUE TITLE
encflsctl can't decode files with hyphen "-" 

### ISSUE THREAD

**Issue by desgua** [vgough/encfs#610]
encfsctl can't decode files that have '-' in their name.    
Example:   
$ encfsctl decode --extpass='secret-tool lookup secret' /home/desgua/encfsroot/ '-2JcGEI1lJib0fPXPPtbAPtAJ'
$ decode: invalid option -- '2'                                                                                                          
2020-06-04 16:06:43,411 WARNING getopt error: 63
decode: invalid option -- 'J'                                                                                                          
2020-06-04 16:06:43,411 WARNING getopt error: 63
decode: invalid option -- 'c'                                                                                                          
2020-06-04 16:06:43,411 WARNING getopt error: 63
decode: invalid option -- 'G'                   
etc

**Comment by ikonopistsev** [comment]
You may use interactive mode:
encfsctl decode --extpass='secret-tool lookup secret' /home/desgua/encfsroot 
without 4th arg ('-2JcGEI1lJib0fPXPPtbAPtAJ')

**Comment by desgua** [comment]
That solves this issue. Thank you so much!
