### ISSUE TITLE
encfsctl change password with shell script

### ISSUE THREAD

**Issue by Jemyy-AR** [vgough/encfs#614]
is there any way to change the password of the encrypted files with **encfsctl** and shell script?
I handle decrypting the files with **--extpass** option in **encfs** command . so is there any option like this to change the password?

**Comment by Francewhoa** [comment]
Command to change the password using a shell script: 

`$ encfsctl passwd ~/.name`

Assumptions

* Assumes in this example above, `~/.name` is the path to the directory which contains the encoded files. The tool will ask for your current password and afterwards, you will be able to set a new one. 

* Assumes this command above is for changing the password of a directory encrypted by EncFS

Thanks to ArchLinux's wiki for this at https://wiki.archlinux.org/index.php/EncFS#Changing_the_password
https://archive.md/eghGn

Related discussion at https://serverfault.com/questions/403820/changed-encfs-password-but-filenames-didnt-change

**Comment by ojamin** [comment]
@Francewhoa Unfortunately not actually an answer to the question as your recommendation prompts for a password rather than allowing the promptless embedding in a shell script. (Made it here trying to answer the same question)

**Comment by ojamin** [comment]
@Jemyy-AR in case you didn't come across it already, your probably looking for:
echo -e "oldpass\nnewpass" | encfsctl autopasswd /my_encfs/

**Comment by Jemyy-AR** [comment]
> 
> 
> @Jemyy-AR in case you didn't come across it already, your probably looking for:
> echo -e "oldpass\nnewpass" | encfsctl autopasswd /my_encfs/

Dear @ojamin tha is what I exactly wanted.
Thanks deeply for your comment
