### ISSUE TITLE
Encfs stopped recognizing my config file

### ISSUE THREAD

**Issue by adam-devel** [vgough/encfs#617]
## Overview
i was using `encfs` on my "Arch Linux" consistently, until one day i did a new fresh install of "Arch Linux"; i backed up my encrypted folders, then — after installing Arch — i copied it back my home directory

## I tried
->  running `encfs ./myfolder.enc ./myfolder.mnt`
<-  i got a help message instead of an error message
- then i noticed `When specifying daemon mode, you must use absolute path`, so i decided to run it in the foreground (`-f`), and give it an absolute path anyways

->  i used the `-f` flag and gave absolute paths
<-  it started "Creating new encrypted volume", of course i canceled that; CTRL-C
- encfs is not aware this is an already encrypted folder, i though it probably tell the difference by looking for a configuration file, so i decided to explicitly give it the config file path `-c ./myfolder.enc/cryfs.config`

->  i ran `encfs -c ./myfolder.enc/cryfs.config ./myfolder.enc ./myfolder.mnt`
<-  i got this:
```
ERROR Failed to load config file ./myfolder.enc/cryfs.config
ERROR Found config file ./myfolder.enc/cryfs.config, but failed to load - exiting
```
------
i  took a look at the configuration file, i assumed it might be a JSON file or some kind of text format so i `cat ./myfolder.enc/cryfs.config`, the results tell me that, either the file is corrupt, or encfs use a binary format for the configuration file

is it a corrupt text or a binary file? is it corrupted?

if it is, can i still get my files back by knowing only the password?

**Comment by vigilancetech-com** [comment]
part of this looks like its related to my #616

**Comment by adam-devel** [comment]
yeah it is

**Comment by adam-devel** [comment]
sorry i should apologize, i was using `encfs` to decrypt a `cryfs` encrypted folder, i will close the issue now
