### ISSUE TITLE
security fixes ?

### ISSUE THREAD

**Issue by misterhsp** [vgough/encfs#621]
Are the issues of the alleged security concerns in git-repo already fixed? Or is there nothing to the whole thing?

thanks...

**Comment by Code7R** [comment]
What concerns, apart from the already known?

https://askubuntu.com/questions/813290/encfs-insecure-what-to-use-now
https://github.com/vgough/encfs/issues/314

**Comment by benrubson** [comment]
Duplicate of #604.
