### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by purpleidea** [vgough/encfs#624]
Hasn't seem any activity in a while. Is the maintainer active? Are they looking for a new one? It's very useful, but because it's security related, it would be great to know it's still getting some love. Maybe a port to rust might even be cool! Thanks!

**Comment by misterhsp** [comment]
I think yes, the project has probably passed away.

...

**Comment by benrubson** [comment]
See #314 and #604.

**Comment by misterhsp** [comment]
@purpleidea 
You should do the same as me. I switched to gocryptfs, because I don't think that there will be anything else happening here.

...
