### ISSUE TITLE
Missing translation files after building

### ISSUE THREAD

**Issue by svetlemodry** [vgough/encfs#63]
Hi,
I'm the [encfs](https://www.archlinux.org/packages/community/x86_64/encfs/) package maintainer for Arch Linux. After building the latest version, the comparison check shows that the new package is missing all the data that was in the '/usr/share/locale' directory. Are there any special steps needed to have the .mo translation files created and included?
Thank you!

**Comment by vgough** [comment]
Thanks for the report - they are missing.  I recall that in the past, I integrated the translation files while creating a distribution.  That doesn't work well in the distributed development model, so I think the answer is to periodically commit a snapshot of the po files.  I'll give this a try with the a new Rosetta snapshot.

**Comment by vgough** [comment]
Files from a PO snapshot have been added in b2f50bab1edd6c13ce4da42d2b3685d6b2bf42e9, and I make sure they compiled (which isn't always the case directly from the snapshots!).  Please give HEAD a try to see if it passes your checks.

**Comment by rfjakob** [comment]
First of all, thanks for the report! Translation files are are included in the 1.8.1 release. If there still is an issue please reopen this bug.
