### ISSUE TITLE
Configure error on Centos 6.6

### ISSUE THREAD

**Issue by teodorg** [vgough/encfs#65]
checking for sys/xattr.h... yes
checking whether xattr interface takes additional options... no
./configure: line 20551: syntax error near unexpected token `newline'
./configure: line 20551: `  yes:no:'

And these lines are:

    # So?  What about this header?
    case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
      yes:no:
    fi

**Comment by rfjakob** [comment]
Which encfs version?

**Comment by teodorg** [comment]
The master branch.

**Comment by rfjakob** [comment]
Looks like something went wrong in the autoconf stage. Please try this configure script: https://github.com/rfjakob/encfs/releases/download/v1.8/configure
For 1.8.1, I will bundle the configure script in the .tar.gz.

**Comment by compevo** [comment]
We have the same problem on Centos 6.6 even with the new configure script above.
./configure does succeed but then it seems like "make" rewrites the same bad ./configure and then build fails.

checking whether xattr interface takes additional options... no
./configure: line 20551: syntax error near unexpected token `newline'
./configure: line 20551: `  yes:no:'
make: *** [config.status] Error 2

**Comment by dougalb** [comment]
I am seeing the same issue. I am guessing it is something to do with autoconf/automake versions on RHEL/CentOS6. I have been able to build with no issues on Amazon Linux 2015.03.

**Comment by vgough** [comment]
The autoconf scripts have been replaced with cmake on master.  You will probably have to download a recent cmake binary (http://www.cmake.org/download/) in order to create the make files, since the default from RHEL 6.6 is probably too old.

If you uncover issues with the cmake build rules, please open a new ticket with details.

Thanks!
