### ISSUE TITLE
encfs in cygwin?

### ISSUE THREAD

**Issue by Zurd** [vgough/encfs#66]
Hi, anyone has succesfully installed encfs on cygwin on Windows? Is it possible at all?

I know there's a version for Windows, running 1.7.4 which is also what my Linux Mint installed. But it says experimental on the webpage, anyone knows if it's reliable?
http://members.ferrara.linux.it/freddy77/encfs.html

Note that there's no version available here:
https://github.com/vgough/encfs/blob/master/ChangeLog
So I don't know what is the latest version on github for encfs

And sourceforge list 1.2.0-2 as the latest:
https://sourceforge.net/projects/encfs
Looks like encfs on sourceforge is dead which is why it's on github anyway.

For the problem in cygwin, it's crashing at autoreconf -if, there's quite a few package I couldn't install as they are not provided in cygwin, like build-essential, libfuse-dev, libssl-dev, librlog-dev, libbost-serialization-dev which is why I'm also asking if it could be even possible to install encfs in cygwin.

Here's where I'm at right now:

Copying file ABOUT-NLS
Creating directory build-aux
Copying file build-aux/config.rpath
Copying file m4/codeset.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:17: error: possibly undefined macro: PKG_CHECK_MODULES
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf-2.69: /usr/bin/autoconf-2.69 failed with exit status: 1

**Comment by rfjakob** [comment]
Please try 1.8.1 ( https://github.com/vgough/encfs/releases/download/v1.8.1/encfs-1.8.1.tar.gz ).
This version, released today, has the configure script bundled. That means you don't need autoconf, instead you just do

    ./configure
    make

That may allow you to get further.

**Comment by Zurd** [comment]
Thanks! I went farther but it's now complaining that I don't have FUSE.

Seems like FUSE is just not available for Windows:
http://fuse.996288.n3.nabble.com/Problems-instaling-and-config-FUSE-in-CYGWIN-td11849.html
http://cygwin.1069669.n5.nabble.com/free-NFS-client-for-Cygwin-and-or-support-for-FUSE-td36572.html

```bash
./configure
[...]
checking fuse.h usability... no
checking fuse.h presence... no
checking for fuse.h... no
checking for fuse.h library with -I/usr/include/fuse... no
checking for fuse.h library with -I/usr/local/include/fuse... no
checking for fuse.h library with -I/opt/include/fuse... no
checking for fuse.h library with -I/opt/local/include/fuse... no
checking for fuse.h library with -I/usr/include/osxfuse... no
checking for fuse.h library with -I/usr/local/include/osxfuse... no
checking for fuse.h library with -I/opt/local/include/osxfuse... no
checking for fuse_mount in -lfuse... no
checking for fuse library with -L/usr/lib... no
checking for fuse library with -L/usr/local/lib... no
checking for fuse library with -L/opt/lib... no
checking for fuse library with -L/opt/local/lib... no
checking for fuse_mount in -losxfuse... no
checking for osxfuse library with -L/usr/lib... no
checking for osxfuse library with -L/usr/local/lib... no
checking for osxfuse library with -L/opt/lib... no
checking for osxfuse library with -L/opt/local/lib... no
checking for fuse_new in -lfuse... no
configure: error: Unable to find libfuse.
```

**Comment by doughdemon** [comment]
You could try out

http://sourceforge.net/p/fuse-emulator/wiki/Building%20Fuse%20on%20Windows%20with%20Cygwin/

**Comment by Zurd** [comment]
That FUSE is the "Free Unix Spectrum Emulator", it is not the FUSE I'm looking for which is "Filesystem in Userspace".

**Comment by doughdemon** [comment]
Zurd wrote:
> That FUSE is the "Free Unix Spectrum Emulator", it is not the FUSE
> I'm looking for which is "Filesystem in Userspace".

Sorry.

https://github.com/freddy77/encfs4win

has not seen any changes since March 2013. It uses a patched version
of encfs-1.7.4. Therefore it is not trivial to update. It also uses
fuse4win, which is a wrapper around dokan (windows native library
with similar purpose as fuse), which are both abadoned. There is a
fork dokanx of dokan but no fork of fuse4win.

Yes, all in all, it would take a lot of work to make encfs work
with cygwin.

**Comment by florian-t** [comment]
Has anyone had a look at http://encfsmp.sourceforge.net/? Looks like a very young piece of software for using encfs under windows / mac.

**Comment by stefanmohl** [comment]
https://github.com/dokan-dev/dokany is a fork of Dokan 0.6 that has seen a lot of activity, including bugfixes and a FUSE-compatible wrapper. There is a Windows-version of encfs that uses it, as well as several other projects (including an sshfs-project). Perhaps it could be leveraged for a cygwin encfs (as well as sshfs!)

**Comment by benrubson** [comment]
EncFS 1.9.5 is Cygwin ready 👍
