### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by maleadt** [vgough/encfs#67]
In order to debug an unrelated issue, I've written [a small `Makefile`](https://gist.github.com/maleadt/7903b678623c2b8a4e64) which performs the following steps:
- create an 8MB, ext4 formatted image
- create a loop device and bind the image to it
- mount the loop-device to a folder
- set-up an encfs encrypted directory (standard settings, password `foobar`)

You can execute these steps by saving the `Makefile` in some folder, and executing `make`. In order to quickly trip the issue, execute `while make; do echo; done`, which repeatedly executes `make` until failure occurs.

On my system, it only takes some 2 or 3 iterations about I get an error: `Transport endpoint is not connected`. This only happens when trying to list the folder; creating and mounting it works perfectly fine:

```
spawn encfs -v /usr/src/encfs-bug/mount/.secure /usr/src/encfs-bug/mount/encrypted
11:52:48 (main.cpp:532) Root directory: /usr/src/encfs-bug/mount/.secure/
11:52:48 (main.cpp:533) Fuse arguments: (daemon) (threaded) (keyCheck) encfs /usr/src/encfs-bug/mount/encrypted -o use_ino -o default_permissions 
Creating new encrypted volume.
Please choose from one of the following options:
 enter "x" for expert configuration mode,
 enter "p" for pre-configured paranoia mode,
 anything else, or an empty line will select standard mode.
?> standard

Standard configuration selected.
11:52:48 (SSL_Cipher.cpp:335) allocated cipher ssl/aes, keySize 24, ivlength 16
11:52:48 (FileUtils.cpp:1085) Using cipher AES, key size 192, block size 1024

Configuration finished.  The filesystem to be created has
the following properties:
11:52:48 (Interface.cpp:117) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:2)
11:52:48 (SSL_Cipher.cpp:335) allocated cipher ssl/aes, keySize 24, ivlength 16
Filesystem cipher: "ssl/aes", version 3:0:2
11:52:48 (Interface.cpp:117) checking if nameio/block(4:0:2) implements nameio/block(4:0:2)
Filename encoding: "nameio/block", version 4:0:2
11:52:48 (Interface.cpp:117) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:2)
11:52:48 (SSL_Cipher.cpp:335) allocated cipher ssl/aes, keySize 24, ivlength 16
Key Size: 192 bits
Block Size: 1024 bytes
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File holes passed through to ciphertext.

Now you will need to enter a password for your filesystem.
You will need to remember this password, as there is absolutely
no recovery mechanism.  However, the password can be changed
later using encfsctl.

11:52:48 (openssl.cpp:43) Allocating 41 locks for OpenSSL
11:52:48 (FileUtils.cpp:1139) useStdin: 0
New Encfs Password: 
Verify Encfs Password: 
11:52:48 (Interface.cpp:117) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:2)
11:52:48 (SSL_Cipher.cpp:335) allocated cipher ssl/aes, keySize 24, ivlength 16
11:52:49 (Interface.cpp:117) checking if nameio/block(4:0:2) implements nameio/block(4:0:2)
```

```
mount | grep /usr/src/encfs-bug/mount/encrypted
encfs on /usr/src/encfs-bug/mount/encrypted type fuse.encfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,default_permissions)
```

```
ls /usr/src/encfs-bug/mount/encrypted
ls: cannot access /usr/src/encfs-bug/mount/encrypted: Transport endpoint is not connected
```

I'm using Arch Linux, which ships fuse 2.5 and encfs 1.8. I'm running kernel 4.0.0-rc4. When the error occurs, I'm not seeing any warnings or errors in my system log.

**Comment by rfjakob** [comment]
I guess when you do not recreate the loop device every time this does not
happen?

By the way, you can use "--standard" and "--extpass" to simplify the
script, take a look at
https://github.com/vgough/encfs/blob/master/tests/normal.t.pl .
On the other hand, testing the user interface with expect would be a nice
addition to the test suite.

**Comment by maleadt** [comment]
It still happens when not recreating the loop device. Strangely, it stopped happening when switching from `expect` to `--standard --extpass='echo ...'`! My hypothesis: when `expect eof` triggers (due to `encfs` closing `stdout`, I assume), `encfs` hasn't fully forked yet, causing `expect` to kill the still foregrounded process.

But that's just a guess, I don't know any of the `encfs` internals :)

**Comment by rfjakob** [comment]
I can reproduce this on my pc. I could not see anything wrong with how expect does it's thing.
What would help is a minimal reproducer script. Is the mkfs.ext4 and/or remount neccessary to trigger it?

**Comment by maleadt** [comment]
Nope, you're absolutely right, the complicated image->`loop`->`mkfs.ext4` stuff is just a remnant of another issue I tried to trigger, but in case of this problem it can safely be removed. A reduced `Makefile`:
```make
SHELL := /bin/bash
PASSWORD=foobar

.PHONY: default
default:
	$(MAKE) clean
	while $(MAKE) test; do echo; done

.PHONY: test
test: clean encrypted
	mount | grep testdir/encrypted      # verify whether the mount succeeded
	ls testdir/encrypted                # see whether the mount is functional


# Directory creation rules
testdir:
	mkdir $@
testdir/encrypted: | testdir
	mkdir $@
testdir/.secure: | testdir
	mkdir $@


# encfs set-up
define EXPECT_ENCFS
	spawn encfs $(PWD)/testdir/.secure $(PWD)/testdir/encrypted

	expect "Please choose from one of the following options:"
	send "standard\r"

	expect "New Encfs Password:"
	send "$(PASSWORD)\r"

	expect "Verify Encfs Password:"
	send "$(PASSWORD)\r"

	expect eof
endef
export EXPECT_ENCFS
.PHONY: encrypted
encrypted: testdir/.secure testdir/encrypted
	# THIS DOESN'T WORK
	expect <( echo "$$EXPECT_ENCFS" )

	# THIS WORKS
	# encfs --standard --extpass="echo $(PASSWORD)" \
	#       $(PWD)/testdir/.secure $(PWD)/testdir/encrypted


# Clean-up
.PHONY: clean
clean:
	if mount | grep testdir/encrypted >/dev/null; then \
		fusermount -u testdir/encrypted; \
	fi
	$(RM) -r testdir/.secure
	$(RM) -r testdir/encrypted

	if [ -d testdir ]; then rmdir testdir; fi
```

I also noticed how this bug is harder to reproduce on a ck-patched (BFS+BFQ) kernel; on a vanilla upstream kernel it triggers within the first some iterations.

**Comment by maleadt** [comment]
Sorry, I am no longer using encfs.

**Comment by benrubson** [comment]
Let's close this then, thank you Tim !
