### ISSUE TITLE
encfs-1.8.1.tar.gz is missing aclocal.m4

### ISSUE THREAD

**Issue by doughdemon** [vgough/encfs#72]
Current tarball doesn't have aclocal.m4. So when trying to run make it will try to run aclocal, which might not work if autoconf is not installed or there could be problems because of non-matching libtool versions.

There is a script makedist.sh, which creates a tarball including all necessary files. Why is it no longer used?

**Comment by doughdemon** [comment]
I see. Does #73 fix it?

**Comment by rfjakob** [comment]
We are getting further:

    ../../encfs/i18n.h:25:26: fatal error: intl/gettext.h: No such file or directory
     #include "intl/gettext.h"
                              ^

**Comment by rfjakob** [comment]
But yeah, by now I think there is no alternative to using makedist.sh. I will use for 1.8.2 once it is fixed up.

**Comment by doughdemon** [comment]
intl/gettext.h is included in EXTRA_DIST of Makefile.am and in my tests
indeed it is included in the tarball created by makedist.sh.

Is intl/gettext.h really missing in your tarball?

**Comment by rfjakob** [comment]
Interesting. `make distcheck` fails, but manually unpacking the tarball and building works.

**Comment by doughdemon** [comment]
That's seems to be a different bug: Building outside of the source
directory is broken.

**Comment by rfjakob** [comment]
Fixed in https://github.com/rfjakob/encfs/commit/5aec2078ee2f3cb0ca2f4d33e98a6c53f971b5a5

**Comment by doughdemon** [comment]
Thanks. That looks good.
