### ISSUE TITLE
IV not based on files' path

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#79]
Hello,

Here is a topic about Filename Initialization Vector Chaining.

I do not use it because I have directories with a huge amout of subdirectories and files, so I do not want to be impacted by the significant performance impact which directory renames involve.

Could we think about a solution to give each object's name its own initialization vector but not based on its path ?
This would help with the performance impact.

Thank you very much !

Ben

**Comment by vgough** [comment]
Yes, I would like to replace the full chaining with a per-directory IV, so that renaming a directory does not require changing contents of the directory.  AFAIK, nobody is working on it yet, it's just a wishlist item.

**Comment by benrubson** [comment]
Related to #5.
