### ISSUE TITLE
Aligned IOs

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#80]
Hello,

This topic is about performances / aligned IOs.

From what I understand, if an application reads a 512 bytes data block, and if MAC (authentication code) is enabled, alignment with disk blocks will not be preserved, and 2 blocks will be read from the disk, "instead" of one.
Same thing of course if we talk about 4K data blocks on 4K block disks.
So for alignment / performance purpose, authentication code should be turned off, as random bytes (0).

Per-file initialization vectors adds a file header (in which the IV is stored), leading into non-aligned IOs.
However, per-file IV seems to be a must-have for security reasons.

So could we think about a solution to keep IOs aligned even with per-file IV option enabled ?

Growing the header to the exact size of a block (512b, 4K... depending on the configured block size) ?
We could then use the extra free space of this header block to store the file, of course only if the file size is lower than or equal to the extra free space.
If the file is bigger than the extra free space, it must starts at the beginning of the second block, to be sure to have IOs aligned.

Other solution, moving header at the end of the file, in the last data block (last block would then be data;padding;footer) ?
It would reduce the first solution overhead, but it could produce its own performance impact (as head of disk will have to move at the end of the file to read the footer, and come back to its beginning to read it).

Any other possible solution ?

Is there any other EncFS configuration option (except MAC, random bytes and per-file IV) that would lead into non aligned IOs ?

Thank you very much !

Best regards,

Ben

**Comment by rfjakob** [comment]
Due to readahead, many more than two blocks will be read anyway.
What is your application that requires block alignment?

**Comment by benrubson** [comment]
Large / huge rsync repositories.

I already encountered very bad performances with non-aligned partitions, which disappeared once partitions correctly aligned.
This non-aligned partitions performance impact is very common, and can be encountered whatever the application you use.

This is why I would like EncFS to work aligned with disks blocks, in order to prevent this performance issue.

**Comment by rfjakob** [comment]
What is killing performance if the partition is not aligned is the filesystem metadata. This is where tons of tiny writes are happening. rsync, on the other hand, operates on big blocks of data.

Aligend IO would be nice to have for database workloads and such, though.

**Comment by benrubson** [comment]
Glad to see that this has been considered as an enhancement, thank you rfjakob !
We will now have to think how to implement this, I gave some possibilities in the first post of this topic, perhaps there are others.

**Comment by benrubson** [comment]
@rfjakob, I close this, not a priority in encfs development, and no more a priority for me.
Thx 👍
