### ISSUE TITLE
Check password method

### ISSUE THREAD

**Issue by benrubson** [vgough/encfs#81]
Hello,

Could it be possible to implement a method to check if a given password is good ?
For example as an option to encfsctl.
echo "pass" | encfsctl checkpasswd /my_encfs/
This would then return 0 or 1.

Thank you !

Ben

**Comment by rfjakob** [comment]
What is wrong with mounting it?

**Comment by benrubson** [comment]
I would like to use the password EncFS stores for other purpose than mounting the encrypted filesystem.
So I need to check the password I have against the one EncFS stores.

The following works to change password :
echo "oldpass
newpass" | encfsctl autopasswd /my_encfs/

So I assume that the following should not be difficult to implement :
echo "pass" | encfsctl checkpasswd /my_encfs/

Thank you very much !

**Comment by benrubson** [comment]
Hello,

Could it be possible to write a quick Perl script which would check a password against a `.encfs6.xml` file ?

For example :
`check_encfs_password.pl <password> <.encfs6.xml_file>`
It would return 0 or 1 whether password is correct or not.

Could you indicate me the fields to use in the `.encfs6.xml` file and the operation to make on the password and these fields to be able to make the comparison ?

Thank you very much :+1: 

Ben

**Comment by vgough** [comment]
Thanks Ben.

**Comment by benrubson** [comment]
Thanks Valient !
