### ISSUE TITLE
.encfs6.xml file

### ISSUE THREAD

**Issue by Slim1991** [vgough/encfs#82]
Hi,
Can you tell me the structure of this xml file? What is underlying?
I want to understand this file.

**Comment by vgough** [comment]
In versions using Boost, the xml file is handled by [boost serialization](http://www.boost.org/doc/libs/1_58_0/libs/serialization/doc/index.html).    Look at the load and save methods here: https://github.com/vgough/encfs/blob/master/encfs/FileUtils.cpp#L138
