### ISSUE TITLE
Boxcryptor Linux Compatibility for Mounting Dropbox Decrypted Folders

### ISSUE THREAD

**Issue by Jonathonbyrd** [vgough/encfs#83]
Hey Guys, I really appreciate all of the work that you're putting into this project. Is there anything that you can do to make encfs capable of mounting a Boxcryptor Local Account on Linux?

It Seems as if Boxcryptor has removed the encfs.xml file that kept it compatible with encfs. What can we do to make this all compatible?

**Comment by vgough** [comment]
I'd ask the Boxcryptor folks.  I'm open to adding an alternative configuration mechanism if that's the issue.

**Comment by JPvRiel** [comment]
In case anyone else stumbles on this here, [Create an EncFS volume compatible with BoxCryptor Classic](https://www.andreagrandi.it/2014/09/12/create-an-encfs-volume-compatible-with-boxcryptor-classic/) was a useful guide. However, the simplest workaround is to set things up with the BoxCryptor Classic app. The newever BoxCryptor 2+ version is a complete re-write and isn't compatible with the EncFS implementation.

During the 1.x EncFS release changes, I'm guessing that if there are any changes that break backwards compatibility with EncFS ~v1.7, BoxCryptor classic may stop being interoperable with EncFS.
