### ISSUE TITLE
NetBSD: Shared library not found

### ISSUE THREAD

**Issue by n-t-roff** [vgough/encfs#87]
```
$ encfs
Shared object "libencfs.so.7" not found
```

NetBSD discourages to use /etc/ld.so.conf and the like (http://www.netbsd.org/docs/elf.html). At NetBSD the location is set with the compiler argument (for the linker) `-Wl,-R` (or `-Wl,-rpath`). This is a portable and save way to "bind" binaries to shared libraries. Would it be possible to add that option? This works on every other UNIX system too and decreases the probability of problems.

**Comment by n-t-roff** [comment]
`encfs` does start after setting
```
export LD_LIBRARY_PATH=/usr/local/lib:/usr/pkg/lib
```
but as said it would be preferable that the tool knows the paths. (The build process has this information. There should be no disadvantage in specifying it with `-Wl,-R`.)

**Comment by vgough** [comment]
Which version of cmake are you using?

CMake is setting rpaths on other systems.  What is the rpath on your installed executable?  (on Linux, 'ldd' will show the paths, on OSX `otool -L` will show them, but I don't know what NetBSD uses).

**Comment by vgough** [comment]
Also, try adding this to your CMakeLists.txt file:

SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

**Comment by n-t-roff** [comment]
```
$ cmake --version
cmake version 3.2.2
$ ldd `which encfs`
/usr/local/bin/encfs:
        -lencfs.7 => not found
        -lfuse.2 => not found
        -lssl.10 => /usr/lib/libssl.so.10
        -lcrypto.8 => /usr/lib/libcrypto.so.8
        -lcrypt.1 => /lib/libcrypt.so.1
        -lgcc_s.1 => /usr/lib/libgcc_s.so.1
        -lc.12 => /usr/lib/libc.so.12
        -lboost_serialization.1.58.0 => not found
        -lrlog.1 => not found
        -lpthread.1 => /usr/lib/libpthread.so.1
        -lstdc++.7 => /usr/lib/libstdc++.so.7
        -lm.0 => /usr/lib/libm.so.0
```
I did add
```
SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
```
as the last line of `CMakeLists.txt`, but this didn't change anything.

**Comment by n-t-roff** [comment]
For /usr/local/lib this does work now:
```
$ objdump -x `which encfs`|grep RPATH
  RPATH                /usr/local/lib

$ ldd `which encfs`
/usr/local/bin/encfs:
        -lencfs.1.9 => /usr/local/lib/libencfs.so.1.9
```
But not for /usr/pkg/lib.

(Unfortuantely encfs does not run on NetBSD.  But there had been a encfs package 10 years ago there, maybe the NetBSD list has an idea what can be done in this case.)

**Comment by vgough** [comment]
Closing this, as the state of encfs/fuse on NetBSD is a separate issue.
