### ISSUE TITLE
OpenSuse 13.2: encfs doesn't find libencfs.so

### ISSUE THREAD

**Issue by n-t-roff** [vgough/encfs#90]
It works by setting
```
LD_LIBRARY_PATH=/usr/local/lib; export LD_LIBRARY_PATH
```
but linking with rpath would be more comfortable for the user.

**Comment by vgough** [comment]
Did you try this with the latest code from mainline?

What does this command show:  "objdump -x encfs | grep RPATH"

**Comment by n-t-roff** [comment]
Nothing.
But ldd tells that encfs points to the build directory.
(What I do (for other software) is to use -L to the build directory to make initial linking work and additional give -Wl,-rpath for later usage after install.  (I.e. `LDFLAGS=-L. -Wl,-rpath,/usr/local/lib`)

**Comment by vgough** [comment]
cmake should take care of this - it will change the rpath during the install.

For instance, on my Ubuntu test system or drone worker (configured to install in a temporary directory):
$ objdump -x encfs | grep RPATH
  RPATH                /home/vgough/devel/encfs-github/build:
$ make install
...
-- Installing: /tmp/cmake/bin/encfs
-- Set runtime path of "/tmp/cmake/bin/encfs" to "/tmp/cmake/lib"
...

$ objdump -x /tmp/cmake/bin/encfs | grep -i rpath
  RPATH                /tmp/cmake/lib

**Comment by n-t-roff** [comment]
I tested again and it works now. Thank you!
