### ISSUE TITLE
Pointless translations for some languages

### ISSUE THREAD

**Issue by Code7R** [vgough/encfs#93]
Hello,
unlike the state of po/\* files indicates, some of them are redundant. Some of the redundant ones even contain errors and/or are less complete. From my POV, following are candidates for removal:

de_AT.po
de_CH.po
en_AU.po
en_CA.po
en_GB.po
pt_PT.po

(not sure about the English variants, a native speaker should decide)

**Comment by vgough** [comment]
Thanks.  If you have time to send a github PR, please do.

**Comment by benrubson** [comment]
Closing this, as https://github.com/vgough/encfs/commit/c4f5325ebcc8e5c78e179f9a2afdc59a55869d3c already references it.
Feel free though to open new PRs updating / deleting unnecessary translations in your native language.
Thx 👍
