### ISSUE TITLE
Mounted folder is empty

### ISSUE THREAD

**Issue by jano-on-github** [vgough/encfs#95]
I used encfs for months without trouble and loved it. But now I have a problem. I tried to decrypt data that I stored in a cloud and it seems to work but unfortunately the mounted folder is empty. encfs gives me the following terminal output:

	janosik@Zenbook:~$ encfs -v -f ~/Downloads/Encrypted  ~/Test
	19:30:40 (main.cpp:523) Root directory: /home/janosik/Downloads/Encrypted/
	19:30:40 (main.cpp:524) Fuse arguments: (fg) (threaded) (keyCheck) encfs /home/janosik/Test -f -s -o use_ino -o default_permissions 
	19:30:40 (FileUtils.cpp:177) version = 20
	19:30:40 (FileUtils.cpp:181) found new serialization format
	19:30:40 (FileUtils.cpp:199) subVersion = 20100713
	19:30:40 (Interface.cpp:165) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:0)
	19:30:40 (SSL_Cipher.cpp:370) allocated cipher ssl/aes, keySize 32, ivlength 16
	19:30:40 (Interface.cpp:165) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:0)
	19:30:40 (SSL_Cipher.cpp:370) allocated cipher ssl/aes, keySize 32, ivlength 16
	19:30:40 (FileUtils.cpp:1620) useStdin: 0
	EncFS-Passwort: 
	19:30:44 (Interface.cpp:165) checking if ssl/aes(3:0:2) implements ssl/aes(3:0:0)
	19:30:44 (SSL_Cipher.cpp:370) allocated cipher ssl/aes, keySize 32, ivlength 16
	19:30:47 (FileUtils.cpp:1628) cipher key size = 52
	19:30:47 (Interface.cpp:165) checking if nameio/block(3:0:1) implements nameio/block(3:0:0)
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/GJYCaoU-C5-Ut,pr2DYLm5o5: Datei oder Verzeichnis nicht gefunden
	19:30:47 (CipherFileIO.cpp:105) in setIV, current IV = 0, new IV = 12689445316339533885, fileIV = 0
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/GJYCaoU-C5-Ut,pr2DYLm5o5
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/GJYCaoU-C5-Ut,pr2DYLm5o5
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/GJYCaoU-C5-Ut,pr2DYLm5o5: Datei oder Verzeichnis nicht gefunden
	19:30:47 (encfs.cpp:138) getattr error: Datei oder Verzeichnis nicht gefunden
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/lRW2DCgJinoTqdcjxXXwMkoXJY-keuQpu6tMnYXHU1bh3,: Datei oder Verzeichnis nicht gefunden
	19:30:47 (CipherFileIO.cpp:105) in setIV, current IV = 0, new IV = 2579159024180395544, fileIV = 0
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/lRW2DCgJinoTqdcjxXXwMkoXJY-keuQpu6tMnYXHU1bh3,
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/lRW2DCgJinoTqdcjxXXwMkoXJY-keuQpu6tMnYXHU1bh3,
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/lRW2DCgJinoTqdcjxXXwMkoXJY-keuQpu6tMnYXHU1bh3,: Datei oder Verzeichnis nicht gefunden
	19:30:47 (encfs.cpp:138) getattr error: Datei oder Verzeichnis nicht gefunden
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/8tG-RdXsZUoRnVnx,d-xF5H5: Datei oder Verzeichnis nicht gefunden
	19:30:47 (CipherFileIO.cpp:105) in setIV, current IV = 0, new IV = 15746073280678210699, fileIV = 0
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/8tG-RdXsZUoRnVnx,d-xF5H5
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/8tG-RdXsZUoRnVnx,d-xF5H5
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/8tG-RdXsZUoRnVnx,d-xF5H5: Datei oder Verzeichnis nicht gefunden
	19:30:47 (encfs.cpp:138) getattr error: Datei oder Verzeichnis nicht gefunden
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/,NP4g8MUcc,GtKQoc3JFJqeJ: Datei oder Verzeichnis nicht gefunden
	19:30:47 (CipherFileIO.cpp:105) in setIV, current IV = 0, new IV = 3161273097063990839, fileIV = 0
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/,NP4g8MUcc,GtKQoc3JFJqeJ
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/,NP4g8MUcc,GtKQoc3JFJqeJ
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/,NP4g8MUcc,GtKQoc3JFJqeJ: Datei oder Verzeichnis nicht gefunden
	19:30:47 (encfs.cpp:138) getattr error: Datei oder Verzeichnis nicht gefunden
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:47 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:47 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:47 (DirNode.cpp:132) error decoding filename: .encfs6.xml
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:47 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:47 (FileNode.cpp:127) calling setIV on (null)
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/,NP4g8MUcc,GtKQoc3JFJqeJ: Datei oder Verzeichnis nicht gefunden
	19:30:47 (CipherFileIO.cpp:105) in setIV, current IV = 0, new IV = 3161273097063990839, fileIV = 0
	19:30:47 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/,NP4g8MUcc,GtKQoc3JFJqeJ
	19:30:47 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/,NP4g8MUcc,GtKQoc3JFJqeJ
	19:30:47 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/,NP4g8MUcc,GtKQoc3JFJqeJ: Datei oder Verzeichnis nicht gefunden
	19:30:47 (encfs.cpp:138) getattr error: Datei oder Verzeichnis nicht gefunden
	19:30:52 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:52 (FileNode.cpp:127) calling setIV on (null)
	19:30:52 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/
	19:30:52 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/
	19:30:52 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:52 (FileNode.cpp:127) calling setIV on (null)
	19:30:52 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/GJYCaoU-C5-Ut,pr2DYLm5o5: Datei oder Verzeichnis nicht gefunden
	19:30:52 (CipherFileIO.cpp:105) in setIV, current IV = 0, new IV = 12689445316339533885, fileIV = 0
	19:30:52 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/GJYCaoU-C5-Ut,pr2DYLm5o5
	19:30:52 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/GJYCaoU-C5-Ut,pr2DYLm5o5
	19:30:52 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/GJYCaoU-C5-Ut,pr2DYLm5o5: Datei oder Verzeichnis nicht gefunden
	19:30:52 (encfs.cpp:138) getattr error: Datei oder Verzeichnis nicht gefunden
	19:30:52 (MACFileIO.cpp:75) fs block size = 1024, macBytes = 8, randBytes = 0
	19:30:52 (FileNode.cpp:127) calling setIV on (null)
	19:30:52 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/8tG-RdXsZUoRnVnx,d-xF5H5: Datei oder Verzeichnis nicht gefunden
	19:30:52 (CipherFileIO.cpp:105) in setIV, current IV = 0, new IV = 15746073280678210699, fileIV = 0
	19:30:52 (DirNode.cpp:770) created FileNode for /home/janosik/Downloads/Encrypted/8tG-RdXsZUoRnVnx,d-xF5H5
	19:30:52 (encfs.cpp:134) getattr /home/janosik/Downloads/Encrypted/8tG-RdXsZUoRnVnx,d-xF5H5
	19:30:52 (RawFileIO.cpp:191) getAttr error on /home/janosik/Downloads/Encrypted/8tG-RdXsZUoRnVnx,d-xF5H5: Datei oder Verzeichnis nicht gefunden
	19:30:52 (encfs.cpp:138) getattr error: Datei oder Verzeichnis nicht gefunden
	19:30:52 (encfs.cpp:213) getdir on /home/janosik/Downloads/Encrypted/
	19:30:52 (BlockNameIO.cpp:185) padding, _bx, finalSize = 129, 16, -113
	19:30:52 (DirNode.cpp:132) error decoding filename: bsqtej7r4ZHbyXr4JqMhu,Px
	19:30:52 (DirNode.cpp:132) error decoding filename: .encfs6.xml

I appreciate any help!

**Comment by rfjakob** [comment]
Hi Jano, please post `ls -l /home/janosik/Downloads/Encrypted/`

**Comment by jano-on-github** [comment]
Hi, thank you for the reply

janosik@Zenbook:~/Downloads$ ls -l /home/janosik/Downloads/Encrypted/
insgesamt 4
drwx------ 11 janosik janosik 4096 Jul 17 19:11 bsqtej7r4ZHbyXr4JqMhu,Px

**Comment by rfjakob** [comment]
Looks like there is only a single file in there. How many files do you expect?

**Comment by jano-on-github** [comment]
Theres one folder at first but it inherits a lot of other folders and files: see
![bildschirmfoto vom 2015-07-19 13 47 33](https://cloud.githubusercontent.com/assets/7703423/8765752/de40c71a-2e1c-11e5-98ea-db1f75979628.png)

**Comment by rfjakob** [comment]
Hmm. Did you rename or move anything in the encrypted directory?

**Comment by jano-on-github** [comment]
Not that I know, maybe some files were corrupted in the cloud storage or while syncing? I tried to resync everything twice, just in case, but the error remains. Has this something do to with file naming or file hierarchy? Is there anything I can do?

**Comment by rfjakob** [comment]
Did you store `.encfs6.xml` seperately from the encrypted data? Is it possible that you are using a different `.encfs6.xml` right now?

**Comment by jano-on-github** [comment]
Yeah okay, it is a bit odd. I dont see a .encfs6.xml file in my cloud storage (mega.co.nz) but there is one in my synced folder in my file manager. Now I dont know how it got there or if maybe the online-interface of mega just doesnt show hidden files. If the .xml file would be wrong that would explain the errors I get?

**Comment by rfjakob** [comment]
Yes, it would explain the errors.
When mounting, encfs just checks if the password is correct for this `.encfs6.xml` file.

**Comment by rfjakob** [comment]
Jano, I just tried uploading an encfs folder to mega.co.nz. I see the `.encfs6.xml` file, mega does not hide it.

![screenshot from 2015-07-19 15-28-50](https://cloud.githubusercontent.com/assets/286847/8766095/f00a2050-2e2a-11e5-8b41-7f6ce7bd4c87.png)

**Comment by jano-on-github** [comment]
Alright, thanks a lot for your effort! I guess the data is lost then, since I read somewhere that without the right .xml file it is impossible to restore the data. I still wonder how the file got lost or changed in the first place... Anyway thank you!

**Comment by rfjakob** [comment]
Yes, I am afraid this is correct. Without the .encfs6.xml the data is lost.

**Comment by wotanii** [comment]
I just ran into the same errror: `DirNode.cpp:132) error decoding filename: .encfs6.xml?`

I fix it with:
1. unmount encfs
2. delete mount-point
3. mount again.
Now all my files are visible again. 
with the next umount & mount the file are gone again and i get the error again. Then I can delete the mountpoint again and it works again.

**Comment by rajanski** [comment]
I got the same problem after moving from encfs 1.7.4 to 1.8.1

`(BlockNameIO.cpp:189) Rejecting filename '.encfs6.xml'
08:17:38 (DirNode.cpp:108) error decoding filename: .encfs6.xml`

**Comment by jjolidon** [comment]
For anyone finding this thread, to make a backup of your encfs-encrypted files with MegaSync you absolutely need to create a `.megaignore` file at the root of your encfs folder to include the following rules:
```
# Synchronize .encfs6.xml files that contains the updated encryption keys
+f:.encfs6.xml
# Share the megaignore file with any other synchronization of the same folder
+sync:.megaignore
```
See https://help.mega.io/installs-apps/desktop-syncing/megaignore for more details on the syntax
