### ISSUE TITLE
cmake 2.18.12 doesn't work

### ISSUE THREAD

**Issue by pepa65** [vgough/encfs#96]
Could you make the build work with cmake-2.8.12?? It used to work fine with autoreconf, but Ubuntu LTS doesn't offer cmake-3.1

**Comment by vgough** [comment]
CMake 3.1 adds C++11 support, which I do not intend to duplicate.  CMake provides plenty of pre-compiled binary builds, and it is easy to run them without actually installing.  Look at the circle setup files as an example - they use a non-installed cmake for the build.

**Comment by pepa65** [comment]
I am not a build wizard... But I will try a few things. It's just a pity it's getting to be so difficult to follow along with recent developments. I switched back to encfs last year because I believed the former disrepute of security problems is being fixed.

**Comment by pepa65** [comment]
I grabbed the most recent version for x86_64 Linux at http://www.cmake.org/download/ and installed it in a local directory, and ran the cmake step with $LOCALDIR/bin/cmake and then make worked fine.
