### ISSUE TITLE
Wiki out of step

### ISSUE THREAD

**Issue by pepa65** [vgough/encfs#97]
It seems the Wiki at https://github.com/vgough/encfs/wiki/Installing-Encfs is out of step, as "autoreconf -if" no longer works. How does Travis now build encfs on Ubuntu??

**Comment by rfjakob** [comment]
https://github.com/vgough/encfs/blob/master/INSTALL.md

**Comment by pepa65** [comment]
Yes, the wiki also references that. What version of Ubuntu is Travis running on?? The current build method doesn't work on Ubuntu LTS.

**Comment by vgough** [comment]
Travis is no longer being used.  Circle and Drone are now both run, based on different Ubuntu distributions.  The Circle build installs a recent version of cmake as part of the environment setup.

**Comment by pepa65** [comment]
OK... Is there any way encfs can be built on my Ubuntu LTS machines?

**Comment by vgough** [comment]
Yes, take a look at how the Circle config does it.  It downloads the cmake binary and untars it into a local directory:

https://github.com/vgough/encfs/blob/master/ci/install-cmake.sh

Then the build script just calls the cmake that was downloaded:

https://github.com/vgough/encfs/blob/master/ci/config.sh

**Comment by vgough** [comment]
I've updated the wiki page to fix the link to INSTALL.md which has the instructions.  Instructions on using a local cmake could be added there as well.
