### ISSUE TITLE
Problem using encfs --reverse over rofs-filtered

### ISSUE THREAD

**Issue by tovrstra** [vgough/encfs#99]
Somehow encfs fails to construct the mount point and .encfs6.xml, yet without any warning or error message. I'm running encfs 1.7.4, rofs-filtered 1.5, fuse 2.9.4 on Fedora 22.

### Steps to reproduce:

1. Make a directory layout as follows in your home dir

    encfstest/
    encfstest/encrypted
    encfstest/filtered
    encfstest/source
    encfstest/source/test1.txt
    encfstest/source/test2.txt

2. Make a file `encfstest/filter.rc` with one line: `test2.txt`

3. Mount the rofs-filtered in the standard way:

```
rofs-filtered  ~/encfstest/filtered -o source=~/encfstest/source \
                    -o config=~/encfstest/filter.rc
```

4. Check that rofs-filtered is working as expected. It does. Only `test1.txt` appears in the directory `filtered`.

5. Use encfs in reverse mode.  (All other settings are standard.)

```
encfs --reverse ~/encfstest/filtered ~/encfstest/encrypted
```

I don't get to see anything in the directory `encrypted` and no file `filtered/.encfs6.xml` is present. The mount command does not report any mount on the directory `encrypted` either.

### Workaround:

1. Work with the following layout:

    encfstest/
    encfstest/container
    encfstest/container/filtered
    encfstest/encrypted
    encfstest/source
    encfstest/source/test1.txt
    encfstest/source/test2.txt

2. Make a file `encfstest/filter.rc` with one line: `test2.txt`

3. Mount the rofs-filtered in the standard way:

```
rofs-filtered  ~/encfstest/container/filtered -o source=~/encfstest/source \
                    -o config=~/encfstest/filter.rc
```

4. Check that rofs-filtered is working as expected. It does. Only `test1.txt` appears in the directory `conrtainer/filtered`.

5. Use encfs in reverse mode on the directory `container`. (All other settings are standard.)

```
encfs --reverse ~/encfstest/container ~/encfstest/encrypted
```

Now all works as expected.

**Comment by onlinespending** [comment]
I'm sure this should be obvious to you, but this doesn't work because rofs-filtered is a read-only FUSE filesystem as the name suggest. The .encfs file cannot be created in the read only filtered directory, which is why you need to have a writable container directory above it that you point encfs to.

**Comment by fulldecent** [comment]
I was not expecting the .encfs be saved into the ciphertext directory when using `--reverse`

**Comment by onlinespending** [comment]
the encfs manpage makes it pretty clear that it saves the .encfs file at the root of the plain-text directory, which in @tovrstra's use case is the rofs-filtered directory (and therefore read only).

**Comment by fulldecent** [comment]
Here is the man page https://github.com/vgough/encfs/blob/master/encfs/encfs.pod#options

Could you please let us know where you are seeing this?

**Comment by rfjakob** [comment]
You can set the environment variable ENCFS6_CONFIG to change the storage
location.

**Comment by fulldecent** [comment]
@tovrstra Can you please try this `ENCFS6_CONFIG` your test case to confirm it works for this use case

**Comment by tovrstra** [comment]
Thanks for explaining! That does the trick. Looking back at this, it now seems so obvious why it didn't work. I just didn't realize it back then.

It would have been nice though if encfs had printed an error message like this:

    Error: could not create config file: ~/encfstest/filtered/.encfs6.xml
    Aborting.

It's just a suggestion.
